<?php
$query = $this->getQuery();
$status = 1;   //1是所有,2是已回复,3是未回复
$page = 1;
if (isset($query['status']) && in_array($query['status'], array(2, 3))) {
   $status = $query['status'];
}
if (isset($query['page'])) {
   $query['page'] = (int) $query['page'];
   $query['page'] == 0 ? $page = 1 : $page = $query['page'];
}
$info = $this->getInquiryList($status, $page);
$list = $info['item'];
$total = $info['total'];
$out = '<table>';
$out1 = '';
$out2 = '';
if ($total) {
   $out .= '<tr class="inquiry_items">
        <th class="inquiry_title">询盘内容</th>
        <th class="inquiry_state">状态</th>
        <th class="inquiry_operate">操作</th>
    </tr>';
   foreach ($list as $item) {
      if ($status == 1) {
         $out .= getTemplate($item, $item->getOffer() == false ? 3 : 2);
      } else if ($status == 2) {
         if ($item->getOffer()) {
            $out .= getTemplate($item, 2);
         }
      } else if ($status == 3) {
         if (!$item->getOffer()) {
            $out .= getTemplate($item, 3);
         }
      }
   }
} else {
   $out .= '<tr class="inquiry_list no_inquiry ">
        <td colspan=3 >暂无询盘信息~~</td>
    </tr>';
}

$out .= '</table>';
echo $out;
function getTemplate($data, $status)
{
   if ($status == 2) {
      return '<tr class="inquiry_list ">
        <td class="inquiry_title">
            <span class="check"><em><i></i></em></span>
            <div class="acticle_box fr">
                <span>' . mb_substr($data->getContent(), 0, 80) . '</span>
                <a class="more" href="/inquirycontent/' . $data->getId() . '.html">更多</a>
            </div>
        </td>
        <td class="inquiry_state">已回复</td>
        <td class="inquiry_operate">
            <a href="/inquirycontent/'.$data->getId().'.html">查看详情</a>
        </td>
    </tr>';
   } else {
      return '<tr class="inquiry_list ">
        <td class="inquiry_title">
            <span class="check"><em><i></i></em></span>
            <div class="acticle_box fr">
                <span>' . mb_substr($data->getContent(), 0, 80) . '</span>
                <a class="more" href="/inquirycohtent/' . $data->getId() . '.html">更多</a>
            </div>
        </td>
        <td class="inquiry_state">未回复</td>
        <td class="inquiry_operate">
            <a href="">回复</a>
        </td>
    </tr>';
   }
}

?>