<?php
$result = $this->getFollowList();
$list = $result[0];
$total = $result[1];
$out = '';
if(count($list)){
   foreach($list as $follow){
      $id = $follow->getId();
      $company = $follow->getCompany();
      $url = $this->getCompanyUrl($company->getSubAttr());
      $provider = $company->getProvider();
      $linker = '';
      if($provider){
         $detail = $provider->getProfile();
         $sexText = $detail->getSex() ? '先生' : '女士';
         $linker = $detail->getRealName().' '.$sexText. ' '.$detail->getPosition().' ' .$detail->getShowPhone();
      }
      $products = $company->getProducts();
      $name = $company->getName();
      $out.='<div class="company_ele" fh-index="'.$id.'">
            <h4>'.$name.'</h4>
            <div class="company_container" style="width:910px">
                <div class="company_title clearfix">
                    <span>企业注册号</span>
                    <span>联系人</span>
                    <span>主营产品</span>
                </div>
                <div class="company_content clearfix">
                    <span>****</span>
                    <span>'.$linker.'</span>
                    <span>'.$products.'</span>
                </div>
                <p class="company_operation clearfix">
                    <i  class="icon-shanchu fr"></i>
                    <a href="'.$url.'" class="main_bg_light fr" target="__blank">企业商铺</a>
                </p>
            </div>
        </div>';
   }
}

$paging = $this->getPaging($total);
if($this->getParam('enablePage') && count($list) && $paging['total'] > 0){
   $out1 = '';
   $currentPage = $paging['current'];
   $cls = "";
   $out .= '<div class="page_list"><p>';
   if ($currentPage > 1) {
      $out.='<a href="'. $this->getPageUrl($currentPage - 1).'" class="prev_page">&lt; 上一页</a>';
   }else{
      $out.='<a class="prev_page">&lt; 上一页</a>';
   }
   if ($currentPage > 5) {
      $out.='<a href="'. $this->getPageUrl(1).'">1</a>... ';
      for ($i = ($currentPage - 2); $i <= $paging['total'] && $i <= $currentPage + 2; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a  class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
   } else {
      for ($i = 1; $i <= $paging['total'] && $i <= 6; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
      if ($paging['total'] > 6) {
         $out1 .='... ' . '<a href="'. $this->getPageUrl(7).'">7</a>';
      }
   }
   $out .= $out1;
   if ($paging['total'] > 0 && $currentPage != $paging['total']) {
      $out .= '<a href="'. $this->getPageUrl($currentPage + 1).'" class="next_page no_marginR" >下一页 &gt;</a>';
   }else{
      $out .= '<a class="next_page no_marginR" >下一页 &gt;</a>';
   }

   $out .= '</p></div>';
}

echo $out;
?>
