<?php
$query = $this->getQuery();
$attrs = $this->getCategoryaAttrs((int)$query['category']);
$out = '<div class="attr_wrap">';

foreach($attrs as $attr){
   $name = $attr->getName();
   $optValue = explode(',', $attr->getOptValue());
   $optValue = array_filter($optValue, function($val){
      if('' == $val){
         return false;
      }else{
         return true;
      }
   });
   $required = $attr->getRequired() ? 'required' : '';
   $star = $attr->getRequired() ? '*' : '';
   if(count($optValue)){
      $out.='<div class="attr_list clearfix basic">
            <span class="attr_title">'.$star.$name.'：</span>
            <div class="attr_info select_brand">
                <select class="attrSelect" id="'.$attr->getName().'"  '.$required.'>';
      foreach($optValue as $one){
         $out.='<option value="'.$one.'">'.$one.'</option>';
      }              
      $out.='</select></div></div>';
   }else{
      $out.='<div class="attr_list clearfix basic">
            <span class="attr_title">'.$star.$name.'：</span>
            <input class="attr_info input_text attrInput" type="text" '.$required.' id="'.$attr->getName().'" fh-type="length" minlength="1" maxlength="10"></div>';
   }
}
$out.='<p class="attr_add">
         <a>+添加属性</a>
         如果我们提供的产品属性无法满足你的需求，你可以自定义最多3个产品属性信息
     </p>';
$out.='</div>';

echo $out;