<ul class="top_nav_list">
    <li class=""><a href="/about/company.html"><i class="icon-gsjianjie"></i>企业简介</a></li>                    
    <li class=""><a href="/about/culture.html"><i class="icon-qiyewenhua"></i>企业文化</a></li>
    <li class=""><a href="/about/business.html"><i class="icon-info"></i>业务介绍</a></li>
    <li class=""><a href="/about/qualification.html"><i class="icon-zizhi"></i>企业资质</a></li>
    <li class=""><a href="/about/ad.html"><i class="icon-fengcai"></i>公司环境</a></li>
    <li class=""><a href="/about/join.html"><i class="icon-join"></i>加入我们</a></li>
    <li class=" "><a href="/about/legal.html"><i class="icon-falv"></i>法律声明</a></li>
    <li class=""><a href="/about/contact.html"><i class="icon-lianxiwomen"></i>联系我们</a></li>
</ul>