<?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
<!--搜索-->
<div class="header_search">
    <div class="header_search_inner conwidth clearfix">
        <div class="icon_logo fl">
            <a href="/">
                <img src="/Statics/Skins/Pc/Images/mall/icon/test_iocn_logo.png" alt="凤凰筑巢LOGO">
            </a>
        </div>
        <div class="header_search_box fr clearfix">
            <div class="search_box">
                <input type="text" placeholder="搜索您的问题" class="search_key">
                <span class="search_button">
                    搜索
                </span>
            </div>
            <div class="search_right_btn noselect fr mainbd_hover">
                <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=2788984873&amp;site=qq&amp;menu=yes" target="__blank">
                    <span>联系客服</span>
                </a>
            </div>
            <div class="search_right_btn noselect fr mainbd_hover">
                <a href="/">
                    <span>返回商城首页</span>
                </a>
            </div>
        </div>
    </div>
</div>
