<div class="header_top">
    <div class="conwidth clearfix">
        <div class="fl">
            欢迎来到凤凰筑巢！ 
				<?php
				$isLogin = $this->checkLogin();
				if (!$isLogin) {
					echo '<a class="login_btn main_hover" target="_blank" href="http://' . $this->getBuyerSiteName() . '/login.html">请登录</a> '
					. '<a class="register_btn main_hover" target="_blank" href="http://' . $this->getBuyerSiteName() . '/register.html">注册</a>';
				} else {
					$curUser = $this->getCurUser();
					$name = $curUser->getName() ? $curUser->getName() : $curUser->getPhone();
					echo '<a class="register_btn main_hover" target="_blank" href="http://' . $this->getBuyerSiteName() . '">' . $name . '</a>'
					. '<a class="login_btn main_hover logout">安全退出</a>';
				}
				?>
        </div>
        <ul class="fr header_top_nav main_hover">
            <li><a href="<?php echo 'http://' . $this->getBuyerSiteName() . '/quotationlist/1.html'; ?>">我的询价单</a></li>
            <li class="line"></li>
            <li><a href="<?php echo 'http://' . $this->getBuyerSiteName(); ?>">会员中心 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">我是 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a target="_blank" href="http://<?php echo $this->getProviderSiteName(); ?>">供应商专区</a></li>
            <li class="line"></li>
            <li><a href="">网站地图 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a target="_blank" href="/category/help.html">帮助中心</a></li>
            <li class="line"></li>
            <li class="more_btn mainbg_hover"><a>关注我们 <i class="iicon-xiangxiajiantou"></i></a>
                <div class="pull_more main_bg">
                    <img class="erweima" src="<?php Qs::Sys('loadImage', 'icon_erweima.png'); ?>">
                    <span>扫一扫<br>关注凤凰筑巢</span>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--搜索-->
<div class="header_search">
    <div class="header_search_inner conwidth clearfix">
        <div class="icon_logo fl">
            <a href="/">
                <img src="/Statics/Skins/Pc/Images/mall/icon/test_iocn_logo.png" alt="凤凰筑巢LOGO">
            </a>
        </div>
        <div class="header_search_box fr clearfix">
            <div class="search_box">
                <input type="text" placeholder="请输入产品的名称" class="search_key">
                <span class="search_button">
                    搜索
                </span>
            </div>
				<div class="search_right_btn noselect fr mainbd_hover">
                <a href="http://<?php echo $this->getBuyerSiteName(); ?>/quotationlist/1.html">
                    <i class="icon-bianji main"></i>
                    <span>我的个人中心</span>
                </a>
            </div>
            <div class="search_right_btn noselect fr mainbd_hover">
                <a href="http://<?php echo $this->getBuyerSiteName(); ?>/quotationlist/1.html">
                    <i class="icon-bianji main"></i>
                    <span>我的询价单</span>
                </a>
            </div>
        </div>
    </div>
</div>
<!--导航-->
<div class="nav main_bg_light">
    <div class="conwidth clearfix">
        <div class="all_sort fl">
            <span class="main_bg all_btn"><i class="icon-fenlei"></i>所有商品分类</span>

            <div class="sort_list" style="display: block">
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-jiancaizhuangxiu"></i>家装建材</h4>

                        <p>
                            <a href="../mall/prolist.html">欧式高景观型</a><a href="../mall/prolist.html">多功能坐躺型</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>家装建材</i></span>

                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-diangongdianqi"></i>电工电气 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a>
                            <a href="">睡袋/抱被</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>电工电气</i></span>

                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-dianziyuanqijian"></i>电子元件 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a>
                            <a href="">睡袋/抱被</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>电子元件</i></span>

                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-anquanfanghu"></i>安全防护 </h4>

                        <p>
                            <a href="">床垫</a><a href="">睡袋/抱被</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>安全防护</i></span>

                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-dashboard24"></i>仪器仪表 </h4>

                        <p>
                            <a href="">床垫</a>
                            <a href="">睡袋/抱被</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>仪器仪表</i></span>

                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <h5  class="sort_detail_h5">
                                欧式高景观型
                            </h5>
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-yejinkuangchan-copy"></i>冶金矿石 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a>
                            <a href="">睡袋/抱被</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>冶金矿石</i></span>

                        <div class="c_sort_detail">
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-dengjuzhaoming"></i>照明工业 </h4>

                        <p>
                            <a href="">床上用品</a>
                            <a href="">睡袋</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>照明工业</i></span>
                        <div class="c_sort_detail">
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                        <div class="c_sort_detail">
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-wujingongju"></i>五金工具 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>家装建材</i></span>
                        <div class="c_sort_detail">
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                        <div class="c_sort_detail">
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-biaozhunjianmro"></i>标准件 </h4>

                        <p>
                            <a href="">床垫</a>
                            <a href="">睡袋/抱被</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <span class="sort_intro"><i class="icon-jiancaizhuangxiu main"></i><i>家装建材</i></span>

                        <div class="c_sort_detail">
                            <a href="">欧式高景观型</a>
                            <a href="">多功能坐躺型</a>
                            <a href="">超宽舒适型</a>
                            <a href="">超轻便折叠型</a>
                            <a href="">运动型推车</a>
                            <a href="">双人推车</a>
                            <a href="">豪华定制型</a>
                            <a href="">推车配件</a>
                            <a href="">新 品</a>
                        </div>
                        <div class="c_sort_detail">
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                        <div class="c_sort_detail">
                            <a href="">0-15个月</a>
                            <a href="">0-4岁</a>
                            <a href="">0-7岁</a>
                            <a href="">9个月-7岁</a>
                            <a href="">9个月-12岁</a>
                            <a href="">ISOFIX</a>
                            <a href="">安全带固定</a>
                        </div>
                    </div>
                </div>
            </div>
            <span class="all_sort_bg" style="display: block"></span>
        </div>
        <ul class="fl nav_list">
            <li><a href="/" class="mainbg_hover">首页</a></li>
            <li><a href="/" class="mainbg_hover">活动</a></li>
            <li><a href="/category/laobanneican.html" class="mainbg_hover">建材老板内参</a></li>
            <li><a href="/" class="mainbg_hover">企业库</a></li>
        </ul>
    </div>
</div>
