<div class="header">
    <div class="header_content conwidth clearfix ">
        <a class=" header_left fl" href="/">
            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_top_logo.png') ?>" alt="">
        </a>
        <div class="header_right fr">
            <ul>
                <li class="main_bg"><a href="/">首页</a></li>
                <!--<li><a href="">我要购买</a></li>-->
                <li><a href="">成功案例</a></li>
                <li><a href="">模板演示</a></li>
                <li><a href="">功能介绍</a></li>
                <li><a href="">关于我们</a></li>
            </ul>
        </div>
    </div>
</div>