<?php
$goodsLists = $this->searchProduct();
$queryAttrs = $goodsLists['queryAttrs'];
$totalPage = ceil($goodsLists['total'] / $this->invokeParams['outputNum']);
$currentPage = $this->getRouteInfo()['pageId'];
$queryUrl = $this->getQueryUrl();
$totalquery = count($queryAttrs);
$out = '<div class="choose_wrap">
                        <div class="choose_list">';
if($totalquery){
   $out.='<dl class="list_item choosed"><dt>已选条件：</dt><dd></dd></dl>';
}else{
   $out.='<dl class="list_item choosed no_bb"><dt>已选条件：</dt><dd></dd></dl>';
}
                     

$index = 0;
foreach ($queryAttrs as $name => $attrs) {
   $out .= '<dl class="list_item';
   if ($index == 1) {
      $out .= ' no_bb';
   } else if ($index > 1) {
      $out .=$index == ($totalquery - 1) ? ' no_bb hide' : ' hide';
   }
   $out .= '"><dt>' . $name . '：</dt>
                                <dd>
                                    <ul class="clearfix">
                                        ';
   foreach ($attrs as $value) {
      $out .= '<li><a  id="' . $name . '" data="' . $value . '">' . $value . '</a></li>';
   }
   $out .= '</ul>';
   if(count($attrs) > 8){
      $out.='<!--更多--><span class="more"><em>更多</em><i class="i_down icon-jiantou3"></i></span>';
   }
   $out.='</dd></dl>';
   $index++;
}
$out.='</div>';
if ($totalquery > 2) {
   $out.='        <!--显示更多-->
                        <div class="show_more"><span>更多选项</span><i class="icon-jiantou3"></i></div>';
}
$out .= '</div>
                    <!--排序-->
                    <div class="rank_wrap clearfix">
                        <ul class="clearfix">
                            <li id="4"><a >综合<i class="icon-rank-down"></i></a></li>
                            <li id="3"><a >价格<i class="icon-rank-down"></i></a></li>
                            <li id="2"><a >人气<i class="icon-rank-down"></i></a></li>
                            <li id="1"><a class="alink_last" >最新<i class="icon-rank-down"></i></a></li>
                        </ul>
                        <!--<span class="check"><i></i><em>工厂认证</em></span>-->
                        <span class="check price"><i></i><em>有价格</em></span>
                        <!--页码-->';
if ($totalPage > 1) {
   $out.=' <span class="page clearfix">';
   if ($currentPage == 1 && $currentPage < $totalPage) {
      $url = $this->getPageUrl($currentPage + 1);
      $out .= '<i class="icon-jiantou7 fl"></i>
                            <em class="main">' . $currentPage . '</em>/' . $totalPage . '
                            <a href="'.$url . $queryUrl . '" ><i class="icon-jiantou6 fr"></i></a>';
   } else if ($currentPage == 1 && 1 == $totalPage) {
      $out .= '<i class="icon-jiantou7 fl"></i>
                            <em class="main">' . $currentPage . '</em>/' . $totalPage . '
                            <i class="icon-jiantou6 fr"></i>';
   } else if ($currentPage > 1 && $currentPage == $totalPage) {
      $url = $this->getPageUrl($currentPage - 1);
      $out .= '<a href="'.$url . $queryUrl . '"><i class="icon-jiantou7 fl"></i></a>
                            <em class="main">' . $currentPage . '</em>/' . $totalPage . '
                            <i class="icon-jiantou6 fr"></i>';
   } else if ($currentPage > 1 && $currentPage < $totalPage) {
      $prevurl = $this->getPageUrl($currentPage - 1);
      $nexturl = $this->getPageUrl($currentPage + 1);
      $out .= '<a href="'.$prevurl . $queryUrl . '"><i class="icon-jiantou7 fl"></i></a>
                            <em class="main">' . $currentPage . '</em>/' . $totalPage . '
                            <a href="'.$nexturl . $queryUrl . '"><i class="icon-jiantou6 fr"></i></a>';
   }
   $out.='</span>';
}
$out .= '</div>';
echo $out;
