<?php
$out = '<div id="shaixuanBox" class="shaixuan_box hide">
    <div id="shaixuanIndex" class="shaixuan_list">
        <div class="shaixuan_head">
            <a class="fl cancel">取消</a>
            <span>筛选</span>
            <a class="fr save">确定</a>
        </div>
        <ul id="shaixuanListNav" class="module_text_nav">';
$keys = $this->getKeys();
$list = $this->searchProduct();
$queryAttrs = $list['queryAttrs'];
$goodsLists = $list['docs'];
$total = $list['total'];
foreach ($queryAttrs as $key => $value) {
   $out .= '<li><a>'.$key.'</a><span class="choose_text">不限</span></li>';
}
$out .= '</ul>
        <div class="user_action">
            <a class="submit_btn mainbgcolor">清除选中</a>
        </div>
    </div><div id="shaixuanListBox" class="shaixuan_list_box shaixuan_list">';
foreach ($queryAttrs as $key => $value) {
   $out .= '<div class="shaixuan_item">
            <div class="shaixuan_head">
                <a class="fl goback">
                    <i class="icon-fanhuijian"></i>
                </a>
                <span>'.$key.'</span>
            </div>
            <ul class="module_text_nav">
                <li>不限</li>';
   foreach ($value as $val) {
      $out .= '<li id="'.$key.'" data="'.$val.'"><a class="no_after">'.$val.'</a><i class="icon-checked"></i></li>';
   }
   $out .= '</ul>
        </div>';
}
$out .= '</div>
</div><div class="card_box">
    <ul class="card3">';
foreach ($goodsLists as $goods) {
	$url = $this->getProductUrl($goods['number']);
	$image = \Cntysoft\Kernel\get_image_cdn_url($goods['defaultImage'], 170, 170);
	$name = $goods['brand'].$goods['title'].$goods['description'];
   $out .= '<li>
            <a href="'.$url.'">
                <div class="pro_img">
                    <div class="pro_table">
                        <img src="'.$image.'" alt=""/>
                    </div>
                </div>
                <p class="pro_text">'.$name.'</p>
                <p class="pro_price add_color">¥'.($goods['price']>0 ? $goods['price'] : "面议").'</p>
            </a>
        </li>';
}
$out .= '</ul>
</div>';
echo $out;
?>