<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/标准内容模型', 'AC')
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">  
        <meta name="description" content="<?php Qs::DsField('AC', 'intro') ?>">
        <meta name="keywords" content="<?php Qs::DsField('AC', 'keywords') ?>">
        <?php Qs::Sys('loadCss', array('referenceindex/style.css', 'referenceindex/referenceinfo.css', 'swiper.min.css')) ?>
    </head>
    <body>
        <!--返回，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--返回-->
            <div class="header_back_box fl">
                <a class="header_back" id="historyBack"><i class="icon-fanhuijian"></i></a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc"><?php Qs::DsField('AC', 'title') ?></h2>
            </div>
            <!--搜索-->
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="/category/laobanneican.html">首页</a></li>
                    <li><a href="/category/jiancaiqiwen/1.html">建材奇闻</a></li>
                    <li><a href="/category/shendujiexi/1.html">深度解析</a></li>
                    <li><a href="/category/zhongbangtuijian/1.html">重磅推荐</a></li>
                </ul>
            </div>
        </div>
        <!--内容详情-->
        <div class="main_content" article="<?php Qs::DsField('AC', 'id') ?>">
            <div class="content_title">
                <h3><?php Qs::DsField('AC', 'title') ?></h3>

                <div class="writer_info">
                    <span class="date"><?php echo date('Y.m.d', QS::DsField('AC', 'inputTime', true)) ?></span>
                    <span>阅读量：<i><?php Qs::DsField('AC', 'hits') ?></i></span>
                </div>
            </div>
            <div class="module_content">
                <?php Qs::DsField('AC', 'content') ?>
                <div class="up_down">
                    <div>
                        上一篇：<?php
                        $prev = Qs::DsField('AC', 'prev', true);
                        if ($prev) {
                           $pretitle = iconv_substr($prev[1], 0, 15, 'UTF-8');
                           echo '<a style="color: #333;" href="' . $prev[0] . '">' . $pretitle . '</a>';
                        } else {
                           echo '木有了';
                        }
                        ?>
                    </div>
                    <div>
                        下一篇：<?php
                        $next = Qs::DsField('AC', 'next', true);
                        if ($next) {
                           $nexttitle = iconv_substr($next[1], 0, 15, 'UTF-8');
                           echo '<a style="color: #333;" href="' . $next[0] . '">' . $nexttitle . '</a>';
                        } else {
                           echo '正在更新中，请等待~';
                        }
                        ?>
                    </div>
                </div>
                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'ChangyanCommentWap')) ?>
            </div>
            <div class="relevant_box">
                <h3 class="relevant_title"><a href="/category/laobanneican.html">相关推荐</a></h3>
                <ul class="relevant_list_box">
                    <?php
                    Qs::Label('文章/老板内参', array('renderTpl'      => 'Mobile_RecommendArticle', 'nodeIdentifier' => array(
                          'laobanneican', 'jiancaiqiwen', 'shendujiexi', 'zhongbangtuijian'
                       ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 8, 'enablePage'     => false, 'listSubNode'    => true))
                    ?>
                </ul>
            </div>
        </div>
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
        <?php
        Qs::Sys('loadRequireJs', 'reference/referenceinfo')
        ?>      
    </body>
</html>