<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('栏目数据源/栏目SEO', 'category');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>老版内参-首页-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">  
        <meta name="description" content="<?php Qs::DsField('category', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('category', 'keyword') ?>">
        <?php Qs::Sys('loadCss', array('referenceindex/style.css', 'referenceindex/referenceindex.css', 'swiper.min.css')) ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">老板内参</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="/category/laobanneican.html">首页</a></li>
                    <li><a href="/category/jiancaiqiwen/1.html">建材奇闻</a></li>
                    <li><a href="/category/shendujiexi/1.html">深度解析</a></li>
                    <li><a href="/category/zhongbangtuijian/1.html">重磅推荐</a></li>
                </ul>
            </div>
        </div>
        <!--一列广告滑动-->


        <?php
        Qs::Label('文章/老板内参', array('renderTpl'      => 'Mobile_DefaultList', 'nodeIdentifier' => array(
              'laobanneican', 'jiancaiqiwen', 'shendujiexi', 'zhongbangtuijian'
           ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 6, 'enablePage'     => false, 'listSubNode'    => true));
        Qs::Sys('loadRequireJs', 'reference/referenceindex')
        ?>      
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                Copyright 2010-2016 www.fhzc.com All Rights Reserved 豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
    </body>
</html>