<!--版权 begin-->
<div class="login_footer">
    <ul class="copy_nav clearfix">
        <li>
            <a href="" target="_blank">关于我们</a>
            <span></span>
        </li>
        <li>
            <a href="" target="_blank">联系我们</a>
            <span></span>
        </li>
        <li>
            <a href="" target="_blank">友情链接</a>
            <span></span>
        </li>
        <li>
            <a href="" target="_blank">帮助中心</a>
            <span></span>
        </li>
        <li>
            <a href="" target="_blank">意见反馈</a>
            <span></span>
        </li>
        <li>
            <a href="" target="_blank">高薪聘请</a>
            <span></span>
        </li>
        <li>
            <a href="" target="_blank">法律声明</a>
        </li>
    </ul>
    <div class="copyright">© 2015 LaoKeBa.com 凤凰筑巢 保留所有权利</div>
    <div class="copy_icp">Copyright 2008-2016 GongChang.com All Rights Reserved 豫ICP备11020782号-15-</div>
</div>