<!--版权 begin-->
<div class="login_footer">
    <ul class="copy_nav clearfix">
        <li>
            <a target="_blank" class="main_hover" href="<?php echo 'http://' .\Cntysoft\RT_PROVIDER_SITE_NAME; ?>">供应商专区</a>
            <span></span>
        </li>
        <li>
            <a target="_blank" class="main_hover" href="<?php echo 'http://' .\Cntysoft\RT_BUYER_SITE_NAME; ?>">采购商专区</a>
            <span></span>
        </li>
        <li>
            <a target="_blank" class="main_hover" href="<?php echo 'http://' .\Cntysoft\RT_SYS_SITE_NAME; ?>/category/zhuchaoschool.html">筑巢商学院</a>
            <span></span>
        </li>
        <li>
            <a target="_blank" class="main_hover" href="<?php echo 'http://' .\Cntysoft\RT_SYS_SITE_NAME; ?>/category/laobanneican.html">老板内参</a>
            <span></span>
        </li>
        <li>
            <a target="_blank" class="main_hover" href="<?php echo 'http://' .\Cntysoft\RT_SYS_SITE_NAME; ?>/category/help.html">帮助中心</a>
        </li>
    </ul>
    <div class="copyright">© 2016 www.fhzc.com 凤凰筑巢 保留所有权利</div>
    <div class="copy_icp">Copyright 2010-2016 Fhzc.com All Rights Reserved 增值电信业务经营许可证：豫 B2-20160047 <a class="main_hover" target="_blank" href="http://www.miibeian.gov.cn"> 豫ICP备14029737号</a> <?php echo round((microtime(true) - SYS_START_TIME)*1000, 2) . 'ms'; ?></div>
</div>