<?php
Qs::Ds('用户数据源/供应商', 'User');
Qs::Ds('商城数据源/商城数据', 'site');
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>我的信息-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('usercenter/providerstyle.css', 'usercenter/prolistgroup.css')) ?>
        <style>
            .layui-layer-input{
               width:240px;
            }
            select{
               background-color: #fff;
            }
            .search_select {
               margin : 0;
            }
        </style>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧') ?>
            <!--右侧内容-->
            <div class="content_wrap fr">
        <h1 class="items_title">管理产品分组</h1>
        <!--回复 未回复-->
        <ul class="reply clearfix">
            <li fh-type=1><a>产品分组</a></li>
            <li fh-type=2><a>管理分组产品</a></li>
            <li fh-type=3 style="margin-left:20px;" class="hide"><a>添加分组</a></li>
        </ul>
        <!--管理产品分组-->
        <div class="group_list hide">
            <?php Qs::Label('供应商/产品分组', array('renderTpl' => 'GroupList'))?>
        </div>
        <!--产品分组-->
         <?php Qs::Label('供应商/产品分组', array('renderTpl' => 'GroupProductList', 'enablePage' => true, 'outputNum' => 8))?>
    </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
        <?php Qs::Sys('loadRequireJs', 'provider/prolistgroup') ?>
    </body>
</html>