<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'site');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>修改产品-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'lib/default.css', 'lib/reset.css', 'usercenter/publish_info.css')) ?>
        <style type="text/css" rel="stylesheet">
            .ke-icon-upload {
                background-position: 0px -496px;
                width: 50px;
                height: 16px;
                height: 16px;
            }
            div.radio i {
                width: 16px;
                height: 16px;
                width:16px\9\0;
                height:16px\9\0;
                *width:0;
                *height:0;
            }
        </style>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">上架产品信息</h1>
                <?php Qs::Label('供应商/商品内容', array('renderTpl' => 'ProductChange')) ?>
            </div>
        </div>
    </div>
    <div class="hide" id="editorUpload"></div>
    <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
    <?php Qs::Sys('loadRequireJs', 'provider/productchange') ?>
</body>
</html>