<?php Qs::Ds('商城数据源/商城数据', 'sites'); ?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>商家忘记密码</title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <?php Qs::Sys('loadCss', array('kelepc/style.css', 'kelepc/login/login.css')) ?>
    </head>
    <body>
        <div class="logo_register clearfix">
            <a href="/">               
                <div class="icon_logo">
                </div>
            </a>
            <h3>商家忘记密码找回</h3>
        </div>
        <div class="wrap">
            <div class="wrap_inner">
                <div class="login_box">
                    <div class="login_header">
                        <h4 class="login_title">忘记密码
                        </h4>
                    </div>
                    <div class="login_form" id="nameForm">
                        <form action="">
                            <div class="login_form_input">
                                <input class="form_text" type="text" fh-type="phone" id="username" placeholder="请输入注册时使用的手机号" required>
                                <!--验证码-->
                                <div class="input_code clearfix">
                                    <input class="fl code" type="text" fh-type="imgCode" id="imgCode" autocomplete="off" placeholder="图片验证码" required>
                                    <a class="icode_image" >
                                        <img alt="图片验证码" title="看不清换一张" id="codeImg" src="/">
                                        <i class="icon-shuaxin"  id="changeCodeImg"></i>
                                    </a>
                                </div>
                                <!--短信验证码
                                <div class="input_code clearfix">
                                    <input class="fl code" type="text" name="code" autocomplete="off" placeholder="请输入短信验证码">
                                    <a class="icode_image tc main_bg_light main_border_light" >
                                        <span>获取短信验证码</span>
                                    </a>
                                </div>-->

                            </div>
                            <!--提交-->
                            <input class="submit_btn main_bg_light" id="nameFormSubmit"  type="submit" value="找回密码"/>
                        </form>
                    </div>
                    <div class="login_form hide" id="passwordForm" >
                        <form action="">
                            <div class="login_form_input">
                                <!--密码-->
                                <input class="fl code" type="text" fh-type="phoneAuthCode" id="phoneAuthCode" autocomplete="off" placeholder="请输入短信验证码" required>
                                <input class="form_text" type="password" fh-type="password" id="password" placeholder="请输入新密码" required>
                                <input class="form_text" type="password" fh-type="password" id="passwordAgain" placeholder="请再次输入新密码" required>
                            </div>
                            <!--提交-->
                            <input class="submit_btn main_bg_light" id="passwordFormSubmit" type="submit" value="确认"/>
                        </form>
                    </div>
                    <!--成功-->
                    <div class="login_form tc success hide"  id="successForm">
                        <i class="icon-duihao1"></i>
                        <p>新密码设置成功，请您牢记新密码</p>
                        <!--返回首页-->
                        <a class="return_btn main_bg_light" href="/login.html">立即登录</a>
                    </div>
                </div>
            </div>
        </div>
        <!--版权 begin-->
        <?php
        Qs::Label('静态类/登陆注册网站底部', array('renderTpl' => 'Pc_KeleLoginBottom'));
        Qs::Sys('loadRequireJs', 'kelepc/forget');
        ?>
    </body>
</html>