<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>商家注册</title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <?php Qs::Sys('loadCss', array('kelepc/style.css', 'kelepc/login/login.css')) ?>
    </head>
    <body>
        <div class="logo_register clearfix">
            <a href="/">               
                <div class="icon_logo">
                </div>
            </a>
            <h3>商家注册</h3>
        </div>
        <div class="wrap">
            <div class="wrap_inner">
                <div class="login_box">
                    <div class="login_header">
                        <h4 class="login_title">账户注册</h4>
                    </div>
                    <div class="login_form">
                        <form action="">
                            <div class="login_form_input">
                                <input class="form_text" type="text" fh-type="phone"  id="phone" placeholder="请输入手机号" required>
                                <!--密码-->
                                <input class="form_text" type="password" fh-type="password"  id="password" placeholder="请输入字母、数字、符号均可，6-25个字符的密码" required>
                                <!--再次输入密码-->
                                <input class="form_text" type="password" fh-type="password"  id="password2" placeholder="请再次输入密码" required>
                                <!--验证码-->
                                <div class="input_code clearfix">
                                    <input class="fl code" type="text" fh-type="imgCode" id="imgCode" autocomplete="off" placeholder="图片验证码" required >
                                    <a class="icode_image" >
                                        <img alt="图片验证码" id="codeImg"  title="看不清换一张" src="">
                                        <i class="icon-shuaxin" id="changeCodeImg"></i>
                                    </a>
                                </div>
                                <!--获取短信验证码-->
                                <div class="input_code clearfix">
                                    <input class="fl code" type="text" fh-type="phoneAuthCode" id="phoneAuthCode" autocomplete="off" placeholder="请输入短信验证码" required>
                                    <a class="icode_image tc"  id="sendMessage" >
                                        <span>获取短信验证码</span>
                                    </a>
                                </div>
                            </div>
                            <!--忘记密码-->
                            <div class="login_forget clearfix">
                                <div class="login_auto checked">
                                    <i class="icon-checked main_light"></i><span>我已经同意《可乐云商用户注册协议》</span>
                                </div>
                                <a href="/login.html" class="main_light">已有帐号？直接登录</a>
                            </div>
                            <!--提交-->
                            <input class="submit_btn main_bg_light" type="submit" id="submit" value="立即注册">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!--版权 begin-->
        <?php
        Qs::Label('静态类/登陆注册网站底部', array('renderTpl' => 'Pc_KeleLoginBottom'));
        Qs::Sys('loadRequireJs', 'kelepc/register');
        ?>
    </body>
</html>