<?php Qs::Ds('用户数据源/供应商', 'provider') ?>
<div class="header_top">
    <div class="conwidth header_top_inner clearfix">
        <div class="fl">
            <a href="http://<?php echo \Cntysoft\PROVIDER_SITE_NAME_DEVEL; ?>">欢迎使用可乐云商！</a> <a class="login_btn main_hover" id="providerName" href="http://<?php echo \Cntysoft\RT_PROVIDER_SITE_NAME ?>/account/index.html"><?php Qs::DsField('provider', 'name') ?></a><a class="register_btn main_hover" id="providerlogout">安全退出</a>
        </div>
        <ul class="fr header_top_nav main_hover">
            <li><a href="">网站地图 <i class="icon-xiangxiajiantou"></i></a>
                <div class="down_list">
                    <a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/help.html">帮助中心</a>
                    <a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/laobanneican.html">老板内参</a>
                    <a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/zhuchaoschool.html">筑巢商学院</a>
                </div></li>
            <li class="line"></li>
            <li><a target="_blank" href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/help.html">帮助中心</a></li>
            <li class="line"></li>
            <li class="more_btn mainbg_hover"><a>关注我们 <i class="iicon-xiangxiajiantou"></i></a>
                <div class="pull_more main_bg">
                    <img class="erweima" src="<?php Qs::Sys('loadImage', 'icon_erweima.png'); ?>">
                    <span>扫一扫<br>关注可乐云商</span>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--个人中心头部-->
<div class="head_wrap main_bg_light">
    <div class="head_box conwidth clearfix">
        <a class="logo_img fl" href="http://<?php echo \Cntysoft\PROVIDER_SITE_NAME_DEVEL ?>"><img src="<?php Qs::Sys('loadImage', 'logo_white.png'); ?>"> </a>
        <ul class="fr clearfix">
            <li><a class=" <?php
					 echo $this->checkFirst();
					 ?> mainbg_hover" href="/">首页</a></li>
            <li><a class="<?php
					 echo $this->checkUrl('account');
					 ?> mainbg_hover" href="/account/index.html">账号中心</a></li>
            <li><a class="<?php
					 echo $this->checkUrl('inquiry');
					 ?> mainbg_hover" href="/inquiry/1.html">询价单</a></li>
            <li><a class="<?php
					 echo $this->checkUrl('product');
					 ?> mainbg_hover" href="/product/1.html">产品中心</a></li>
            <li><a class="<?php
					 echo $this->checkUrl('site');
					 ?> mainbg_hover" href="/site/news/1.html">店铺设置</a></li>
        </ul>
    </div>
</div>
