<!--<div class="header_top">
    <div class="conwidth header_top_inner clearfix">
        <ul class="fr header_top_nav main_hover">
            <li><a href="">我的询价单</a></li>
            <li class="line"></li>
            <li><a href="">会员中心 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">我是 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">供应商专区</a></li>
            <li class="line"></li>
            <li><a href="">运营商专区</a></li>
            <li class="line"></li>
            <li><a href="">网站地图 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">帮助中心</a></li>
            <li class="line"></li>
            <li class="more_btn mainbg_hover"><a>关注我们 <i class="iicon-xiangxiajiantou"></i></a>
                <div class="pull_more main_bg">
                    <img class="erweima" src="<?php Qs::Sys('loadImage', 'icon_erweima.png'); ?>">
                    <span>扫一扫关注凤凰筑巢</span>
                </div>
            </li>
        </ul>
    </div>
</div>-->
<!--个人中心头部-->
<div class="head_wrap main_bg_light">
    <div class="head_box conwidth clearfix">
        <a class="logo_img fl" href="http://devel.abc.com"><img src="<?php Qs::Sys('loadImage', 'logo_white.png'); ?>"> </a>
        <ul class="fr clearfix">
            <li><a class=" <?php
                echo $this->checkFirst();
                ?> mainbg_hover" href="/">首页</a></li>
            <li><a class="<?php
                echo $this->checkUrl('account');
                ?> mainbg_hover" href="/account/index.html">账号中心</a></li>
            <li><a class="<?php
                echo $this->checkUrl('inquiry');
                ?> mainbg_hover" href="/inquiry/1.html">询价单</a></li>
            <li><a class="<?php
                echo $this->checkUrl('product');
                ?> mainbg_hover" href="/product/1.html">产品中心</a></li>
            <li><a class="<?php
                echo $this->checkUrl('site');
                ?> mainbg_hover" href="/site/news/1.html">店铺设置</a></li>
        </ul>
    </div>
</div>
