<?php


?>
<table>
    <tr class="inquiry_items">
        <th class="inquiry_title">询盘内容</th>
        <th class="inquiry_state">状态</th>
        <th class="inquiry_operate">操作</th>
    </tr>
    <tr class="inquiry_list ">
        <td class="inquiry_title">
            <span class="check"><em><i></i></em></span>
            <div class="acticle_box fr">
                <span>3月2日，国家统计局日前发布了中国制造业和非制造业采购经
                    理指数。数据显示，2016年2月份，中国制造业采购经理指数
                    (PMI)为49.0%，国家统计局日前发布了中国制造业和非制造业采购经国家统计局日前发布了中国制造业和非制造业采购经
                    国家统计局日前发布了中国制造业和非制造业采购经</span>
                <a class="more" href="#">更多</a>
            </div>

        </td>
        <td class="inquiry_state">已读</td>
        <td class="inquiry_operate">
            <a href="">修改</a>
            <span>|</span>
            <a href="">删除</a>
        </td>
    </tr>
    <tr class="inquiry_list ">
        <td class="inquiry_title">
            <span class="check"><em><i></i></em></span>
            <div class="acticle_box fr">
                <span>3月2日，国家统计局日前发布了中国制造业和非制造业采购经
                    理指数。数据显示，2016年2月份，中国制造业采购经理指数
                    (PMI)为49.0%，国家统计局日前发布了中国制造业和非制造业采购经国家统计局日前发布了中国制造业和非制造业采购经
                    国家统计局日前发布了中国制造业和非制造业采购经</span>
                <a class="more" href="#">更多</a>
            </div>

        </td>
        <td class="inquiry_state">已读</td>
        <td class="inquiry_operate">
            <a href="">修改</a>
            <span>|</span>
            <a href="">删除</a>
        </td>
    </tr>
    <tr class="inquiry_list ">
        <td class="inquiry_title">
            <span class="check"><em><i></i></em></span>
            <div class="acticle_box fr">
                <span>3月2日，国家统计局日前发布了中国制造业和非制造业采购经
                    理指数。数据显示，2016年2月份，中国制造业采购经理指数
                    (PMI)为49.0%，国家统计局日前发布了中国制造业和非制造业采购经国家统计局日前发布了中国制造业和非制造业采购经
                    国家统计局日前发布了中国制造业和非制造业采购经</span>
                <a class="more" href="#">更多</a>
            </div>

        </td>
        <td class="inquiry_state">已读</td>
        <td class="inquiry_operate">
            <a href="">修改</a>
            <span>|</span>
            <a href="">删除</a>
        </td>
    </tr>
    <!--暂无询盘信息-->
    <tr class="inquiry_list no_inquiry ">
        <td colspan=3 >暂无询盘信息~~</td>
    </tr>
</table>