<!DOCTYPE html>
<?php Qs::Ds('内容数据源/企业信息', 'CP') ?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－产品中心</title>
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/company_prolist.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--内容-->
        <div class="content conwidth clearfix">
            <!--站点指示-->
            <div class="site">
                <a href="/">首页</a>
                <span>&gt;</span>
                <a class="main">产品中心</a>
            </div>
            <!--左侧公司信息-->
            <div class="l_section fl">
                <!--公司信息-->
                <div class="company_info">
                    <div class="company_name">
                        <h1><?php Qs::DsField('CP', 'name') ?></h1>
                        <p>
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi1.png') ?>" title="资质好" alt="资质好">
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi2.png') ?>" title="诚信商家" alt="诚信商家">
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi2.png') ?>" title="有良心商家" alt="有良心商家">
                        </p>
                    </div>
                    <div class="company_intro">
                        <dl>
                            <dt>经营模式</dt>
                            <dd><?php
                                $trade = array(1 => '销售型', '生产型', '设计型', '信息服务型', '销售+生产型', '销售+设计型', '生产+设计型', '销售+生产+设计型');
                                echo $trade[Qs::DsField('CP', 'tradeMode', true)]
                                ?></dd>
                        </dl>
                        <dl>
                            <dt>所在地区</dt>
                            <dd><?php echo ' ' . implode(' ', Qs::DsField('CP', 'PCD', true)) ?></dd>
                        </dl>
                        <dl>
                            <dt>联系人</dt>
                            <dd><?php Qs::DsField('CP', 'providername') ?></dd>
                        </dl>
                        <dl>
                            <dt>联系电话</dt>
                            <dd><?php Qs::DsField('CP', 'contact') ?></dd>
                        </dl>
                        <dl>
                            <dt>工作时间</dt>
                            <dd>
                                <p>周一到周五</p>
                                <p>(08:30-18:30)</p>
                            </dd>
                        </dl>
                    </div>
                </div>
                <!--产品分类-->
                <!--                <div class="product_classify">
                                    <h1>全部分类<em>121355</em></h1>
                                    <div class="classify_list">
                                        <h2><i class="icon-black-right"></i>一级分类<em>12352</em></h2>
                                        <ul>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                        </ul>
                                    </div>
                                    <div class="classify_list">
                                        <h2><i class="icon-black-right"></i>一级分类<em>12352</em></h2>
                                        <ul>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                        </ul>
                                    </div>
                                    <div class="classify_list">
                                        <h2><i class="icon-black-right"></i>一级分类<em>12352</em></h2>
                                        <ul>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                        </ul>
                                    </div>
                                    <div class="classify_list">
                                        <h2><i class="icon-black-right"></i>一级分类<em>12352</em></h2>
                                        <ul>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                            <li><a href="#">二级分类<em>322</em></a></li>
                                        </ul>
                                    </div>
                                </div>-->
            </div>

            <!--右侧内容列表-->
            <div class="r_section fr">
                <?php Qs::Label('企业网站/产品', array('renderTpl' => 'Pc_ProductList', 'outputNum' => 12, 'enablePage' => true)); ?>
            </div>
        </div>
        <!--底部-->
        <?php Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <?php Qs::Sys('loadRequireJs', 'company/company_prolist') ?>

    </body>
</html>
