<!DOCTYPE html>
<?php
Qs::Ds('商品数据源/商品信息', 'goods');
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('goods', 'name') ?>-产品详情-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('slick.css', 'company/style.css', 'company/commpany_proinfo.css')) ?>
        <script>window._bd_share_config = {
              "common" : {
                 "bdSnsKey" : {},
                 "bdText" : "",
                 "bdMini" : "2",
                 "bdMiniList" : false,
                 "bdPic" : "",
                 "bdStyle" : "0",
                 "bdSize" : "16"
              }, "share" : {"bdSize" : 16}
           };
           with (document)
              0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
        </script>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top', 'company' => 'companysite')) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--内容-->
        <?php Qs::Label('企业网站/产品', array('renderTpl' => 'Pc_GoodsContent')) ?>
        <!--底部-->
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',));
        Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyRight',))
        ?>
        <div id='totop'><a style="display: none"><i class='icon-jiantou1'></i></a><a><i class='icon-kefu'></i><em>客服</em>
                <div class='block'><span>电话：<?php Qs::DsField('CP', 'contact') ?></span></div></a></div>
                <?php Qs::Sys('loadRequireJs', 'company/company_proinfo') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>

    </body>
</html>
