<!DOCTYPE html>
<?php Qs::Ds('内容数据源/企业设置', 'CS') ?>
<?php
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－关于我们-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/aboutus.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top', 'company' => 'companysite')) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a  class="main_hover"href="/">首页</a>
            <span>&gt;</span>
            <a class="main">关于我们</a>
        </div>
        <div class="l_main conwidth clearfix">
            <div class="m_left fl">
                <h3>关于我们</h3>
                <ul>
                    <li><a  class="active_hover" href="/about.html?intro">企业介绍</a></li>
                    <li><a  class="active_hover" href="/about.html?culture">企业文化</a></li>
                    <li><a class="active_hover" href="/about.html?zizhi">企业资质</a></li>
                    <li><a class="active_hover" href="/about.html?environ">企业环境</a></li>
                    <li class="no_bb "><a class="active_hover" href="/about.html?connect">联系我们</a></li>
                </ul>
            </div>
            <div class="m_right fr">
                <!--//公司介绍-->
                <div class="m_intro m_culture hide company_intro">
                    <h3>企业介绍</h3>
                    <?php Qs::DsField('CS', 1)
                    ?>
                </div>
                <!--企业文化-->
                <div class="m_culture hide company_culture">
                    <h3>企业文化</h3>
                    <?php Qs::DsField('CS', 2)
                    ?>
                </div>
                <!--资质-->
                <div class="m_zizhi m_intro hide company_zizhi">
                    <h3>企业资质</h3>
                    <?php Qs::DsField('CS', 3)
                    ?>
                </div>
                <!--企业环境-->
                <div class="m_culture  hide company_environ" style="margin-left: 0px">
                    <h3>企业环境</h3>
                    <?php
                    $environments = Qs::DsField('setting', 'environment', true);
                    foreach ($environments as $value) {
                       echo' <p><img src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" class="lazy" data-original="' . $value['image'] . '" style="display: block;"></p>';
                    }
                    ?>
                </div>
                <!--联系我们-->
                <div class="m_connect m_intro hide company_connect" style="margin-left: 0px">
                    <h3>联系我们</h3>
                    <?php Qs::DsField('CS', 4)
                    ?>
                </div>
            </div>
        </div>
        <!--底部-->
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',));
        Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyRight',))
        ?>
        <div id='totop'><a style="display: none"><i class='icon-jiantou1'></i></a><a><i class='icon-kefu'></i><em>客服</em>
                <div class='block'><span>电话：<?php Qs::DsField('CP', 'contact') ?></span></div></a></div>
                <?php Qs::Sys('loadRequireJs', 'company/aboutus') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>
        <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=BPWH0tb47EkNlH6fGGzh381M"></script>
    </body>
</html>
