<!DOCTYPE html>
<?php Qs::Ds('内容数据源/企业设置', 'CS') ?>
<?php
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－关于我们-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/aboutus.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top', 'company' => 'companysite')) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a  class="main_hover"href="/">首页</a>
            <span>&gt;</span>
            <a class="main">关于我们</a>
        </div>
        <div class="l_main conwidth clearfix">
            <div class="m_left fl">
                <h3>关于我们</h3>
                <ul>
                    <li><a  class="active_hover" href="/about.html?intro">企业介绍</a></li>
                    <li><a  class="active_hover" href="/about.html?culture">企业文化</a></li>
                    <li><a class="active_hover" href="/about.html?zizhi">企业资质</a></li>
                    <!--<li><a  class="active_hover">发展历程</a></li>-->
                    <li class="no_bb "><a class="active_hover" href="/about.html?connect">联系我们</a></li>
                </ul>
            </div>
            <div class="m_right fr">
                <!--//公司介绍-->
                <div class="m_intro hide">
                    <h3>企业介绍</h3>
                    <?php Qs::DsField('CS', 1)
                    ?>
                </div>
                <!--企业文化-->
                <div class="m_culture hide">
                    <h3>企业文化</h3>
                    <?php Qs::DsField('CS', 2)
                    ?>
                </div>
                <!--资质-->
                <div class="m_zizhi hide">
                    <h3>企业资质</h3>
                    <?php Qs::DsField('CS', 3)
                    ?>
                </div>

                <!--联系我们-->
                <div class="m_connect hide">
                    <h3>联系我们</h3>
                    <?php Qs::DsField('CS', 4)
                    ?>
                </div>
            </div>
        </div>
        <!--底部-->
        <?php Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <div class="online">
            <div class="online_ele  ">
                <a target="_blank" <?php echo strlen(Qs::DsField('CP', 'providerqq', true)) ? 'href="http://wpa.qq.com/msgrd?v=3&uin=' . Qs::DsField('CP', 'providerqq', true) . '&site=qq&menu=yes"' : ''; ?>>
                    <i class="icon-qq main"></i>
                    <p class="main">在线客服</p>
                    <span class="main_bg"></span>
                </a>
            </div>
        </div>
        <div id='totop'><a style="display: none"><i class='icon-jiantou1'></i></a><a class='shoucang'><i class='icon-empty-star'></i><em>关注</em></a><a><i class='icon-kefu'></i><em>客服</em>
                <div class='block'><span>电话：<?php Qs::DsField('CP', 'contact') ?></span></div></a></div>
                <?php Qs::Sys('loadRequireJs', 'company/aboutus') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>
        <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=BPWH0tb47EkNlH6fGGzh381M"></script>
    </body>
</html>
