<!DOCTYPE html>
<?php Qs::Ds('内容数据源/企业标准内容模型', 'AC') ?>
<?php
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－招聘信息-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/zhaopin.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--公司头部-->
        <div class="l_top ">
            <div class="conwidth clearfix">
                <div class="l_top_left">
                    <a href="">
                        <img src="<?php Qs::DsField('CP', 'logo') ?>" alt="">
                        <span><?php Qs::DsField('CP', 'name') ?></span>
                    </a>
                </div>
                <div class="l_top_right icon-erweima">
                    <div class="erweima_box">
                        <div class="qrcode" id="qrcode1" company="<?php Qs::DsField('CP', 'company') ?>" companyqq="<?php Qs::DsField('CP', 'providerqq') ?>" companyphone="<?php Qs::DsField('CP', 'contact') ?>">
                        </div>
                        <p>扫一扫，用手机查看</p>
                    </div>
                </div>
            </div>
        </div>
        <!--导航和搜索-->
        <div class="l_nav ">
            <div class="conwidth">
                <ul class="clearfix ">
                    <li class="mainbd_hover active_hover "><a href="/">首页</a></li>
                    <li class="mainbd_hover active_hover"><a href="/productlist/1.html">产品中心</a></li>
                    <li class="mainbd_hover active_hover">
                        <a href="/newscenter.html">新闻中心</a>
                        <div class="nav_box">
                            <ul>
                                <li class="active_hover"><a href="/companynews.html">公司新闻</a></li>
                                <li class="active_hover"><a href="/industrynews.html">行业新闻</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="mainbd_hover active_hover main_border main"><a href="/joinus.html">招聘中心</a></li>
                    <li class="mainbd_hover active_hover">
                        <a href="/about.html">关于我们</a>
                        <div class="nav_box">
                            <ul>
                                <li class="active_hover"><a href="/about.html">公司介绍</a></li>
                                <li class="active_hover"><a href="/about.html">公司资质</a></li>
                                <li class="active_hover"><a href="/about.html">公司文化</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
                <div class="search">
                    <input type="text">
                    <i class="icon-sousuo"></i>
                </div>
            </div>
        </div>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a class="main">招聘中心</a>
        </div>
        <div class="l_main conwidth clearfix">
            <!--左侧-->
            <div class="m_left fl">
                <div class="company_info">
                    <div class="company_name">
                        <h1><?php Qs::DsField('CP', 'name') ?></h1>
                        <p>
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi1.png') ?>" title="资质好" alt="资质好">
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi2.png') ?>" title="诚信商家" alt="诚信商家">
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi2.png') ?>" title="有良心商家" alt="有良心商家">
                        </p>
                    </div>
                    <div class="company_intro">
                        <dl>
                            <dt>经营模式</dt>
                            <dd><?php
                                $trade = array(1 => '销售型', '生产型', '设计型', '信息服务型', '销售+生产型', '销售+设计型', '生产+设计型', '销售+生产+设计型');
                                echo $trade[Qs::DsField('CP', 'tradeMode', true)]
                                ?></dd>
                        </dl>
                        <dl>
                            <dt>所在地区</dt>
                            <dd><?php echo ' ' . implode(' ', Qs::DsField('CP', 'PCD', true)) ?></dd>
                        </dl>
                        <dl>
                            <dt>联系人</dt>
                            <dd><?php Qs::DsField('CP', 'providername') ?></dd>
                        </dl>
                        <dl>
                            <dt>联系电话</dt>
                            <dd><?php Qs::DsField('CP', 'contact') ?></dd>
                        </dl>
                        <dl>
                            <dt>工作时间</dt>
                            <dd>
                                <p>周一到周五</p>
                                <p>(08:30-18:30)</p>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
            <!--右侧-->
            <div class="m_right fr">
                <h3>招聘中心</h3>
                <div class="zhaopin_ele">
                    <h4><?php Qs::DsField('AC', 'title') ?></h4><br>
                    <p class="clearfix">
                        <span class="zhaopin_intro">任职部门：</span>
                        <span class="zhaopin_detail"><?php Qs::DsField('AC', 'department') ?></span>
                    </p>
                    <p class="clearfix">
                        <span class="zhaopin_intro">招聘人数：</span>
                        <span class="zhaopin_detail"><?php Qs::DsField('AC', 'number') ?></span>
                    </p>
                    <p class="clearfix">
                        <span class="zhaopin_intro">联系电话：</span>
                        <span class="zhaopin_detail"><?php Qs::DsField('AC', 'tel') ?></span>
                    </p>
                    <p class="clearfix">
                        <span class="zhaopin_intro">截止时间：</span>
                        <span class="zhaopin_detail"><?php echo date('Y-m-d', QS::DsField('AC', 'endTime', true)) ?></span>
                    </p><br>
                    <p class="clearfix">
                        <?php Qs::DsField('AC', 'content') ?>
                    </p><br>
                    <div class="prev_next">
                        <p><em>上一条：</em><?php
                            $prev = Qs::DsField('AC', 'prev', true);
                            if ($prev) {
                               echo '<a href="' . $prev[0] . '">' . iconv_substr($prev[1], 0, 18) . '</a>';
                            } else {
                               echo '木有了';
                            }
                            ?>
                        </p>
                        <p><em>下一条：</em><?php
                            $next = Qs::DsField('AC', 'next', true);
                            if ($next) {
                               echo '<a href="' . $next[0] . '">' . iconv_substr($next[1], 0, 18) . '</a>';
                            } else {
                               echo '正在更新中，请等待~';
                            }
                            ?></p>
                    </div>
                </div>

            </div>
        </div>
        <!--底部-->
        <?php Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <?php Qs::Sys('loadRequireJs', 'company/common') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>
    </body>
</html>