<!DOCTYPE html>
<?php Qs::Ds('内容数据源/企业信息', 'CP') ?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－招聘信息</title>
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/zhaopinlist.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a class="main">招聘中心</a>
        </div>
        <div class="l_main conwidth clearfix">
            <!--左侧-->
            <div class="m_left fl">
                <div class="company_info">
                    <div class="company_name">
                        <h1><?php Qs::DsField('CP', 'name') ?></h1>
                        <p>
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi1.png') ?>" title="资质好" alt="资质好">
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi2.png') ?>" title="诚信商家" alt="诚信商家">
                            <img src="<?php Qs::Sys('loadImage', 'company/test_icon_zizhi2.png') ?>" title="有良心商家" alt="有良心商家">
                        </p>
                    </div>
                    <div class="company_intro">
                        <dl>
                            <dt>经营模式</dt>
                            <dd><?php
                                $trade = array(1 => '销售型', '生产型', '设计型', '信息服务型', '销售+生产型', '销售+设计型', '生产+设计型', '销售+生产+设计型');
                                echo $trade[Qs::DsField('CP', 'tradeMode', true)]
                                ?></dd>
                        </dl>
                        <dl>
                            <dt>所在地区</dt>
                            <dd><?php echo ' ' . implode(' ', Qs::DsField('CP', 'PCD', true)) ?></dd>
                        </dl>
                        <dl>
                            <dt>联系人</dt>
                            <dd><?php Qs::DsField('CP', 'providername') ?></dd>
                        </dl>
                        <dl>
                            <dt>联系电话</dt>
                            <dd><?php Qs::DsField('CP', 'contact') ?></dd>
                        </dl>
                        <dl>
                            <dt>工作时间</dt>
                            <dd>
                                <p>周一到周五</p>
                                <p>(08:30-18:30)</p>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
            <!--右侧-->
            <div class="m_right fr">
                <?php
                Qs::Label('企业网站/文章', array('renderTpl' => 'Pc_ZhaoPin', 'nodeIdentifier' => array('joinus'), 'titleLength' => 34, 'introLength' => 20, 'outputNum' => 5, 'enablePage' => true, 'listSubNode' => true))
                ?>
            </div>
        </div>
        <!--底部-->
        <?php Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <?php Qs::Sys('loadRequireJs', 'company/common') ?>
    </body>
</html>