<!DOCTYPE html>
<?php Qs::Ds('内容数据源/企业信息', 'CP') ?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－新闻动态</title>
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/newsdetail.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'LaoBan',)) ?>
        <!--公司头部-->
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a class="main">新闻中心</a>
        </div>
        <div class="l_main conwidth clearfix">
            <!--左侧-->
            <div class="m_left fl">
                <h3>新闻中心</h3>
                <ul>
                    <li><a class="active_hover main">行业新闻</a></li>
                    <li class="no_bb"><a class="active_hover">企业新闻</a></li>
                </ul>
            </div>
            <!--右侧-->
            <div class="m_right fr">
                <h3>卡萨帝灵珑传奇热水器</h3>
                <p><span>发表时间：2015-11-17</span><span>作者：smm </span> <span >浏览：1111</span></p>
                <div class="news_detail">
                    <p>
                        作为当前治国方针政策中最重要的一环，信息安全已经成为国家安全的重要战略组成部分。在这方面，国人已经经历了长久的努力和实践——掌握自主知识产权的核心技术和产品已经成为当前国家信息安全
                    </p>
                    <p>领域最为迫切的需求，而目前国产化芯片和操作系统作为最重要战略布局得到了国家的大力扶持。</p>
                    <img src="../../Images/test/test_banner1.jpg" alt="">
                    <p> 深度科技研发的桌面操作系统就可以很好地满足使用者的需求——不仅在界面体验上无需改变用户长期以来的使用习惯，更是兼容市面上主流的Windows应用程序。安全性方面，因为可以由管理员设置权限进行统一管理，员工无法自己随意安装、卸载软件，使企业系统安全性更高，进而提升信息保密程度。对于特殊行业，
                        以及企业而言，深度科技自主研发的操作系统因为其易用性及安全性，有着得天独厚的优势。</p>
                </div>
            </div>
        </div>
        <!--底部-->
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <?php Qs::Sys('loadRequireJs', 'company/common') ?>
    </body>
</html>
