<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业标准内容模型', 'AC');
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/newsdetail.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--公司头部-->
        <div class="l_top ">
            <div class="conwidth clearfix">
                <div class="l_top_left">
                    <a href="">
                        <img src="<?php Qs::DsField('CP', 'logo') ?>" alt="">
                        <span><?php Qs::DsField('CP', 'name') ?></span>
                    </a>
                </div>
                <div class="l_top_right icon-erweima">
                    <div class="erweima_box">
                        <div class="qrcode" id="qrcode1" company="<?php Qs::DsField('CP', 'company') ?>" companyqq="<?php Qs::DsField('CP', 'providerqq') ?>" companyphone="<?php Qs::DsField('CP', 'contact') ?>">
                        </div>
                        <p>扫一扫，用手机查看</p>
                    </div>
                </div>
            </div>
        </div>
        <!--导航和搜索-->
        <div class="l_nav ">
            <div class="conwidth">
                <ul class="clearfix ">
                    <li class="mainbd_hover active_hover "><a href="/">首页</a></li>
                    <li class="mainbd_hover active_hover"><a href="/productlist/1.html">产品中心</a></li>
                    <li class="mainbd_hover active_hover main_border main">
                        <a href="/newscenter.html">新闻中心</a>
                        <div class="nav_box">
                            <ul>
                                <li class="active_hover"><a href="/companynews.html">公司新闻</a></li>
                                <li class="active_hover"><a href="/industrynews.html">行业新闻</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="mainbd_hover active_hover"><a href="/joinus.html">招聘中心</a></li>
                    <li class="mainbd_hover active_hover">
                        <a href="/about.html">关于我们</a>
                        <div class="nav_box">
                            <ul>
                                <li class="active_hover"><a href="/about.html">公司介绍</a></li>
                                <li class="active_hover"><a href="/about.html">公司资质</a></li>
                                <li class="active_hover"><a href="/about.html">公司文化</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
                <div class="search">
                    <input type="text">
                    <i class="icon-sousuo"></i>
                </div>
            </div>
        </div>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a class="main">新闻中心</a>
        </div>
        <div class="l_main conwidth clearfix">
            <!--左侧-->
            <div class="m_left fl">
                <h3>新闻中心</h3>
                <ul>
                    <?php Qs::Label('企业网站/文章', array('renderTpl' => 'Pc_NewNav',)) ?> 
                </ul>
            </div>
            <!--右侧-->
            <div class="m_right fr">
                <h3><?php Qs::DsField('AC', 'title') ?></h3>
                <p><span>发表时间：<?php echo date('Y-m-d', QS::DsField('AC', 'inputTime', true)) ?></span>
                    <span >浏览：<?php Qs::DsField('AC', 'hits') ?></span></p>
                <div class="news_detail" style="min-height: 600px">
                    <?php Qs::DsField('AC', 'content') ?>
                </div>
                <div class="up_down">
                    <div>
                        上一篇：<?php
                        $prev = Qs:: DsField('AC', 'prev', true);
                        if ($prev) {
                           $pretitle = mb_substr($prev [1], 0, 18);
                           echo '<a href="' . $prev[0] . '">' . $pretitle . '</a>';
                        } else {
                           echo '木有了';
                        }
                        ?>
                    </div>
                    <div>
                        下一篇：  <?php
                        $next = Qs::DsField('AC', 'next', true);
                        if ($next) {
                           $nexttitle = mb_substr($next[1], 0, 18);
                           echo '<a href="' . $next[0] . '">' . $nexttitle . '</a>';
                        } else {
                           echo '正在更新中，请等待~';
                        }
                        ?>
                    </div>
                </div>
            </div>           
        </div>
        <!--底部-->
        <?php Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <div class="online">
            <div class="online_ele  ">
                <a target="_blank" <?php echo strlen(Qs::DsField('CP', 'providerqq', true)) ? 'href="http://wpa.qq.com/msgrd?v=3&uin=' . Qs::DsField('CP', 'providerqq', true) . '&site=qq&menu=yes"' : ''; ?>>
                    <i class="icon-qq main"></i>
                    <p class="main">在线客服</p>
                    <span class="main_bg"></span>
                </a>
            </div>
        </div>
        <div id='totop'><a style="display: none"><i class='icon-jiantou1'></i></a><a class='shoucang'><i class='icon-empty-star'></i><em>关注</em></a><a><i class='icon-kefu'></i><em>客服</em>
                <div class='block'><span>电话：<?php Qs ::DsField('CP', 'contact') ?></span></div></a></div>
                <?php Qs::Sys('loadRequireJs', 'company/common') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>
    </body>
</html>
