<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－新闻动态-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/newslist.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top', 'company' => 'companysite')) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a class="main_hover" href="/">首页</a>
            <span>&gt;</span>
            <a class="main">新闻中心</a>
        </div>
        <div class="l_main conwidth clearfix">
            <!--左侧-->
            <div class="m_left fl">
                <h3>新闻中心</h3>
                <ul>
                    <?php Qs::Label('企业网站/文章', array('renderTpl' => 'Pc_NewNav',)) ?>                    
                </ul>
            </div>
            <!--新闻列表-->
            <div class="m_right fr">
                <?php
                Qs::Label('企业网站/文章', array('renderTpl' => 'Pc_DefaultList', 'nodeIdentifier' => array(), 'titleLength' => 34, 'introLength' => 20, 'outputNum' => 5, 'enablePage' => true, 'listSubNode' => true))
                ?>
            </div>
        </div>
        <div id='totop'><a style="display: none"><i class='icon-jiantou1'></i></a><a><i class='icon-kefu'></i><em>客服</em>
                <div class='block'><span>电话：<?php Qs::DsField('CP', 'contact') ?></span></div></a></div>
        <!--底部-->
        <!--底部-->
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',));
        Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyRight',))
        ?>
        <?php Qs::Sys('loadRequireJs', 'company/common') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>
    </body>
</html>