<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/店铺设置', 'setting');
Qs::Ds('内容数据源/企业案例模型', 'case');
Qs::Ds('内容数据源/企业信息', 'CP');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('case', 'title'); ?>-<?php Qs::DsField('CP', 'name') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'slick.css', 'company/case_detail.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top', 'company' => 'companysite')) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <!--路由-->
        <!--站点指示-->
        <div class="site conwidth">
            <a class="main_hover" href="/">首页</a>
            <span>&gt;</span>
            <a class="main"><?php Qs::DsField('case', 'title'); ?></a>
        </div>
        <div class="l_main conwidth" newsid="<?php Qs::DsField('case', 'id') ?>">
            <div class="detail_left ">
                <div class="container">
                    <div class="slick">
                        <?php
                        $content = Qs::DsField('case', 'content', true);
                        foreach ($content as $value) {
                           echo '<div class="big_img">
									 <div>
										  <img src="' . $value['src'] . '">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>';
                        }
                        ?>
                    </div>
                    <div class="big_left big_com">
                        <div class="big_margin left_com"></div>
                    </div>
                    <div class="big_right big_com">
                        <div class="big_margin right_com"></div>
                    </div>
                </div>
                <div class="slick_bg">
                    <div class="slick_nav">
                        <?php
                        foreach ($content as $index => $value) {
                           if ($index) {
                              echo '<div class="small_img">
									 <img  src="' . $value['src'] . '">
									 <div class="count"></div>
								</div>';
                           } else {
                              echo '<div class="small_img">
									 <img class="border_green" src="' . $value['src'] . '">
									 <div class="count"></div>
								</div>';
                           }
                        }
                        ?>
                    </div>
                    <div class="prev_pic prev_next_com">
                        <?php
                        $prev = Qs::DsField('case', 'prev', true);
                        if ($prev) {
                           echo '<img src="' . (isset($prev[2]) ? Cntysoft\Kernel\get_image_cdn_url($prev[2], 124, 79) : 'http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png' ) . '">
								<a href="' . $prev[0] . '"><span>上一图册</span></a>';
                        } else {
                           echo '<img src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png">
								<a><span>没有了</span></a>';
                        }
                        ?>
                    </div>
                    <div class="next_pic prev_next_com">
                        <?php
                        $next = Qs::DsField('case', 'next', true);
                        if ($next) {
                           echo '<img src="' . (isset($next[2]) ? Cntysoft\Kernel\get_image_cdn_url($next[2], 124, 79) : 'http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png') . '">
								<a href="' . $next[0] . '"><span>下一图册</span></a>';
                        } else {
                           echo '<img src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png">
								<a><span>没有了</span></a>';
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <!--底部-->
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',));
        Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyRight',))
        ?>
        <?php Qs::Sys('loadRequireJs', 'company/case_detail') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>
    </body>
</html>
