<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
	 <head>
		  <meta charset="UTF-8">
		  <title>case_detail</title>
		  <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
		  <?php Qs::Sys('loadCss', array('company/style.css', 'slick.css', 'company/case_detail.css')) ?>
	 </head>
	 <body>
		  <!--头部-->
		  <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--公司头部-->
		  <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
		  <!--路由-->
		  <!--站点指示-->
		  <div class="site conwidth">
				<a href="/">首页</a>
				<span>&gt;</span>
				<a class="main">案例详情</a>
		  </div>
		  <div class="l_main conwidth">
				<div class="detail_left ">
					 <div class="container">
						  <div class="slick">
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test/test_xgt_detail2.jpg">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_banner.jpg">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_detail3.png">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_detail4.png">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_detail2.jpg">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_detail3.png">
										  <div class="store clearfix">
												<span class="store_img"></span>

										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_detail2.jpg">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_banner.jpg">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_detail3.png">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
								<div class="big_img">
									 <div>
										  <img src="../../Images/company/test//test_xgt_detail3.png">
										  <div class="store clearfix">
												<span class="store_img"></span>
										  </div>
									 </div>
								</div>
						  </div>
						  <div class="big_left big_com">
								<div class="big_margin left_com"></div>
						  </div>
						  <div class="big_right big_com">
								<div class="big_margin right_com"></div>
						  </div>
					 </div>
					 <div class="slick_bg">
						  <div class="slick_nav">
								<div class="small_img">
									 <img class="border_green" src="../../Images/company/test//test_xgt_detail2.jpg">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_banner.jpg">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_detail3.png">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_detail4.png">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_detail2.jpg">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_detail3.png">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_detail2.jpg">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_banner.jpg">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_detail3.png">
									 <div class="count"></div>
								</div>
								<div class="small_img">
									 <img src="../../Images/company/test//test_xgt_detail3.png">
									 <div class="count"></div>
								</div>
						  </div>
						  <div class="small_left">
								<div class="small_margin left_com"></div>
						  </div>
						  <div class="small_right">
								<div class="small_margin right_com"></div>
						  </div>
						  <div class="prev_pic prev_next_com">
								<img src="../../Images/company/test//test_xgt_detail4.png">
								<a href=""><span>上一图册</span></a>
						  </div>
						  <div class="next_pic prev_next_com">
								<img src="../../Images/company/test//test_xgt_detail3.png">
								<a href=""><span>下一图册</span></a>
						  </div>
					 </div>
				</div>
		  </div>
		  <!--底部-->
		  <?php Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <!--侧边栏-->
        <div class="online">
            <div class="online_ele  ">
                <a target="_blank" <?php echo strlen(Qs::DsField('CP', 'providerqq', true)) ? 'href="http://wpa.qq.com/msgrd?v=3&uin=' . Qs::DsField('CP', 'providerqq', true) . '&site=qq&menu=yes"' : ''; ?>>
                    <i class="icon-qq main"></i>
                    <p class="main">在线客服</p>
                    <span class="main_bg"></span>
                </a>
            </div>
        </div>
        <div id='totop'><a style="display: none"><i class='icon-jiantou1'></i></a><a class='shoucang'><i class='icon-empty-star'></i><em>关注</em></a><a><i class='icon-kefu'></i><em>客服</em>
                <div class='block'><span>电话：<?php Qs::DsField('CP', 'contact') ?></span></div></a></div>
					 <?php Qs::Sys('loadRequireJs', 'company/case_detail') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>
	 </body>
</html>
