<!DOCTYPE html>
<?php
use App\Yunzhan\Content\Constant;
Qs::Ds('内容数据源/企业标准内容模型', 'CS', array('newsid' => Constant::INFO_INTRO_ID));
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－首页-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'slick.css', 'company/companyindex.css')) ?>
    </head>

    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--公司头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Pc_CompanyTop',)) ?>
        <div class="l_main conwidth">
            <!--banner-->
            <div class="banner">
                <?php
                $banners = QS::DsField('setting', 'banner', true);
                if (count($banners) == 0) {
                   ?>
                   <div><a ><img src="<?php Qs::Sys('loadImage', 'company/test_company_banner.jpg') ?>" alt="<?php Qs::DsField('CP', 'name') ?>"></a></div>
                   <?php
                }
                foreach ($banners as $banner) {
                   $image = $banner['image'];
                   $url = $banner['url'];
                   if ($url) {
                      echo '<div><a href="' . $url . '" target="_blank"><img src="' . $image . '" alt=""></a></div>';
                   } else {
                      echo '<div><a><img src="' . $image . '" alt=""></a></div>';
                   }
                }
                ?>
            </div>
            <!--新闻和企业文化-->
            <div class="company_info clearfix">
                <div class="l_news fl">
                    <h3>新闻动态 <a href="/newscenter.html" class="active_hover">更多 >></a></h3>
                    <div class="clearfix">
                        <?php
                        Qs::Label('企业网站/文章', array('renderTpl' => 'Pc_IndexNewList', 'nodeIdentifier' => array('newscenter', 'companynews', 'industrynews'), 'titleLength' => 17, 'introLength' => 20, 'outputNum' => 4, 'enablePage' => false, 'listSubNode' => true))
                        ?>
                    </div>
                </div>
                <div class="l_intro fr">
                    <h3>企业介绍 <a href="/about.html" class="active_hover">更多 >></a></h3>
                    <?php
                    $inrodata = Qs::DsField('CS', 'content', true);
                    if (iconv_strpos($inrodata, '<img')) {
                       $imgs = mb_split('data-original="', $inrodata);
                       echo'<a href="/about.html"> <img src="' . mb_split('"', $imgs[1])[0] . '" alt=""></a>';
                    }
                    ?>
                    <p>
                        <?php
                        echo iconv_substr(strip_tags($inrodata), 0, 92, 'UTF-8')
                        ?>
                        <a href="/about.html" class="main" style="float: right">查看详情 >></a></p>
                </div>
            </div>
            <!--产品展示-->
            <div class="l_pro">
                <h3>产品展示 <a href="/productlist/1.html" class="active_hover">查看更多 >></a>
                    <!--<span class="prev_page"><i></i></span><span class="next_page"><i></i></span>-->
                </h3>
                <div class="pro_box clearfix">
                    <?php Qs::Label('企业网站/产品', array('renderTpl' => 'Pc_IndexProductList', 'outputNum' => 8, 'enablePage' => false)); ?>
                </div>
            </div>
        </div>
        <!--底部-->
        <?php Qs::Label('云站/网站底部', array('renderTpl' => 'Pc_CompanyBottom',)) ?>
        <!--侧边栏-->
        <div class="online">
            <div class="online_ele  ">
                <a target="_blank" <?php echo strlen(Qs::DsField('CP', 'providerqq', true)) ? 'href="http://wpa.qq.com/msgrd?v=3&uin=' . Qs::DsField('CP', 'providerqq', true) . '&site=qq&menu=yes"' : ''; ?>>
                    <i class="icon-qq main"></i>
                    <p class="main">在线客服</p>
                    <span class="main_bg"></span>
                </a>
            </div>
        </div>
        <div id='totop'><a style="display: none"><i class='icon-jiantou1'></i></a><a class='shoucang'><i class='icon-empty-star'></i><em>关注</em></a><a><i class='icon-kefu'></i><em>客服</em>
                <div class='block'><span>电话：<?php Qs::DsField('CP', 'contact') ?></span></div></a></div>
                <?php Qs::Sys('loadRequireJs', 'company/company_index') ?>
        <script>
           window.BUYER_SITE_NAME = '<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>';
        </script>

    </body>
</html>
