<div class="nav main_border">
    <div class="conwidth clearfix">
        <div class="all_sort fl">
            <span class="main_bg all_btn"><i class="icon-fenlei"></i>所有商品分类</span>

            <div class="sort_list">
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-jiancaizhuangxiu"></i>家装建材</h4>

                        <p>
                            <a href="../mall/prolist.html">欧式高景观型</a><a href="../mall/prolist.html">多功能坐躺型</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>婴儿推车</i></span>

                            <div class="fl main_hover">
                                <a href="">欧式高景观型</a>
                                <a href="">多功能坐躺型</a>
                                <a href="">超宽舒适型</a>
                                <a href="">超轻便折叠型</a>
                                <a href="">运动型推车</a>
                                <a href="">双人推车</a>
                                <a href="">豪华定制型</a>
                                <a href="">推车配件</a>
                                <a href="">新 品</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-diangongdianqi"></i>电工电气 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a>
                            <a href="">睡袋/抱被</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>婴儿推车</i></span>

                            <div class="fl main_hover">
                                <a href="">欧式高景观型</a>
                                <a href="">多功能坐躺型</a>
                                <a href="">超宽舒适型</a>
                                <a href="">超轻便折叠型</a>
                                <a href="">运动型推车</a>
                                <a href="">双人推车</a>
                                <a href="">豪华定制型</a>
                                <a href="">推车配件</a>
                                <a href="">新 品</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>婴儿推车</i></span>

                            <div class="fl main_hover">
                                <a href="">欧式高景观型</a>
                                <a href="">多功能坐躺型</a>
                                <a href="">超宽舒适型</a>
                                <a href="">超轻便折叠型</a>
                                <a href="">运动型推车</a>
                                <a href="">双人推车</a>
                                <a href="">豪华定制型</a>
                                <a href="">推车配件</a>
                                <a href="">新 品</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-dianziyuanqijian"></i>电子元件 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a>
                            <a href="">睡袋/抱被</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>婴儿推车</i></span>

                            <div class="fl main_hover">
                                <a href="">欧式高景观型</a>
                                <a href="">多功能坐躺型</a>
                                <a href="">超宽舒适型</a>
                                <a href="">超轻便折叠型</a>
                                <a href="">运动型推车</a>
                                <a href="">双人推车</a>
                                <a href="">豪华定制型</a>
                                <a href="">推车配件</a>
                                <a href="">新 品</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-anquanfanghu"></i>安全防护 </h4>

                        <p>
                            <a href="">床垫</a><a href="">睡袋/抱被</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>婴儿推车</i></span>

                            <div class="fl main_hover">
                                <a href="">欧式高景观型</a>
                                <a href="">多功能坐躺型</a>
                                <a href="">超宽舒适型</a>
                                <a href="">超轻便折叠型</a>
                                <a href="">运动型推车</a>
                                <a href="">双人推车</a>
                                <a href="">豪华定制型</a>
                                <a href="">推车配件</a>
                                <a href="">新 品</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-dashboard24"></i>仪器仪表 </h4>

                        <p>
                            <a href="">床垫</a>
                            <a href="">睡袋/抱被</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-yejinkuangchan-copy"></i>冶金矿石 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a>
                            <a href="">睡袋/抱被</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-dengjuzhaoming"></i>照明工业 </h4>

                        <p>
                            <a href="">床上用品</a>
                            <a href="">睡袋</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-wujingongju"></i>五金工具 </h4>

                        <p>
                            <a href="">床上用品</a><a href="">床垫</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sort_ele">
                    <div class="sort_container">
                        <h4><i class="icon-biaozhunjianmro"></i>标准件 </h4>

                        <p>
                            <a href="">床垫</a>
                            <a href="">睡袋/抱被</a><a href="">毛毯礼盒</a>
                        </p>
                    </div>
                    <div class="sort_detail ">
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                        <div class="c_sort_detail clearfix">
                            <span class="sort_intro"><i>安全座椅</i></span>

                            <div class="fl main_hover">
                                <a href="">0-15个月</a>
                                <a href="">0-4岁</a>
                                <a href="">0-7岁</a>
                                <a href="">9个月-7岁</a>
                                <a href="">9个月-12岁</a>
                                <a href="">ISOFIX</a>
                                <a href="">安全带固定</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <span class="all_sort_bg main_bg"></span>
        </div>
        <ul class="fl nav_list">
            <li><a href="../mall/index.html" class="main_hover">首页</a></li>
            <li><a href="../mall/prolist.html" class="main_hover">活动</a></li>
            <li><a href="../mall/prolist.html" class="main_hover">建材老板内参</a></li>
            <li><a href="../mall/prolist.html" class="main_hover">企业库</a></li>
        </ul>
    </div>
</div>