<?php
$result = $this->getQuotationList();
$list = $result['item'];
$total = $result['total'];
$out = '';

if(count($list)){
   foreach($list as $inquiry){
      $buyer = $inquiry->getBuyer();
      $offer = $inquiry->getOffer();
      $product = $inquiry->getProduct();
      $time = date('Y年m月d日 H:i:s', $inquiry->getInputTime());
      $url = $this->getProductUrl($product->getNumber());
      $name = $product->getBrand(). ' ' . $product->getTitle() . ' ' . $product->getDescription();
      $quotationUrl = $this->getQuotationUrl($inquiry->getId());
      
      $out.='<div class="baojia_ele">
            <h3>'.$time.' </h3>
            <div class="baojia_grid clearfix">
                <div class="baojia_pro">
                    <div>
                        <h4>采购产品：</h4>
                        <a href="'.$url.'" target="__blank"><p class="main_light">'.$name.'</p></a>
                    </div>
                </div>
                <div class="baojia_source">
                    <div>
                        <p>
                            报价单来源：产品咨询
                        </p>
                    </div>
                </div>
                <div class="baojia_count">
                    <div>
                        <p>
                            '. ($offer ? 1 : 0).'条报价
                        </p>
                    </div>
                </div>
                <div class="baojia_operation">
                    <div>
                        <span>'.($offer ? "报价已结束" : "报价进行中").'</span>
                        <a href="'.$quotationUrl.'" target="__blank"> <span class="main_bg_light">查看报价单</span></a>
                    </div>
                </div>
            </div>
        </div>';
   }
}

$paging = $this->getPaging($total);
if($this->getParam('enablePage') && count($list) && $paging['total'] > 0){
   $out1 = '';
   $currentPage = $paging['current'];
   $cls = "";
   $out .= '<div class="page_list"><p>';
   if ($currentPage > 1) {
      $out.='<a href="'. $this->getPageUrl($currentPage - 1).'" class="prev_page">&lt; 上一页</a>';
   }else{
      $out.='<a class="prev_page">&lt; 上一页</a>';
   }
   if ($currentPage > 5) {
      $out.='<a href="'. $this->getPageUrl(1).'">1</a>... ';
      for ($i = ($currentPage - 2); $i <= $paging['total'] && $i <= $currentPage + 2; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a  class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
   } else {
      for ($i = 1; $i <= $paging['total'] && $i <= 6; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
      if ($paging['total'] > 6) {
         $out1 .='... ' . '<a href="'. $this->getPageUrl(7).'">7</a>';
      }
   }
   $out .= $out1;
   if ($paging['total'] > 0 && $currentPage != $paging['total']) {
      $out .= '<a href="'. $this->getPageUrl($currentPage + 1).'" class="next_page no_marginR" >下一页 &gt;</a>';
   }else{
      $out .= '<a class="next_page no_marginR" >下一页 &gt;</a>';
   }

   $out .= '</p></div>';
}

echo $out;