<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>404-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('mall/style.css', 'mall/404.css', 'swiper.min.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <span class="icon_logo">
                    <a href="<?php echo 'http://' . Cntysoft\RT_SYS_SITE_NAME ?>">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </a>
                </span>
            </div>
            <!--搜索框-->
            <div class="header_title">
                <div class="search_input_box">
                    <i class="icon-sousuo"></i>
                    <input class="search_input" type="text" required placeholder="搜索产品"/>
                </div>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
        </div>
        <!--导航-->
        <div class="top_nav_box hide">
            <ul class="top_nav_list clearfix">
                <li><a href="<?php echo 'http://' . Cntysoft\RT_SYS_SITE_NAME ?>">首页</a></li>
                <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/classifylist.html">全部分类</a></li>
                <!--<li><a href="/">产品搜索</a></li>-->
                <!--<li><a href="/">企业搜索</a></li>-->
                <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/help.html">帮助中心</a></li>
                <li><a href="<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>">个人中心</a></li>
                <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/laobanneican.html">老板内参</a></li>
            </ul>
        </div>
        <!--内容-->
        <div class="content">
            <div class="content_text">
                <p>抱歉！您所要访问的页面不存在。</p>
                <p>
                    <a href="javascript:history.go(-1)">返回上一页</a>
                    <a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME; ?>">返回首页</a>
                </p>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'mall/404'); ?>
    </body>
</html>