<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>首页-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('mall/style.css', 'mall/index.css', 'swiper.min.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <span class="icon_logo">
                    <img src="/Statics/Skins/Mobile/Images/icon/icon_logo.png" alt="logo"/>
                </span>
            </div>
            <!--搜索框-->
            <div class="header_title">
                <div class="search_input_box">
                    <i class="icon-sousuo"></i>
                    <input id="search_input" class="search_input" type="text" required placeholder="搜索产品"/>
                </div>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--导航-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="/">首页</a></li>
                    <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/zhuchaoschool.html">筑巢商学院</a></li>
                    <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/laobanneican.html">老板内参</a></li>
                    <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/help.html">帮助中心</a></li>
                    <!--<li><a href="http://<\?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/about/company.html">关于我们</a></li>-->
                    <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/zhuchaogonggao/1.html">筑巢公告</a></li>
                </ul>
            </div>
        </div>
        <div class="search_box">
            <div class="headbar">
                <!--取消-->
                <div class="header_back_box fl">
                    <a class="header_back"><i class="icon-cuowu"></i></a>
                </div>
                <!--更多按钮-->
                <div class="header_right header_right_icon_search fr">
                    <span class="search_icon"><i class="icon-sousuo"></i></span>
                </div>
                <!--搜索框-->
                <div class="header_title">
                    <div class="search_input_box">
                        <input class="search_input_real search_input" type="text" required placeholder="搜索产品"/>
                    </div>
                </div>
            </div>
            <div class="search_hot">
                <h3>大家都在搜</h3>
                <ul class="search_hot_key" style="padding-top:12px;">
                    <li>壁纸</li>
                    <li>木床</li>
                    <li>橱柜</li>
                    <li>马桶</li>
                    <li>台灯</li>
                    <li>枕头</li>
                    <li>开关</li>
                    <li>衣柜</li>
                    <li>窗帘</li>
                    <li>餐桌</li>
                    <li>定制衣柜</li>
                    <li>浴缸</li>
                </ul>
            </div>
        </div>
        <!--一列广告滑动-->
        <?php Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_Index')) ?>
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
        <?php Qs::Sys('loadRequireJs', 'mall/index'); ?>
    </body>
</html>
