<div class="head_wrap main_bg_light">
    <div class="head_box conwidth clearfix">
        <a class="logo_img fl" href="<?php echo 'http://' .Cntysoft\SYS_SITE_NAME_DEVEL;?>"><img src="<?php Qs::Sys('loadImage','mall/icon/icon_logo_white.png')?>"> </a>
        <span class="fl">会员中心</span>
        <div class="search fr">
            <input type="text" placeholder="请输入关键字" class="search_key">
            <span class="search_btn">搜索</span>
        </div>
    </div>
</div>