<?php $config = $this->getSiteUrl(); ?>
<!--logo，搜索,名称-->
<div class="headbar  clearfix main_bg">
    <!--logo-->
    <div class="header_left fl">
        <a href="javascript:history.back()">
            <span class="icon-fanhuijian"></span>
        </a>
    </div>
    <!--搜索框-->
    <div class="header_title">
        <div class="search_input_box">
            会员中心
        </div>
    </div>
    <!--更多按钮-->
    <div class="header_right fr">
        <span class="more_icon"><i class="icon-xiala"></i></span>
    </div>
    <!--导航-->
    <div class="top_nav_box hide">
        <ul class="top_nav_list">
            <li><a href="<?php echo $config['SiteUrl']; ?>">首页</a></li>
            <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/classifylist.html">全部分类</a></li>
            <!--<li><a href="/">产品搜索</a></li>-->
            <!--<li><a href="/">企业搜索</a></li>-->
            <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/help.html">帮助中心</a></li>
            <li><a href="<?php echo 'http://' . \Cntysoft\RT_BUYER_SITE_NAME; ?>">个人中心</a></li>
            <li><a href="http://<?php echo \Cntysoft\RT_SYS_SITE_NAME ?>/category/laobanneican.html">老板内参</a></li>
        </ul>
    </div>
</div>
