<?php
$goodsInfo = $this->getProductByNumber();
$goodsDetail = $goodsInfo->getDetail();
$goodStatus = $goodsInfo->getStatus();
$name = ($goodsInfo->getBrand() . $goodsInfo->getTitle() . $goodsInfo->getDescription());
$out = '<div class="module_ad3 module_ad clearfix  swiper-container" num="' . $goodsInfo->getNumber() . '">
    <div class="swiper-wrapper">';
$images = $goodsDetail->getImages();
$i = 1;
foreach ($images as $image) {
   $out .= '<div class="module_ad_list swiper-slide">
            <a>
                <div class="module_ad_img"
                     style="background: url(' . $this->getImgUrl($image[0], 386, 385) . ') no-repeat center  ;">
                    <div class="module_ad_box"></div>
                </div>
            </a>
        </div>';
}
$out .= '</div>
    <div class="swiper-pagination"></div>
</div>';
$out.='<div class="pro_info_box">
    <p class="pro_price main">' . ($goodsInfo->getPrice() > 0 ? '￥ ' . $goodsInfo->getPrice() : "面议") . '</p>
    <p class="pro_num">产品编号：' . $goodsInfo->getNumber() . '</p>
    <h3 class="pro_title">' . $name . '</h3>
    <p class="pro_text">
        ' . $goodsDetail->getAdvertText() . '
    </p>
</div><div class="pro_detail_box">
    <!--导航-->
    <ul class="module_nav_bar">
        <li class="current"><span>产品信息</span></li>
        <li><span>规格属性</span></li>
    </ul>
    <div class="pro_content">
        ' . $goodsDetail->getIntroduction() . '
    </div>
    <div class="pro_content hide">
        <ul class="pro_content_inner">';
$attribute = $goodsDetail->getAttribute();
foreach ($attribute as $key => $value) {
   if (count($value)) {
      foreach ($value as $attrs => $attr) {
         $out .= '<li class="item">
                <div class="key">' . $attrs . '：</div>
                <div class="val">' . $attr . '</div>
            </li>';
      }
   }
}
$out.='</ul>
    </div>
</div>';
echo $out;
?>
