<?php
$out = '';
$goodsLists = $this->getProductList();
if (count($goodsLists) == 0) {
   echo $out;
   return;
}
foreach ($goodsLists as $goods) {
   $defpic = $goods->getDefaultImage();
   $price0 = $goods->getPrice();
   $infourl = $this->getInfoUrl($goods->getNumber());
   $price = $price0 > 0 ? '¥' . $price0 : '面议';
   $out .= '<div class="pro_list">
    <a href="' . $infourl . '" class="pro_list_a">
        <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImgUrl($defpic, 384, 241) . '" alt=""/>
        <h3>' . $goods->getBrand() . ' ' . $goods->getTitle() . ' ' . $goods->getDescription() . '</h3>
        <p>产品编号：' . $goods->getNumber() . '</p>
        <div class="price_btn main">' . $price . '</div>
    </a>
</div>';
}

echo $out;
