<?php
$out = '<div class="pro_list_box">';
$goodsLists = $this->getProductList();
foreach ($goodsLists as $goods) {
   $infourl = $this->getInfoUrl($goods->getNumber());
   $defpic = $goods->getDefaultImage();
   $price0 = $goods->getPrice();
   $price = $price0 > 0 ? '¥' . $price0 : '面议';
   $out .= '<div class="pro_list">
        <a href="' . $infourl . '" class="pro_list_a">
            <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImgUrl($defpic, 384, 240) . '" alt="">
            <h3>' . $goods->getBrand() . ' ' . $goods->getTitle() . ' ' . $goods->getDescription() . '</h3>
            <p>产品编号：' . $goods->getNumber() . '</p>
            <div class="price_btn main">' . $price . '</div>
            <span class="tip"><i>新品</i></span>
        </a>
    </div>';
}
$out.='</div>';
echo $out;
?>
