<?php
$out = '';
$goodsLists = $this->getProductList();
if (count($goodsLists) == 0) {
   echo $out;
   return;
}
foreach ($goodsLists as $goods) {
   $defpic = $goods->getDefaultImage();
   $price0 = $goods->getPrice();
   $infourl = $this->getInfoUrl($goods->getNumber());
   $price = $price0 > 0 ? '¥' . $price0 : '面议';
   $out .= '<div class="pro_show">
                <h4>产品编号：' . $goods->getNumber() . '</h4>
                <p class="clearfix">
                    <span class="pro_price">' . $price . '</span>
                    <span class="pro_detail">' . $goods->getBrand() . ' ' . $goods->getTitle() . ' ' . $goods->getDescription() . '</span>
                </p>
                <a  href="' . $infourl . '"><img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImgUrl($defpic, 290, 181) . '" alt=""></a>
            </div>';
}

echo $out;
