<?php
$out = '';
$goodsLists = $this->getProductList();
if (count($goodsLists) == 0) {
   echo $out;
   return;
}
foreach ($goodsLists as $goods) {
   $defpic = $goods->getDefaultImage();
   $price0 = $goods->getPrice();
   $infourl = $this->getInfoUrl($goods->getNumber());
   $price = $price0 > 0 ? '¥' . $price0 : '面议';
   $out .= '<div class="pro_card" >
                        <div>
                            <a target="_blank" href="' . $infourl . '"><img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImgUrl($defpic, 260, 162) . '" alt=""></a>
                            <p class="active_hover"><a target="_blank" href="' . $infourl . '">' . $goods->getBrand() . ' ' . $goods->getTitle() . ' ' . $goods->getDescription() . ' </a></p>
                            <span class="">' . $price . '</span>
                        </div>
                    </div>';
}

echo $out;
