<?php
$result = $this->getCollection();
$list = $result[0];
$total = $result[1];
$out = '';
if(count($list)){
   foreach($list as $collect){
      $product = $collect->getProduct();
      $company = $product->getCompany();
      $from = '';
      if($company){
         $from = $this->getArea($company->getProvince()).' '.$this->getArea($company->getCity());
      }
      $number = $product->getNumber();
      $imageUrl = $this->getImageCdnUrl($product->getDefaultImage());
      $name = $product->getBrand() . ' ' . $product->getTitle() . ' ' . $product->getDescription(); 
      $url = $this->getProductUrl($product->getNumber());
      $price = 0 == $product->getPrice() ? '面议' : '￥' . $product->getPrice();
      $status = $product->getStatus();
      
      $out.='<div class="collect_ele clearfix" fh-id="'.$collect->getId().'">
            <a href="'.$url.'" class="collect_ele_img" target="__blank"> <img src="'.$imageUrl.'" alt="'.$name.'"></a>
            <div class="collect_container">
                <h4><a href="'.$url.'" target="__blank">'.$name.'</a></h4>
                <p class="collect_price main_light"><span>'.$price.'</span><i>奖0积分</i></p>
                <p class="clearfix">
                    <span class="collect_intro">发货地：</span>
                    <span class="collect_detail">'.$from.' </span>
                </p>
                <p class="clearfix">
                    <span class="collect_intro">销售区域：</span>
                    <span class="collect_detail"></span>
                </p>
            </div>
            <div class="collect_operation ">
                <p class="clearfix">';
      if(3 == $status){
         $out.='<span class="xunjia_btn fr icon-tubiao"></span><span class="phone_btn fr  icon-dianhua2 main_bg_light"></span>';
      }else{
         $out.='<span class="icon-yishixiao"></span>';
      }
                    
      $out.='</p>
               <p class="clearfix"><span class="del_btn fr  icon-shanchu"></span></p>
           </div>
       </div>';
   }
}

$paging = $this->getPaging($total);

if($this->getParam('enablePage') && count($list) && $paging['total'] > 0){
   $out1 = '';
   $currentPage = $paging['current'];
   $cls = "";
   $out .= '<div class="page_list"><p>';
   if ($currentPage > 1) {
      $out.='<a href="'. $this->getPageUrl($currentPage - 1).'" class="prev_page">&lt; 上一页</a>';
   }else{
      $out.='<a class="prev_page">&lt; 上一页</a>';
   }
   if ($currentPage > 5) {
      $out.='<a href="'. $this->getPageUrl(1).'">1</a>... ';
      for ($i = ($currentPage - 2); $i <= $paging['total'] && $i <= $currentPage + 2; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a  class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
   } else {
      for ($i = 1; $i <= $paging['total'] && $i <= 6; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
      if ($paging['total'] > 6) {
         $out1 .='... ' . '<a href="'. $this->getPageUrl(7).'">7</a>';
      }
   }
   $out .= $out1;
   if ($paging['total'] > 0 && $currentPage != $paging['total']) {
      $out .= '<a href="'. $this->getPageUrl($currentPage + 1).'" class="next_page no_marginR" >下一页 &gt;</a>';
   }else{
      $out .= '<a class="next_page no_marginR" >下一页 &gt;</a>';
   }

   $out .= '</p></div>';
}

echo $out;