<?php
$identifier = $this->getRouteInfo()['nodeIdentifier'];
$nodeInfo = $this->getNodeInfoByIdentifier($identifier);
$generalInfos = $this->getInfoListByNodeAndStatus($nodeInfo->getId());
?>
<div class="main_content clearfix conwidth">
	 <!--左侧内容-->
	 <div class="help_left_nav fl">
		  <ul class="left_menu">
				<li class="menu_item">
					 <a class="menu_head main" index="gongsijianjie">公司简介</a>
				</li>
				<li class="menu_item">
					 <a class="menu_head" index="tuanduiguanli">管理团队</a>
				</li>
				<li class="menu_item">
					 <a class="menu_head" index="hexinlinian">核心理念</a>
				</li>
				<li class="menu_item">
					 <a class="menu_head" index="falvshengming">法律声明</a>
				</li>
				<li class="menu_item">
					 <a class="menu_head" index="lianxiwomen">联系我们</a>
				</li>
		  </ul>
	 </div>
	 <!--右侧内容-->
	 <div class="right_content fr" style="display: none;">
		  <div class="right_content_title">
				<h3 class="title">11111</h3>
		  </div>
		  <div class="about_content">

		  </div>
	 </div>
	 <div class="right_content fr">
		  <div class="right_content_title">
				<h3 class="title">22222</h3>
		  </div>
		  <div class="about_content">

		  </div>
	 </div>
</div>