<?php
$help = $this->getNodeInfoByIdentifier('help');
$subNodes = $this->getSubNodesByIdentifier('help');
$nodeIds = array(
	$help->getId()
);
foreach ($subNodes as $node) {
	$nodeIds[] = $node->getId();
	$itemNodes = $this->getSubNodesByIdentifier($node->getNodeIdentifier());
	foreach ($itemNodes as $v) {
		$nodeIds[] = $v->getId();
	}
}
$infos = $this->getInfoListByNodeAndStatusNotPage($nodeIds);
$out = '';
foreach ($infos as $info) {
   $out .= '<li class="hot_item"><a href="/article/' . $info->getId() . '.html">' . $info->getTitle() . '</a></li>';
}
echo $out;
