<?php
$identifier = $this->getRouteInfo()['nodeIdentifier'];
$nodeInfo = $this->getNodeInfoByIdentifier($identifier);
$out = '<div class="right_content fl">
	 <h3>' . $nodeInfo->getText() . '</h3>';
$generalInfos = $this->getInfoListByNodeAndStatus($nodeInfo->getId());
foreach ($generalInfos[0] as $generalInfo) {
	$out .= '<div class="right_list clearfix">
		  <a href="/article/' . $generalInfo->getId() . '.html" class="news_img">
				<img src="' . Cntysoft\Kernel\get_image_cdn_url($generalInfo->getDefaultPicUrl()[0], 200, 140) . '">
		  </a>
		  <h4 class="news_title text_ellipsis main_hover"><a href="/article/' . $generalInfo->getId() . '.html">' . $generalInfo->getTitle() . '</a></h4>
		  <p class="time_look"><span class="time">发表时间：' . date('Y-m-d', $generalInfo->getInputTime()) . '</span> <span class="look">阅读量：' . $generalInfo->getHits() . '</span></p>
		  <p class="news_content">' . $generalInfo->getIntro() . '
		  </p>
		  <a href="/article/' . $generalInfo->getId() . '.html" class="read_more">详情 &gt;&gt;</a>
	 </div>';
}

$out .= '<div class="page_list"><p>';
$totalPage = ceil($generalInfos[1] / $this->invokeParams['outputNum']);
if (0 != $totalPage) {
	$out .= '<a href="/category/' . $identifier . '/1.html">首页</a>';
}
$pageId = (int) $this->getRouteInfo()['pageid'];
if ($pageId != 1) {
	$out .= '<a href="/category/' . $identifier . '/' . ($pageId - 1) . '.html">&lt; 上一页</a>';
}
if ($totalPage <= 6) {
	for ($i = 1; $i <= $totalPage; $i++) {
		if ($i != $pageId) {
			$out .= '<a class="" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
		} else {
			$out .= '<a class="main_bg main_border" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
		}
	}
} else {
	if ($pageId >= 3 && $pageId < $totalPage - 3) {
		for ($i = $pageId - 2; $i <= $pageId + 3; $i++) {
			if ($i != $pageId) {
				$out .= '<a class="" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
			} else {
				$out .= '<a class="main_bg main_border" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
			}
		}
	} else if ($pageId < 3) {
		for ($i = 1; $i <= 6; $i++) {
			if ($i != $pageId) {
				$out .= '<a class="" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
			} else {
				$out .= '<a class="main_bg main_border" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
			}
		}
	} else if ($pageId >= $totalPage - 3) {
		for ($i = $totalPage - 5; $i <= $totalPage; $i++) {
			if ($i != $pageId) {
				$out .= '<a class="" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
			} else {
				$out .= '<a class="main_bg main_border" href="/category/' . $identifier . '/' . $i . '.html">' . $i . '</a>';
			}
		}
	}
}
if ($pageId != $totalPage && $totalPage != 0) {
	$out .= '<a href="/category/' . $identifier . '/' . ($pageId + 1) . '.html">下一页 &gt;</a>';
}
if (0 != $totalPage) {
	$out .= '<a href="/category/' . $identifier . '/' . $totalPage . '.html">尾页</a>';
}
$out .= '</p></div></div>';
echo $out;
