<?php
$result = $this->getProductList();
$status = $this->getStatus();
$list = $result[0];
$total = $result[1];
$out='<div class="prolist_wrap">
         <div class="prolist_operate">
            <span class="check"><em><i></i></em>全选</span>
            <span class="btn btn_del delete">删除</span>';
if(3 == $status){
   $out.='<span class="btn btn_del shelf">下架</span>';
}else if(5 == $status){
   $out.='<span class="btn btn_del upshelf">上架</span>';
}
$out.='<a class="question" target="_blank" href="http://' . \Cntysoft\RT_SYS_SITE_NAME . '/category/guanlichanpiing/1.html">产品上下架问题解答&gt;</a>
         </div>
         <!--标题-->
         <table>
            <tr class="prolist_items">
               <th class="pro-code">产品编号</th>
               <th class="pro_img">图片</th>
               <th class="pro_title">标题</th>
               <th class="pro_price">价格</th>';
if(3 == $status){
   $out.='<th class="pro_time">上架时间</th>';
}else if(5 == $status){
   $out.='<th class="pro_time">下架原因</th>';
}else{
   $out.='<th class="pro_time">添加时间</th>';
}
$out.='<th class="pro_star">质量星级</th>
         <th class="pro_operate">操作</th>
         <th class="pro_code2">产品二维码</th>
      </tr>';
if(count($list)){
   foreach ($list as $product){
      $name = $product->getBrand() . $product->getTitle() . $product->getDescription();
      $productId = $product->getId();
      $number = $product->getNumber();
      $price = (0 == $product->getPrice()) ? '面议' : '￥<em>'.$product->getPrice().'</em>';
      $time = date('Y-m-d', $product->getInputTime());
      $comment = $product->getComment();
      $image = $this->getImageCdnUrl($product->getDefaultImage());
      $url = $this->getProductUrl($number);
      $siteurl=$this->getSiteProductUrl($number);
      $star = $product->getStar();
      $out.='<tr class="prolist_list " fh-number="'.$number.'">
            <td class="pro-code">
               <span class="check"><em><i ></i></em></span>
               <span>'.$number.'</span>
            </td>
            <td class="pro_img">
               <a href="'.$siteurl.'" target="_blank"><img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="'.$image.'"></a>
            </td>
            <td class="pro_title">
               <a href="'.$siteurl.'" target="_blank"><p>'.$name.'</p></a>
            </td>
            <td class="pro_price ">'.$price.'</td>
            <td class="pro_time">'. (5 == $status ? $comment : $time ).'</td>
            <td class="pro_star">';
      for($i=0; $i<5; $i++){
         if($i<$star){
            $out.='<i class="icon-star main"></i>';
         }else{
            $out.='<i class="icon-star"></i>';
         }
      }
      $out.='</td>
            <td class="pro_operate">
               <a href="/product/change/'.$number.'.html">修改</a>
               <span>|</span>
               <a class="delete">删除</a>
            </td>
            <td class="pro_code2">
                        <i class="icon-erweima"></i>
                        <div class="pro_code_box">
                            <p>点击下载二维码</p>
                            <div class="code_img" url="'.$siteurl.'" title="'.$name.'">
                            </div>
                        </div>
                    </td>
         </tr>';
   }
}else{
//   $out.='<tr class="prolist_list "></tr>';
}
$out.='</table>
   <div class="prolist_operate prolist_bottom">
      <span class="check"><em><i ></i></em>全选</span>
      <span class="btn btn_del delete">删除</span>';
$paging = $this->getPaging($total);
if($this->getParam('enablePage') && count($list) && $paging['total'] > 0){
   $out1 = '';
   $currentPage = $paging['current'];
   $cls = "";
   $out .= '<div class="page_list fr"><p>';
   if ($currentPage > 1) {
      $out.='<a href="'. $this->getPageUrl($currentPage - 1).'" class="prev_page">&lt; 上一页</a>';
   }else{
      $out.='<a class="prev_page">&lt; 上一页</a>';
   }
   if ($currentPage > 5) {
      $out.='<a href="'. $this->getPageUrl(1).'">1</a>... ';
      for ($i = ($currentPage - 2); $i <= $paging['total'] && $i <= $currentPage + 2; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a  class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
   } else {
      for ($i = 1; $i <= $paging['total'] && $i <= 6; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
      if ($paging['total'] > 6) {
         $out1 .='... ' . '<a href="'. $this->getPageUrl(7).'">7</a>';
      }
   }
   $out .= $out1;
   if ($paging['total'] > 0 && $currentPage != $paging['total']) {
      $out .= '<a href="'. $this->getPageUrl($currentPage + 1).'" class="next_page no_marginR" >下一页 &gt;</a>';
   }else{
      $out .= '<a class="next_page no_marginR" >下一页 &gt;</a>';
   }

   $out .= '</p></div>';
}

$out.='</div>
</div>';
echo $out;
?>
