<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>关于我们</title>
        <?php Qs::Sys('loadCss', array('help/helpstyle.css', 'help/aboutus.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a href="/category/guanyuwomen.html">关于我们</a>
        </div>
        <!--帮助中心-->
        <div class="main_content clearfix conwidth">
            <!--左侧内容-->
            <div class="help_left_nav fl">
                <ul class="left_menu">
                    <li class="menu_item">
                        <a class="menu_head main" index="gongsijianjie">公司简介</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" index="tuanduiguanli">管理团队</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" index="hexinlinian">核心理念</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" index="falvshengming">法律声明</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" index="lianxiwomen">联系我们</a>
                    </li>
                </ul>
            </div>
            <!--右侧内容-->
            <div class="right_content fr">
                <div class="right_content_title">
                    <h3 class="title">22222</h3>
                </div>
                <div class="about_content">

                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部'); ?>
        <script data-main="/Statics/Skins/Pc/Js/requireenter.js" app="help/help" id="require" src="/Statics/Skins/Pc/Js/lib/require.js"></script>
    </body>
</html>