<?php Qs::Ds('商城数据源/商城数据', 'site'); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心-<?php Qs::DsField('site', 'SiteTitle') ?></title>
    <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
    <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
    <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
		  <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
    <?php Qs::Sys('loadCss', array('huiyuan/style.css', 'huiyuan/user.css'))?>
</head>
<body>
<!--头部-->
<!--个人中心头部-->
<?php Qs::Label('采购商/用户中心头部', array('renderTpl' => 'Pc_Header'))?>
<!--个人中心-->
<div class="content conwidth clearfix">
    <!--左侧列表-->
    <?php Qs::Label('采购商/用户中心左侧')?>
    <!--右侧内容-->
    <div class="content_wrap fr">
        <h1 class="items_title">个人信息</h1>
        <div class="form_box">
            <div class="form_list">
                <label><em class="main">*</em>旧密码:</label>
                <input type="password" id="oldpassword" fh-type="password" required>
            </div>
            <div class="form_list">
                <label><em class="main">*</em>新密码:</label>
                <input type="password" id="newpassword" fh-type="password" required>
            </div>
            <div class="form_list">
                <label><em class="main">*</em>重复密码:</label>
                <input type="password" id="repassword" fh-type="password" required>
            </div>
            <!--按钮-->
            <div class="action_btn" style="width: 600px">
                <a class="main_bg submit">提交</a>
                <a class="main_bg reset">重置</a>
            </div>
        </div>
    </div>
</div>
<?php Qs::Label('静态类/登陆注册网站底部'); Qs::Sys('loadRequireJs', 'buyer/password')?>
</body>
</html>