<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关注企业</title>
    <?php Qs::Sys('loadCss', array('buyer/style.css', 'buyer/company.css'))?>
</head>
<body>
<!--头部-->
<!--个人中心头部-->
<?php Qs::Label('采购商/用户中心头部')?>
<!--个人中心-->
<div class="content conwidth clearfix">
    <!--左侧列表-->
    <?php Qs::Label('采购商/用户中心左侧')?>
    <!--右侧内容-->
    <div class="content_wrap fr">
        <h1 class="items_title">关注企业</h1>
        <?php Qs::Label('采购商/关注企业列表', array('renderTpl' => 'CompanyList', 'outputNum' => 4, 'enablePage' => true))?>
    </div>
</div>
<!--合作伙伴-->
<?php Qs::Label('静态类/网站底部'); Qs::Sys('loadRequireJs', 'buyer/company')?>
</body>
</html>