<?php Qs::Ds('商城数据源/商城数据', 'site'); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关注企业-<?php Qs::DsField('site', 'SiteTitle') ?></title>
    <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
    <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
    <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
		  <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
    <?php Qs::Sys('loadCss', array('huiyuan/style.css', 'huiyuan/company.css'))?>
</head>
<body>
<!--头部-->
<!--个人中心头部-->
<?php Qs::Label('采购商/用户中心头部', array('renderTpl' => 'Pc_Header'))?>
<!--个人中心-->
<div class="content conwidth clearfix">
    <!--左侧列表-->
    <?php Qs::Label('采购商/用户中心左侧')?>
    <!--右侧内容-->
    <div class="content_wrap fr">
        <h1 class="items_title">关注企业</h1>
        <?php Qs::Label('采购商/关注企业列表', array('renderTpl' => 'CompanyList', 'outputNum' => 4, 'enablePage' => true))?>
    </div>
</div>
<!--合作伙伴-->
<?php Qs::Label('静态类/登陆注册网站底部'); Qs::Sys('loadRequireJs', 'buyer/company')?>
</body>
</html>