<?php Qs::Ds('用户数据源/采购商', 'User');Qs::Ds('商城数据源/商城数据', 'site');?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>个人中心-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('huiyuan/style.css', 'huiyuan/user.css')) ?>
        <style>
            div.radio i {
                width: 16px;
                height: 16px;
                width:16px\9\0;
                height:16px\9\0;
                *width:0;
                *height:0;
            }
        </style>
    </head>
    <body>
        <!--头部-->
        <!--个人中心头部-->
        <?php Qs::Label('采购商/用户中心头部', array('renderTpl' => 'Pc_Header')) ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('采购商/用户中心左侧') ?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">个人信息</h1>
                <div class="form_box">
                    <div class="form_list">
                        <label class="label_uploading"><em class="main">*</em>用户头像:</label>
                        <ul class="img_uploading clearfix">
                            <?php
                            $avatar = Qs::DsField('User', 'avatar', true);
                            if ($avatar) {
                               echo '<li class="avatar"><img id="avatar" src="' . $avatar . '" fh-rid="' . Qs::DsField('User', 'rid', true) . '"><em class="deleteImg">删除</em></li><li class="img_plus hide"><p>+</p><span>添加照片</span></li>';
                            } else {
                               echo '<li class="img_plus"><p>+</p><span>添加照片</span></li>';
                            }
                            ?>
                        </ul>
                    </div>
                    <?php
                    $name = Qs::DsField('User', 'name', true);
                    if (!$name) {
                       $canChange = '';
                    } else {
                       $canChange = 'disabled class="no_border"';
                    }
                    ?>
                    <div class="form_list">
                        <label><em class="main">*</em>用&nbsp;户&nbsp;名:</label>
                        <input type="text" id='name' value="<?php echo $name; ?>" reg="/^[a-zA-Z0-9]{3,10}$/" <?php echo $canChange ?>>
                    </div>
                    <div class="form_list">
                        <label><em class="main"></em>等&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;级:</label>
                        <input type="text" id='level' value="<?php echo 'LV' . Qs::DsField('User', 'level', true); ?>" disabled class="no_border">
                    </div>
                    <div class="form_list">
                        <label><em class="main"></em>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别:</label>
                        <?php
                        $checkArray = array(1 => '', 2 => '', 3 => '');
                        $sex = Qs::DsField('User', 'sex', true);
                        if ($sex == 1) {
                           $checkArray[1] = 'checked';
                        } elseif ($sex == 2) {
                           $checkArray[2] = 'checked';
                        } else {
                           $checkArray[3] = 'checked';
                        }
                        ?>
                        <div class="radio margin-left">
                            <label for="sex">
                                <input id="sex" name="sex" type="radio"  value="1" <?php echo $checkArray[1] ?>>
                                <i></i>
                                <span>男</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="sex2">
                                <input id="sex2" name="sex" type="radio"  value="2" <?php echo $checkArray[2] ?>>
                                <i></i>
                                <span>女</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="sex3">
                                <input id="sex3" name="sex" type="radio" value="3" <?php echo $checkArray[3] ?>>
                                <i></i>
                                <span>保密</span>
                            </label>
                        </div>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>手机号码:</label>
                        <input type="text" id="phone" value="<?php Qs::DsField('User', 'phone') ?>" disabled class="no_border">
                    </div>
                    <div class="action_btn" style="width:600px;margin-bottom: 20px">
                        <label></label>
                        <a class="main_bg" id="submit">提交</a>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/登陆注册网站底部');Qs::Sys('loadRequireJs', 'buyer/basic');?>
    </body>
</html>