<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心</title>
    <?php Qs::Sys('loadCss', array('buyer/style.css', 'buyer/baojiadetail.css'))?>
</head>
<body>
<!--个人中心头部-->
<?php Qs::Label('采购商/用户中心头部')?>
<!--个人中心-->
<div class="content conwidth clearfix">
    <!--左侧列表-->
    <?php Qs::Label('采购商/用户中心左侧')?>
    <!--右侧内容-->
    <div class="content_wrap fr">
        <h1 class="items_title">报价</h1>
        <?php Qs::Label('采购商/报价单详情', array('renderTpl' => 'Quotation'))?>
    </div>
</div>
<?php Qs::Label('静态类/网站底部');?>
</body>
</html>