<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心</title>
    <?php Qs::Sys('loadCss', array('buyer/style.css', 'buyer/baojialist.css'))?>
</head>
<body>
<!--头部-->
<!--个人中心头部-->
<?php Qs::Label('采购商/用户中心头部')?>
<!--个人中心-->
<div class="content conwidth clearfix">
    <!--左侧列表-->
    <?php Qs::Label('采购商/用户中心左侧')?>
    <!--右侧内容-->
    <div class="content_wrap fr">
        <h1 class="items_title">收到的报价单</h1>
        <?php Qs::Label('采购商/报价单列表', array('renderTpl' => 'QuotationList', 'outputNum' => 4, 'enablePage' => true))?>
    </div>
</div>
<?php Qs::Label('静态类/网站底部'); Qs::Sys('loadRequireJs', 'buyer/collection')?>
</body>
</html>