<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>收藏商品</title>
    <?php Qs::Sys('loadCss', array('buyer/style.css', 'buyer/collect_pro.css'))?>
</head>
<body>
<!--头部-->
<div class="header_top">
    <div class="conwidth header_top_inner clearfix">
        <div class="fl">
            欢迎来到凤凰筑巢！ <a class="login_btn main_hover">请登录</a> <a class="register_btn main_hover">注册</a>
        </div>
        <ul class="fr header_top_nav main_hover">
            <li><a href="">我的询价单</a></li>
            <li class="line"></li>
            <li><a href="">会员中心 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">我是 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">供应商专区</a></li>
            <li class="line"></li>
            <li><a href="">运营商专区</a></li>
            <li class="line"></li>
            <li><a href="">网站地图 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">帮助中心</a></li>
            <li class="line"></li>
            <li class="more_btn mainbg_hover"><a>关注我们 <i class="iicon-xiangxiajiantou"></i></a>
                <div class="pull_more main_bg">
                    <img class="erweima" src="../../Images/test/test_news_img.jpg">
                    <span>扫码下载凤凰筑巢客户端</span>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--个人中心头部-->
<?php Qs::Label('采购商/用户中心头部')?>
<!--个人中心-->
<div class="content conwidth clearfix">
    <!--左侧列表-->
    <?php Qs::Label('采购商/用户中心左侧')?>
    <!--右侧内容-->
    <div class="content_wrap fr">
        <h1 class="items_title">收藏产品</h1>
        <div class="collect_list">
            <?php Qs::Label('采购商/收藏产品列表', array('renderTpl' => 'ProductList', 'outputNum' => 4, 'enablePage' => true))?>
        </div>
        </div>
    </div>
<!--合作伙伴-->
<?php Qs::Label('静态类/网站底部'); Qs::Sys('loadRequireJs', 'buyer/collection')?>
</body>
</html>