<?php
Qs::Ds('商城数据源/商城数据', 'site');
Qs::Ds('云站数据源/标准内容模型', 'info');
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>修改案例-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css', 'lib/default.css', 'lib/reset.css')) ?>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧', array('renderTpl' => 'SiteSetting')) ?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">职位招聘</h1>
                <div class="form_box">
                    <div class="form_list">
                        <label><em class="main">*</em>职位:</label>
                        <input type="text" id="title" class="checkfield" reg="^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){2,15}$" tip-value="请输入2-15位职位名称" value="<?php Qs::DsField('info', 'title'); ?>" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>部门:</label>
                        <input type="text" id="department" class="checkfield"  reg="^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){2,15}$" tip-value="请输入2-15位部门名称" value="<?php Qs::DsField('info', 'department'); ?>" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>数量:</label>
                        <input type="text" id="number" class="checkfield middle_input" fh-type="number" value="<?php Qs::DsField('info', 'number'); ?>" required>
                    </div>
                    <div class="form_list clearfix">
                        <label class="fl"><em class="main">*</em>描述内容:</label>
                        <div class="fl">
                            <p class="title">&nbsp;&nbsp; 排版好样式会在招聘页面直接显示</p>
                            <textarea class="textarea_area" id="info_editor" style="height:400px;"><?php Qs::DsField('info', 'content'); ?></textarea>
                        </div>
                    </div>
                    <?php
                    $number = explode('-', Qs::DsField('info', 'tel', true));
                    if (!isset($number)) {
                       $number = array(86, '', '');
                    }
                    ?>
                    <div class="form_list">
                        <label>座机:</label>
                        <input class="tel_china checkfield" id="telCountry" tip-target="#telNum" type="text" value="<?php echo $number[0]; ?>" placeholder="86" reg="[1-9][0-9]{1,3}" tip-value="国家区号为2-3位数字" required>
                        <span class="tel_line">-</span>
                        <input class="tel_code checkfield" id="telArea" tip-target="#telNum" type="text" value="<?php echo $number[1]; ?>" placeholder="区号"  reg="0[1-9][0-9]{1,2}" tip-value="区号为以0开头3-4位数" required>
                        <span class="tel_line">-</span>
                        <input class="tel_num checkfield" id="telNum" type="text" placeholder="电话号码" value="<?php echo $number[2]; ?>" fh-type="tel" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>截止日期:</label>
                        <input type="text" id="endTime" class="checkfield" reg="^[1-2][\d]{3}-[0-1][\d]-[0-3][\d]$" fh-toggle="datepicker" style="width:140px;" readonly="true" tip-value="请选择日期" value="<?php echo date('Y-m-d', Qs::DsField('info', 'endTime', true)) ?>" required>
                    </div>
                    <div class="form_list">
                        <div class="action_btn">
                            <a class="main_bg" id="submit">保存</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
        <?php Qs::Sys('loadRequireJs', 'provider/jobmodify') ?>
    </body>
</html>