<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>个人中心</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/zhaopin.css', 'lib/default.css', 'lib/reset.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <div class="items_wrap fl">
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>账户中心</dt>
                    <dd><a class="mainbg_hover_light" href="/account/index.html">基本信息</a></dd>
                    <dd><a class="mainbg_hover_light" href="/account/company.html">企业信息</a></dd>
                    <dd><a class="mainbg_hover_light" href="/account/safe.html">修改密码</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>产品中心</dt>
                    <dd><a class="main_bg_light" href="/product/addproduct/1.html">发布产品</a></dd>
                    <dd><a class="mainbg_hover_light" href="/product/1.html">产品管理</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>询价单</dt>
                    <dd><a class="mainbg_hover_light" href="/inquiry/1.html">全部</a></dd>
                    <dd><a class="mainbg_hover_light" href="/inquiry/1.html?status=1">未回复</a></dd>
                    <dd><a class="mainbg_hover_light" href="/inquiry/1.html?status=2">已回复</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>店铺设置</dt>
                    <dd><a class="mainbg_hover_light" href="/site/news/1.html">店铺新闻</a></dd>
                    <dd><a class="mainbg_hover_light" href="/site/job/1.html">招聘</a></dd>
                    <dd><a class="mainbg_hover_light" href="/site/setting.html">店铺设置</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>消息</dt>
                    <dd><a class="mainbg_hover_light" href="/account/businessmsg/1.html">服务消息</a></dd>
                    <dd><a class="mainbg_hover_light" href="/account/sysmsg/1.html">系统消息</a></dd>
                </dl>
            </div>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">企业招聘<a class="main_bg_light fr" href="/site/job/add.html"><em>+</em>发布招聘信息</a></h1>
                <div class="notice main_bg_light">
                    <a><i class="main icon-notice"></i> 你已发布 1 条招聘信息，还可发布 999 条</a>
                </div>
                <!--新闻标题-->
                <!--标题-->
                <table>
                    <tr class="recruit_items">
                        <th class="recruit_title">项目名称</th>
                        <th class="recruit_num">招聘人数</th>
                        <th class="recruit_time">发布时间</th>
                        <th class="recruit_status">招聘状态</th>
                        <th class="recruit_operate">操作</th>
                    </tr>
                    <tr class="recruit_list ">
                        <td class="recruit_title">
                            <span class="check"><em><i></i></em></span>
                            <a class="caption" href="#"><em>[顶]</em>昶王科技开通世界工厂网店铺啦</a>
                        </td>
                        <td class="recruit_num">12</td>
                        <td class="recruit_time">
                            2016-03-07<br>13:12:12
                        </td>
                        <td class="recruit_status">已过期</td>
                        <td class="recruit_operate">
                            <a href="">修改</a>
                            <span>|</span>
                            <a href="">删除</a>
                            <span>|</span>
                            <a href="#">取消置顶</a>
                        </td>
                    </tr>
                    <!--暂无新闻i，赶快去添加-->
                    <tr class="recruit_list no_recruit">
                        <td colspan=5>暂无发布招聘信息，赶快去添加吧~~</td>
                    </tr>
                </table>
                <div class="recruit_delete  ">
                    <span class="check"><em><i></i></em>全选</span>
                    <span class="btn btn_del">删除</span>
                </div>
                <!--分页-->
                <div class="page_list">
                    <p>
                        <a class="first_page" href="#">首页</a>
                        <a class="prev_page" href="#">上一页</a>
                        <a class="main_bg main_border" href="#">1</a>
                        <a href="#">2</a>
                        <a href="#">3</a>
                        <a class="no_all_b" href="#">......</a>
                        <a href="#">100</a>
                        <a class="next_page no_marginR" href="#">下一页</a>
                        <a class="last_page no_marginR" href="#">尾页</a>
                        <span>&nbsp;共10页&nbsp;到第</span>
                        <input type="text" onkeyup="value = value.replace(/[^\d/g]/, '')">
                        <span>页</span>
                        <span class="page_submit mainbg_hover">确认</span>
                    </p>
                </div>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'provider/newscontent') ?>
    </body>
</html>