<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>企业新闻</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/news.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧')?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">发布产品<a class="main_bg_light fr" href="/site/news/add.html"><em>+</em>发布新闻</a></h1>
                <div class="notice main_bg_light">
                    <a><i class="main icon-notice"></i> 你已发布 1 条企业新闻，还可发布 999 条</a>
                </div>
                <!--新闻标题-->
                <!--标题-->
                <?php Qs::Label('供应商/新闻',array('renderTpl' => 'usercenterList'))?>
                <div class="news_delete  ">
                    <span class="check"><em><i></i></em>全选</span>
                    <span class="btn btn_del">删除</span>
                </div>
            </div>
        </div>
    </div>
    <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom'))?>
    <?php Qs::Sys('loadRequireJs', 'provider/newslist') ?>
</body>

</html>