<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>个人中心</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css','lib/default.css','lib/reset.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧')?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">个人信息</h1>
                <div class="form_box">
                    <div class="form_list">
                        <label><em class="main">*</em>标题:</label>
                        <input type="text" id='title' class="checkfield" reg="^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){5,30}$" tip-value="请输入5-30位新闻标题" required>
                    </div>
                    <div class="form_list">
                        <label class="label_uploading"><em class="main">*</em>封面：</label>
                        <ul class="img_uploading clearfix">
                            <li class="img_plus">
                                <p>+</p>
                                <span>添加照片</span>
                            </li>
                        </ul>
                    </div>
                    <div class="form_list clearfix">
                        <label class="fl"><em class="main">*</em>描述内容:</label>

                        <div class="fl">
                            <p class="title">&nbsp;&nbsp; 排版好样式会在招聘页面直接显示</p>
                            <textarea class="textarea_area" id="info_editor" style="height: 400px;width: 650px;"></textarea>
                        </div>
                    </div>
                    <div class="form_list">
                        <div class="action_btn">
                            <a class="main_bg" id="submit">保存</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom'))?>
        <?php Qs::Sys('loadRequireJs', 'provider/newscontent') ?>
    </body>
</html>