<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>个人中心</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css', 'lib/default.css', 'lib/reset.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <div class="items_wrap fl">
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>账户中心</dt>
                    <dd><a class="mainbg_hover_light" href="/account/index.html">基本信息</a></dd>
                    <dd><a class="mainbg_hover_light" href="/account/company.html">企业信息</a></dd>
                    <dd><a class="mainbg_hover_light" href="/account/safe.html">修改密码</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>产品中心</dt>
                    <dd><a class="main_bg_light" href="/product/addproduct/1.html">发布产品</a></dd>
                    <dd><a class="mainbg_hover_light" href="/product/1.html">产品管理</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>询价单</dt>
                    <dd><a class="mainbg_hover_light" href="/inquiry/1.html">全部</a></dd>
                    <dd><a class="mainbg_hover_light" href="/inquiry/1.html?status=1">未回复</a></dd>
                    <dd><a class="mainbg_hover_light" href="/inquiry/1.html?status=2">已回复</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>店铺设置</dt>
                    <dd><a class="mainbg_hover_light" href="/site/news/1.html">店铺新闻</a></dd>
                    <dd><a class="mainbg_hover_light" href="/site/job/1.html">招聘</a></dd>
                    <dd><a class="mainbg_hover_light" href="/site/setting.html">企业介绍</a></dd>
                    <dd><a class="mainbg_hover_light" href="/site/setting.html">企业文化</a></dd>
                    <dd><a class="mainbg_hover_light" href="/site/setting.html">联系我们</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>消息</dt>
                    <dd><a class="mainbg_hover_light" href="/account/businessmsg/1.html">服务消息</a></dd>
                    <dd><a class="mainbg_hover_light" href="/account/sysmsg/1.html">系统消息</a></dd>
                </dl>
            </div>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">企业介绍</h1>
                <div class="form_box">
                    <div class="form_list clearfix">
                        <textarea class="textarea_area" id="info_editor" style="height: 400px;width: 100%;"></textarea>
                    </div>
                    <div class="form_list tc">
                        <a class="l_btn" id="submit">保存</a>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'provider/setting') ?>
    </body>
</html>