<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>个人中心</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css', 'lib/default.css', 'lib/reset.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧')?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">企业介绍</h1>
                <div class="form_box">
                    <div class="form_list clearfix">
                        <textarea class="textarea_area" id="info_editor" style="height: 400px;width: 100%;"></textarea>
                    </div>
                    <div class="form_list tc">
                        <a class="l_btn" id="submit">保存</a>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'provider/setting') ?>
    </body>
</html>