<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>个人中心</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧') ?>
            <div class="content_wrap fr">
                <h1 class="items_title">开通店铺</h1>
                <div class="notice main_bg_light">
                    <a><i class="main icon-notice"></i> 您还没有开通店铺哦~</a>
                </div>
                <div class="form_box">
                    <div class="form_list">
                        <label><em class="main">*</em>站点域名:</label>
                        <input type="text" id="subattr" fh-type="subname" required>
                    </div>
                    <!--按钮-->
                    <div class="action_btn" style="width: 600px">
                        <a class="main_bg submit" id="submit">提交</a>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
        <?php Qs::Sys('loadRequireJs', 'provider/siteopen') ?>
    </body>
</html>