<?php
use App\Yunzhan\Content\Constant;
Qs::Ds('商城数据源/商城数据', 'site');
Qs::Ds('云站数据源/标准内容模型', 'info', array('itemId' => Constant::INFO_CONTACT_ID));
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>联系我们-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('usercenter/providerstyle.css', 'usercenter/user_index1.css', 'lib/default.css', 'lib/reset.css')) ?>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧', array('renderTpl' => 'SiteSetting')) ?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">联系我们</h1>
                <div class="form_box">
                    <div class="form_list clearfix">
                        <textarea class="textarea_area" id="info_editor" style="height: 400px;width: 100%;"><?php Qs::DsField('info', 'content'); ?></textarea>
                    </div>
                    <div class="form_list tc">
                        <div class="action_btn" style="width: 600px">
                            <a class="main_bg submit" id="submit">保存</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
        <?php Qs::Sys('loadRequireJs', 'provider/sitecontact') ?>
    </body>
</html>