<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>业务介绍-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/service.css','layer.ext.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a class="main_hover" href="/">首页</a>
            <span>&gt;</span>
            <a>关于我们</a>
            <span>&gt;</span>
            <a>业务介绍</a>
        </div>
        <div class="l_main conwidth clearfix">
            <!--左侧-->
            <div class="l_left ">
                <h3 class="main_bg_light">关于我们<span>About us</span></h3>
                <ul>
                    <li class=""><a href="/about/company.html"><i class="icon-iconfonticonfontgongsijianjie"></i>公司简介</a></li>                    
                    <li class=""><a href="/about/culture.html"><i class="icon-qiyewenhua"></i>企业文化</a></li>
                    <li class="active"><a href="/about/business.html"><i class="icon-chanpinjieshao"></i>业务介绍</a></li>
                    <li class=""><a href="/about/qualification.html"><i class="icon-zizhi"></i>企业资质</a></li>
                    <li class=""><a href="/about/ad.html"><i class="icon-fengcai"></i>公司环境</a></li>
                    <li class=""><a href="/about/join.html"><i class="icon-iconfontlijishenqingxingjia"></i>加入我们</a></li>
                    <li class=" "><a href="/about/legal.html"><i class="icon-icon"></i>法律声明</a></li>
                    <li class=""><a href="/about/contact.html"><i class="icon-lianxiwomen"></i>联系我们</a></li>
                </ul>
            </div>
            <!--右侧-->
            <div class="l_right">
                <h2 class="right_title">业务介绍</h2>
                <p>凤凰筑巢是建材及其相关行业产品信息发布与采购的信息平台。为建材行业提供供应商与采购商之间的供求对接，消除中间商，实现信息发布、搜索、数据统计、优质推荐、在线洽谈等服务，让采购商以更低的成本、更多的选择购买到更优质的建材及其相关产品和服务。</p>
                <div class="service_box">
                    <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_service.png') ?>" alt="">
                </div>
                <div class="clearfix service_detail">
                    <div class="fl">
                        <p>我们为供应商提供</p>
                        <p>免费开商铺，免费发布信息；</p>
                        <p>多种推广渠道，提高产品点击率；</p>
                        <p>推荐意向客户，实现供求高效对接；</p>
                        <p>提供产品的多种数据统计、排名等，寻找精准客户。</p>
                    </div>
                    <div class="fr">
                        <p>我们为采购者提供&nbsp;&nbsp;&nbsp;</p>
                        <p>免费需求发布平台；</p>
                        <p>所需商品的供应商信息；</p>
                        <p>发布商品的供应商报价；</p>
                        <p>行业专家讲解推荐。</p>
                    </div>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'help/help');
        ?>
    </body>
</html>