<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>业务介绍-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('help/helpstyle.css', 'help/aboutus.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a href="/about/business.html">业务介绍</a>
        </div>
        <!--帮助中心-->
        <div class="main_content clearfix conwidth">
            <!--左侧内容-->
            <div class="help_left_nav fl">
                <ul class="left_menu">
                    <li class="menu_item">
                        <a class="menu_head" href="/about/company.html">公司简介</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" href="/about/culture.html">企业文化</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head main" href="/about/business.html">业务介绍</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" href="/about/qualification.html">企业资质</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" href="/about/join.html">加入我们</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" href="/about/legal.html">法律声明</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" href="/about/ad.html">广告服务</a>
                    </li>
                    <li class="menu_item">
                        <a class="menu_head" href="/about/contact.html">联系我们</a>
                    </li>
                </ul>
            </div>
            <!--右侧内容-->
            <div class="right_content fr">
                <div class="right_content_title">
                    <h3 class="title">业务介绍</h3>
                </div>
                <div class="about_content" style="text-indent: 2em;">
                    <p>凤凰筑巢是建材及其相关行业产品信息发布与采购的信息平台。为建材行业提供供应商与采购商之间的供求对接，消除中间商，实现信息发布、搜索、数据统计、优质推荐、在线洽谈等服务，让采购商以更低的成本、更多的选择购买到更优质的建材及其相关产品和服务。</p>
                    <p>我们为<strong>采购者</strong>提供: </p>
                    <p>提供所采购商品的供应商信息；</p>
                    <p>甄选所有供应商信息，提供最合适的供应商推荐；</p>
                    <p>缩短采购时间；</p>
                    
                    <p>我们为<strong>供应商</strong>提供:</p>
                    <p>不收取会员费，免费发布信息；</p>
                    <p>提供信息发布渠道，让更多的人知道他们的产品；</p>
                    <p>为供应商推荐意向客户，实现供应商与采购商的共赢；</p>
                    <p>提供产品的点击量、浏览人群及数据统计，行业排名等，为供应商寻找到更多的精准客户；</p>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'help/help');
        ?>
    </body>
</html>