<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>加入我们-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/join.css','layer.ext.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a class="main_hover"  href="/">首页</a>
            <span>&gt;</span>
            <a>关于我们</a>
            <span>&gt;</span>
            <a>加入我们</a>
        </div>
        <!--帮助中心-->
        <div class="l_main conwidth clearfix">
            <!--左侧-->
            <div class="l_left ">
                <h3 class="main_bg_light">关于我们<span>About us</span></h3>
                <ul>
                    <li class=""><a href="/about/company.html"><i class="icon-iconfonticonfontgongsijianjie"></i>公司简介</a></li>                    
                    <li class=""><a href="/about/culture.html"><i class="icon-qiyewenhua"></i>企业文化</a></li>
                    <li class=""><a href="/about/business.html"><i class="icon-chanpinjieshao"></i>业务介绍</a></li>
                    <li class=""><a href="/about/qualification.html"><i class="icon-zizhi"></i>企业资质</a></li>
                    <li class=""><a href="/about/ad.html"><i class="icon-fengcai"></i>公司环境</a></li>
                    <li class="active">
                        <a href="/about/join.html"><i class="icon-iconfontlijishenqingxingjia"></i>加入我们</a>
                        <div class="join_list">
                            <p><a href="#android">Android开发工程师</a></p>
                            <p><a href="#ios">IOS开发工程师</a></p>
                            <p><a href="#php">PHP开发工程师</a></p>
                            <p><a href="#qianduan">前端工程师</a></p>
                            <p><a href="#ui">UI设计师</a></p>
                            <p><a href="#wenan">文案策划</a></p>
                            <p><a href="#bianji">网站编辑</a></p>
                        </div>
                    </li>
                    <li class=" "><a href="/about/legal.html"><i class="icon-icon"></i>法律声明</a></li>
                    <li class=""><a href="/about/contact.html"><i class="icon-lianxiwomen"></i>联系我们</a></li>
                </ul>
            </div>
            <!--右侧-->
            <div class="l_right">
                <h2 class="right_title">加入我们</h2>
                <p>决定一个人的一生，以及整个生命的，有时只是一瞬间的选择，如果你才思敏捷，构思创意如星光般璀璨夺目；如果你睿智冷静，编辑程序如大师般行于流水。</p>
                <p>世界会向那些有目标和远见的人让路不凡的人生由此开启......</p>
                <div id="android" class="join_ele">
                    <h3><i class="main_bg"></i>Android开发工程师</h3>
                    <div class="join_detail">
                        <span class="join_intro">岗位职责：</span>
                        <p>1、负责智能手机应用相关的技术研究；</p>
                        <p>2、从事与商品化相关的技术支持；</p>
                        <p>3、在Android手机上设计并开发应用程序；</p>
                        <p>4、Android平台框架层的维护以及扩展；</p>
                        <p>5、负责Android项目的开发工作；</p>
                        <p>6、负责Android项目的架构设计、方案的制定；</p>
                        <p>7、跟进Android的新技术发展。编写设计开发及实现文档；</p>
                        <p>8、根据产品功能需求设计并完成软件实现；</p>
                        <p>9、参与产品需求分析并制定技术实施方案；</p>
                    </div>
                    <div class="join_detail">
                        <span class="join_intro">岗位要求：</span>
                        <p>1、计算机、通信、电子等相关专业本科以上学历，一年以上工作经验；</p>
                        <p>2、熟悉Linux操作系统，熟悉c/Java编程技术，掌握Android系统网络编程；</p>
                        <p>3、具有J2ME或Java开发经验，熟悉ANDROID手机软件架构；</p>
                        <p>4、熟悉多线程、Socket或ACE等网络通信编程技术；</p>
                        <p>5、熟悉java各种编程方法，比如多线程,jni、aidl等。 熟悉JVM的运行机制；</p>
                        <p>6、具备良好合作态度及团队精神，并富有工作激情、创新力和责任感；</p>
                        <p>7、喜欢挑战高难度项目；有较好的学习能力、沟通能力，能承受一定的工作压力；</p>
                        <p>8、具有良好的英文文档编写能力；</p>
                        <p>9、熟练使用android studio；</p>
                    </div>
                </div>
                <div id="ios" class="join_ele">
                    <h3><i class="main_bg"></i>IOS开发工程师</h3>
                    <div class="join_detail">
                        <span class="join_intro">岗位职责：</span>
                        <p>1、根据需求进行IOS平台客户端软件的设计、开发和维护；</p>
                        <p>2、与项目相关人员配合共同完成应用软件的开发设计工作；</p>
                        <p>3、IOS平台开发环境（平台及工具软件）的设计、实现和维护；</p>
                        <p>4、负责与服务器端调试，确保应用质量；</p>
                        <p>5、按照项工作目计划在保证质量的前提下、按时完成开发任务；</p>
                    </div>
                    <div class="join_detail">
                        <span class="join_intro">岗位要求：</span>
                        <p>1、计算机或相关专业本科及以上学历；</p>
                        <p>2、1-3年以上IOS开发经验；</p>
                        <p>3、有自己独立的IOS端产品上线，自己有MAC、iPhone者优先考虑；</p>
                        <p>4、具体有扎实的Objective-C语言基础，会使用cocos2d-x者优先；</p>
                        <p>5、精通iOS开发技术，能处理比较复杂的UI、线程、系统调用、网络等方面问题；</p>
                        <p>6、精通多线程和网络编程，掌握基本的框架结构和设计模式，对高性能程序设计、架构有较多的工程经验；</p>
                        <p>7、了解App Store发布流程和审核要求；</p>
                        <p>8、深入理解Objective-C Runtime运行机制和内存管理机制；</p>
                        <p>9、熟悉mac os x操作系统和xcode/iphone sdk开发环境；</p>
                    </div>
                </div>
                <div id="php"  class="join_ele">
                    <h3><i class="main_bg"></i>PHP开发工程师</h3>
                    <div class="join_detail">
                        <span class="join_intro">岗位职责：</span>
                        <p>1、负责后台开发和维护工作；</p>
                        <p>2、熟练PHP+MySQL网络程序开发；</p>
                        <p>3、熟悉phalcon框架，了解微信开发优先；</p>
                        <p>4、根据产品开发进度和任务分配，开发相应的应用模块；</p>
                        <p>5、熟练使用Linux操作系统者优先；</p>
                    </div>
                    <div class="join_detail">
                        <span class="join_intro">岗位要求：</span>
                        <p>1、专科及以上学历，计算机及相关专业，至少1年以上工作经验；</p>
                        <p>2、精通LNMP开发；</p>
                        <p>3、熟悉HTML,XHTML,XML,DIV+CSS,javascript，Ajax，jQuery页面制作方式及W3C标准；</p>
                        <p>4、具有PHP缓存技术、静态化设计方面，熟悉TCP/IP、HTTP协议者优先；</p>
                        <p>5、熟练使用git；</p>
                        <p>6、有团队精神，能够主动和队友沟通、分享；</p>
                    </div>
                </div>
                <div id="qianduan" class="join_ele">
                    <h3><i class="main_bg"></i>前端工程师</h3>
                    <div class="join_detail">
                        <span class="join_intro">岗位职责：</span>
                        <p>1、负责web前端框架优化、开发及用户交互体验设计，保障产品的开发和维护；</p>
                        <p>2、熟练运用html5，css3和响应式页面的设计制作，能够独立完成一个网站的静态页面搭建和手机端web页面；</p>
                        <p>3、能够解决各个浏览器之间的兼容性问题，适配现在主流浏览器；</p>
                        <p>4、根据产品需求及设计图输出页面；</p>
                        <p>5、能独立完成工作，服从公司安排，协助相关部门完成其他临时性工作；</p>
                    </div>
                    <div class="join_detail">
                        <span class="join_intro">岗位要求：</span>
                        <p>1、计算机或相关专业本科及以上学历，有相关的网页制作经验；</p>
                        <p>2、熟悉Html,Div,Css进行网页排版与布局，熟悉Html5,Css3，并熟练调试不同浏览器的兼容性；</p>
                        <p>3、熟悉Javascript语言，实现各种页面交互效果，熟悉Jquery,Nodejs等JS框架；</p>
                        <p>4、熟练使用Photoshop常用操作、切图等；</p>
                        <p>5、具备优秀的沟通能力和团队协作能力、高度的责任性；</p>
                    </div>
                </div>
                <div id="ui" class="join_ele">
                    <h3><i class="main_bg"></i>UI设计师</h3>
                    <div class="join_detail">
                        <span class="join_intro">岗位职责：</span>
                        <p>1、负责公司网站的设计、改版、更新；</p>
                        <p>2、负责公司产品的界面进行设计、编辑、美化等工作；</p>
                        <p>3、负责与开发人员配合完成所辖网站等前台页面设计和编辑；</p>
                        <p>4、其他与美术设计相关的工作如宣传册、宣传单页的设计等；</p>
                    </div>
                    <div class="join_detail">
                        <span class="join_intro">岗位要求：</span>
                        <p>1、计算机技术、美术、平面设计等相关专业，本科及以上学历；</p>
                        <p>2、有网页设计及平面设计工作经验者待遇从优；</p>
                        <p>3、有扎实的美术功底、良好的创意思维和理解能力，能及时把握客户需求；</p>
                        <p>4、能够熟练常用的图片处理软件，如Photoshop等；</p>
                        <p>5、构思新颖、创意独特、具有丰富的互联网设计经验；</p>
                        <p>6、善于与人沟通，良好的团队合作精神和高度的责任感，能够承受压力，有创新精神，保证工作质量；</p>
                    </div>
                </div>
                <div id="wenan" class="join_ele">
                    <h3><i class="main_bg"></i>文案策划</h3>
                    <div class="join_detail">
                        <span class="join_intro">岗位职责：</span>
                        <p>1、研究宏观市场信息，包括市场及行业动态、技术发展趋势、国家与地方政策变化及趋势，并收集市场、产品及竞争对手信息；</p>
                        <p>2、负责公司品牌网站、传播平台的建设、维护与更新，确保品牌传播的及时性与有效性；</p>
                        <p>3、负责企业文案、品牌文案、产品广告文案及促销活动推广文案的撰写；</p>
                        <p>4、负责硬广、软文、宣传资料、新闻稿等文案撰写；</p>
                        <p>5、负责公司内刊、公司宣传栏的策划、文案撰写及出版管理；</p>
                        <p>6、根据业务和市场发展状况，制定年度、季度、月度宣传推广计划；</p>
                        <p>7、支持完成展会、促销、会议等营销活动策划工作；</p>
                        <p>8、负责与平面设计师保持密切沟通配合，对广告平面表现提供创意文案支持；</p>
                        <p>9、需文案策划配合协助的其他工作，以及领导安排的其他工作；</p>
                    </div>
                    <div class="join_detail">
                        <span class="join_intro">岗位要求：</span>
                        <p>1、有1年以上工作经验，大专及以上学历；</p>
                        <p>2、对市场行业信息敏感，具有市场分析能力；</p>
                        <p>3、擅长营销文案撰写、新闻撰写、活动方案撰写、网络编辑，有较强的文字编写能力和策划能力；</p>
                        <p>4、拥有独立的工作能力和团队协作精神，具有较强的语言、文字表达能力；</p>
                        <p>5、有激情，有活力，思维活跃，善于沟通；</p>
                    </div>
                </div>
                <div id="bianji" class="join_ele">
                    <h3><i class="main_bg"></i>网站编辑</h3>
                    <div class="join_detail">
                        <span class="join_intro">岗位职责：</span>
                        <p>1、网站的基础运营和维护；</p>
                        <p>2、网站会员管理；</p>
                        <p>4、组合网站关键信息，选择关键字、关键词，提高网站搜索量；</p>
                        <p>5、经理交代的其他工作；</p>
                    </div>
                    <div class="join_detail">
                        <span class="join_intro">岗位要求：</span>
                        <p>1、1-3年工作经验，学历不限；</p>
                        <p>2、多渠道及时了解网站动态，更新网站内容，发布行业信息；</p>
                        <p>3、通过各种网络推广渠道，宣传网站，提高知名度；</p>
                        <p>4、思维活跃，有团队精神；</p>
                    </div>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'aboutus/zhaopin');
        ?>
    </body>
</html>