<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>企业资质-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/zizhi.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a>关于我们</a>
            <span>&gt;</span>
            <a>企业资质</a>
        </div>
        <!--帮助中心-->
        <div class="l_main conwidth clearfix">
            <!--左侧内容-->
            <div class="l_left ">
                <h3 class="main_bg_light">关于我们<span>About us</span></h3>
                <ul>
                    <li class=""><a href="/about/company.html"><i class="icon-iconfonticonfontgongsijianjie"></i>公司简介</a></li>                    
                    <li class=""><a href="/about/culture.html"><i class="icon-qiyewenhua"></i>企业文化</a></li>
                    <li class=""><a href="/about/business.html"><i class="icon-chanpinjieshao"></i>业务介绍</a></li>
                    <li class="active"><a href="/about/qualification.html"><i class="icon-zizhi"></i>企业资质</a></li>
                    <li class=""><a href="/about/ad.html"><i class="icon-fengcai"></i>公司环境</a></li>
                    <li class=""><a href="/about/join.html"><i class="icon-iconfontlijishenqingxingjia"></i>加入我们</a></li>
                    <li class=" "><a href="/about/legal.html"><i class="icon-icon"></i>法律声明</a></li>
                    <li class=""><a href="/about/contact.html"><i class="icon-lianxiwomen"></i>联系我们</a></li>
                </ul>
            </div>
            <!--右侧内容-->
            <div class="l_right">
                <h2 class="right_title">企业资质</h2>
                <div class="zizhi_inner">
                    <div class="zizhi_box clearfix">
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi1.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>营业执照</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi2.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>增值电信业务</p>
                                    <p>经营许可证</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi3.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩易站</p>
                                    <p>系统V1.0</p>
                                    <p>著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi4.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>OpenBI大数据</p>
                                    <p>分析系统V1.0</p>
                                    <p>著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi5.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩UI渲染</p>
                                    <p>系统V1.0</p>
                                    <p>著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi6.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩内容</p>
                                    <p>管理系统v1.0</p>
                                    <p>著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi7.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩工作易</p>
                                    <p>应用系统V1.0</p>
                                    <p>著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi8.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>凤凰筑巢安卓端</p>
                                    <p>软件v1.0</p>
                                    <p>著作权证书</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'help/help');
        ?>
    </body>
</html>