<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>业务介绍-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/culture.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a class="main_hover"  href="/">首页</a>
            <span>&gt;</span>
            <a>关于我们</a>
            <span>&gt;</span>
            <a>企业文化</a>
        </div>
        <!--帮助中心-->
        <div class="l_main conwidth clearfix">
            <!--左侧内容-->
            <div class="l_left ">
                <h3 class="main_bg_light">关于我们<span>About us</span></h3>
                <ul>
                    <li class=""><a href="/about/company.html"><i class="icon-gsjianjie"></i>公司简介</a></li>                    
                    <li class="active"><a href="/about/culture.html"><i class="icon-qiyewenhua"></i>企业文化</a></li>
                    <li class=""><a href="/about/business.html"><i class="icon-chanpinjieshao"></i>业务介绍</a></li>
                    <li class=""><a href="/about/qualification.html"><i class="icon-zizhi"></i>企业资质</a></li>
                    <li class=""><a href="/about/ad.html"><i class="icon-fengcai"></i>公司环境</a></li>
                    <li class=""><a href="/about/join.html"><i class="icon-join"></i>加入我们</a></li>
                    <li class=""><a href="/about/legal.html"><i class="icon-falv"></i>法律声明</a></li>
                    <li class=""><a href="/about/contact.html"><i class="icon-lianxiwomen"></i>联系我们</a></li>
                </ul>
            </div>
            <!--右侧内容-->
            <div class="l_right">
                <h2 class="right_title">企业文化</h2>
                <p>我们想成为为一个与众不同的人，创新是我们的思维方式，技术研发是我们的根骨，专业化的服务是我们的血肉，我们站在巨人的肩膀上，只望比巨人看的更远。</p>
                <div class="culture_box clearfix">
                    <div class="culture_ele">
                        <i class="icon-hexin main_light"></i>
                        <p>企业核心</p>
                        <p>创新与服务</p>
                    </div>
                    <div class="culture_ele culture2">
                        <i class="icon-qiyequn main_light"></i>
                        <p>企业精神</p>
                        <p>专业、务实、高效、创新</p>
                    </div>
                    <div class="culture_ele">
                        <i class="icon-jinghua main_light"></i>
                        <p>企业思想</p>
                        <p>用信息带动企业发展，用技术推动时代创新</p>
                    </div>
                </div>
                <p>
                    公司倡导“专业、务实、高效、创新”的企业精神，具有良好的内部机制、优良的工作环境以及良好的激励机制，吸引了一批年轻的、有学识的、具有实干精神的人才。
                    高素质、高水平、高效率的人才是在当今激烈的市场竞争中立于不败之地的保障。
                    我们坚持用一颗感恩的心回馈客户，以客户为中心，用我们的专业水平、优质服务、合理价格为客户的成功添砖加瓦。自公司创办以来，得到了广大客户的充分认可，我们将一如既往的为客户提供最优质的服务。
                </p>
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'help/help');
        ?>
    </body>
</html>