<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>业务介绍-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/summary.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a>关于我们</a>
            <span>&gt;</span>
            <a>公司简介</a>
        </div>
        <!--帮助中心-->
        <div class="l_main conwidth clearfix">
            <!--左侧内容-->
            <div class="l_left ">
                <h3 class="main_bg_light">关于我们<span>About us</span></h3>
                <ul>
                    <li class="active"><a href="/about/company.html">公司简介</a></li>                    
                    <li class=""><a href="/about/culture.html">企业文化</a></li>
                    <li class=""><a href="/about/business.html">业务介绍</a></li>
                    <li class=""><a href="/about/qualification.html">企业资质</a></li>
                    <li class=""><a href="/about/ad.html">公司环境</a></li>
                    <li class=""><a href="/about/join.html">加入我们</a></li>
                    <li class=" "><a href="/about/legal.html">法律声明</a></li>
                    <li class=""><a href="/about/contact.html">联系我们</a></li>
                </ul>
            </div>
            <!--右侧内容-->
            <div class="l_right">
                <h2 class="right_title">公司简介</h2>
                <p>
                    凤凰筑巢是郑州神恩信息技术有限公司开发的主要项目。郑州神恩信息技术有限公司是河南省鑫山实业发展有限公司的子公司，位于郑州市凤凰城内，是一家拥有国家双软认证、以Web OS应用开发、销售为主的互联网公司。
                </p>
                <p>
                    河南省鑫山实业发展有限公司创建于1995年，是以商贸家居流通为核心、以文化产业为平台、以广告业为途径、以电子商务发展为辅助、以物业、物流
                    业为支撑的民营集团性企业，公司员工千余人，注册资金5亿元人民币，公司净资产近百亿元。
                </p>
                <p>
                    凤凰城是鑫山实业的核心产业之一，营业面积达40余万平方米，经营数十个建材家居业种，拥有商户4000余家、停车位1800多个，占据了河南省建材
                    家居半数以上的市场份额。同时，城内配有图书馆、企业收藏馆、商务办公室、设计师创客空间、智能家居样板间等，并辅以金融、保险、工商、税务、邮
                    政、信息、物流等综合服务配套设施。
                </p>
                <p>
                    神恩视创新与服务为企业之根本，倡导专业、务实、高效、创新的企业精神。规范的内部机制、优良的工作环境以及广阔的发展空间，吸引了一批年轻、
                    有学识、有实干精神的人才。
                </p>
                <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_summary.jpg') ?>" alt="">
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'help/help');
        ?> 
    </body>
</html>