<!--合作伙伴-->
<div class="partner_link">
    <div class="conwidth">
        <dl class="partner">
            <dt class="fl">合作伙伴：</dt>
            <dd class="fr">
                <span><img class="gray" src="../../Images/test/test_news_img.jpg"></span>
                <span><img class="gray" src="../../Images/test/test_banner1.jpg"></span>
                <span><img class="gray" src="../../Images/test/test_brand_ad.jpg"></span>
            </dd>
        </dl>
        <dl class="link">
            <dt class="fl">友情链接：</dt>
            <dd class="fr main_hover">
                <a href="">马可波罗</a><span>|</span>
                <a href="">慧聪网</a><span>|</span>
                <a href="">中国供应商</a><span>|</span>
                <a href="">中国建材网</a><span>|</span>
                <a href="">价格网</a><span>|</span>
                <a href="">食品网</a><span>|</span>
                <a href="">际通宝</a><span>|</span>
                <a href="">环球贸易网</a><span>|</span>
                <a href="">八方资源网</a><span>|</span>
                <a href="">马可波罗</a><span>|</span>
                <a href="">慧聪网</a><span>|</span>
                <a href="">中国供应商</a><span>|</span>
                <a href="">中国建材网</a><span>|</span>
                <a href="">价格网</a><span>|</span>
                <a href="">食品网</a><span>|</span>
                <a href="">际通宝</a><span>|</span>
                <a href="">环球贸易网</a><span>|</span>
                <a href="">八方资源网</a><span>|</span>
                <a href="">马可波罗</a><span>|</span>
                <a href="">慧聪网</a><span>|</span>
                <a href="">中国供应商</a><span>|</span>
                <a href="">中国建材网</a><span>|</span>
                <a href="">价格网</a><span>|</span>
                <a href="">食品网</a><span>|</span>
                <a href="">际通宝</a><span>|</span>
                <a href="">环球贸易网</a><span>|</span>
                <a href="">八方资源网</a><span>|</span>
                <a href="">马可波罗</a><span>|</span>
                <a href="">慧聪网</a><span>|</span>
                <a href="">中国供应商</a><span>|</span>
                <a href="">中国建材网</a><span>|</span>
                <a href="">价格网</a><span>|</span>
                <a href="">食品网</a><span>|</span>
                <a href="">际通宝</a><span>|</span>
                <a href="">环球贸易网</a><span>|</span>
                <a href="">八方资源网</a><span>|</span>
                <a href="">马可波罗</a><span>|</span>
                <a href="">慧聪网</a><span>|</span>
                <a href="">中国供应商</a><span>|</span>
                <a href="">中国建材网</a><span>|</span>
                <a href="">价格网</a><span>|</span>
                <a href="">食品网</a><span>|</span>
                <a href="">际通宝</a><span>|</span>
                <a href="">环球贸易网</a><span>|</span>
                <a href="">八方资源网</a><span>|</span>
                <a href="">更多</a>
            </dd>
        </dl>
    </div>
</div>
<!--底部导航-->
<div class="footer">
    <div class="footer_nav_box conwidth clearfix">
        <dl class="footer_nav main_hover">
            <dt>新手课堂</dt>
            <dd>
                <a href="">购物指南</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">配送方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover">
            <dt>新手课堂</dt>
            <dd>
                <a href="">购物指南</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">配送方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover">
            <dt>新手课堂</dt>
            <dd>
                <a href="">购物指南</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">配送方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover">
            <dt>新手课堂</dt>
            <dd>
                <a href="">购物指南</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">配送方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover no_mr">
            <dt>新手课堂</dt>
            <dd>
                <a href="">购物指南</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">配送方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
            <dd>
                <a href="">支付方式</a>
            </dd>
        </dl>
    </div>
</div>
<!--版权-->
<div class="copy_box">
    <div class="copy_box_inner conwidth">
        <div class="links">
            <a href="">世界工厂网大全</a><span>|</span>
            <a href="">供应商专区</a><span>|</span>
            <a href="">运营商专区</a><span>|</span>
            <a href="">推广服务</a><span>|</span>
            <a href="">代理商专区</a><span>|</span>
            <a href="">帮助中心</a><span>|</span>
            <a href="">问题反馈</a>
        </div>
        <div class="links copy_list">
            增值电信业务经营许可证：豫 B2-20140060|网络文化经营许可证：豫网文【2015】1103-002 号|出版物经营许可证：新出发 zzgx 零字第 0003 号|广播电视节目制作经营许可证：（豫）字第
            00236 号
        </div>
        <p class="links copy_list">
            Copyright 2008-2016 GongChang.com All Rights Reserved 豫ICP备11020782号-15- 23.77ms
        </p>
        <div class="cert">
            <span><img src="../../Images/mall/sprite/icon_cert_img_0.jpg" alt=""/></span>
            <span><img src="../../Images/mall/sprite/icon_cert_img_1.jpg" alt=""/></span>
            <span><img src="../../Images/mall/sprite/icon_cert_img_2.jpg" alt=""/></span>
            <span><img src="../../Images/mall/sprite/icon_cert_img_3.jpg" alt=""/></span>
            <span><img src="../../Images/mall/sprite/icon_cert_img_4.jpg" alt=""/></span>
            <span><img src="../../Images/mall/sprite/icon_cert_img_5.jpg" alt=""/></span>
        </div>
    </div>
</div>