<?php Qs::Ds('商城数据源/商城数据', 'site'); ?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>忘记密码-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/login.css')); ?>
    </head>
    <body>
        <div class="wrap">
            <div class="wrap_inner">
                <!--logo-->
                <div class="logo_register">
                    <div class="icon_logo fl">
                        <a href="<?php echo 'http://'. \Cntysoft\RT_SYS_SITE_NAME ?>">
                            <img src="<?php Qs::Sys('loadImage', 'login/icon/icon_logo_fff.png') ?>" alt="凤凰筑巢LOGO">
                        </a>
                    </div>
                    <h3 class="fl">采购商</h3>
                    <a href="register.html" class="register_a fr">还没有筑巢账号？30秒注册</a>
                </div>
                <div class="login_box">
                    <div class="login_header">
                        <h4 class="login_title">忘记密码</h4>
                        <div class="login_form check_form">
                            <form action="">
                                <div class="login_form_input">
                                    <input class="form_text" type="text" name="user" id="phone" fh-type="phone" placeholder="请输入注册时使用的手机号" required>
                                    <div class="input_code clearfix">
                                        <input class="fl code" type="text" name="code" autocomplete="off"  fh-type="imgCode" id="imgCode" placeholder="图片验证码" required>
                                        <a class="icode_image" >
                                            <img alt="图片验证码" title="看不清换一张" src="" id="codeImg">
                                            <i class="icon-update" id="changeCodeImg"></i>
                                        </a>
                                    </div>
                                </div>
                                <!--提交-->
                                <input class="submit_btn main_bg_light" type="submit" value="找回密码" id="submit_first"/>
                            </form>
                        </div>
                        <div class="login_form reset_form hide">
                            <form action="">
                                <div class="login_form_input">
                                    <input class="fl code" type="text" fh-type="phoneAuthCode" id="phoneAuthCode" autocomplete="off" placeholder="请输入短信验证码" required>
                                    <input class="form_text" type="password" name="user" fh-type="password" id="password" placeholder="请输入6-15位字母、数字、符号的新密码">
                                    <input class="form_text" type="password" name="user" fh-type="password" id="password2" placeholder="请再次输入新密码">
                                </div>
                                <!--提交-->
                                <input class="submit_btn main_bg_light" type="submit" id="submit_second" value="确认"/>
                            </form>
                        </div>
                        <!--成功-->
                        <div class="login_form tc success hide">
                            <i class="icon-duihaoyuanquan main_light"></i>
                            <p>新密码设置成功，请您牢记新密码</p>
                            <!--返回首页-->
                            <a class="main_border_light return_btn mainbg_hover_light" href="/login.html">返回登陆页</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--版权 begin-->
        <?php Qs::Label('静态类/登陆注册网站底部');Qs::Sys('loadRequireJs', 'buyer/forget'); ?>
    </body>
</html>