<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/标准内容模型', 'AC');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="description" content="<?php Qs::DsField('AC', 'intro') ?>">
        <meta name="keywords" content="<?php Qs::DsField('AC', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('mall/style.css', 'reference/style.css', 'reference/referencedetail.css', 'college/collegeinfo.css','layer','layer.ext.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--导航-->
        <div class="head main_bg_light">
            <div class="head_box conwidth1100 clearfix">
                <a class="logo_img fl" href="/">
                    <img src="<?php Qs::Sys('loadImage', 'reference/test_logo_white.png') ?>">
                    <span><em>|</em>老板内参</span>
                </a>
                <ul class="fr clearfix">
                    <?php
                    $nodeIdentifier = Qs::DsField('AC', 'nodeIdentifier', true);
                    $sign1 = $nodeIdentifier == 'laobanneican' ? 'main_bg' : '';
                    $sign2 = $nodeIdentifier == 'jiancaiqiwen' ? 'main_bg' : '';
                    $sign3 = $nodeIdentifier == 'shendujiexi' ? 'main_bg' : '';
                    $sign4 = $nodeIdentifier == 'zhongbangtuijian' ? 'main_bg' : '';
                    echo '<li><a class=" ' . $sign1 . ' mainbg_hover" href="/category/laobanneican.html">首页</a></li>
                    <li><a class=" ' . $sign2 . ' mainbg_hover" href="/category/jiancaiqiwen/1.html">建材奇闻</a></li>
                    <li><a class=" ' . $sign3 . ' mainbg_hover" href="/category/shendujiexi/1.html">深度解析</a></li>
                    <li><a class=" ' . $sign4 . ' mainbg_hover" href="/category/zhongbangtuijian/1.html">重磅推荐</a></li>';
                    ?>                    
                </ul>
            </div>
        </div>

        <!--内容-->
        <div class="content conwidth1100">

            <!--列表内容-->
            <div class="news_wrap clearfix">
                <!--站点指示-->
                <div class="site">
                    <a href="/category/laobanneican.html">老板内参</a>
                    <?php
                    if ($nodeIdentifier != 'laobanneican') {
                       echo '<span>&gt;</span>
                    <a href="/category/' . $nodeIdentifier . '/1.html"> ' . Qs::DsField('AC', 'nodeText', true) . '</a>';
                    }
                    ?>                    
                    <span>&gt;</span>
                    <a> <?php Qs::DsField('AC', 'title') ?></a>
                </div>
                <div class="left_section fl">
                    <div class=" article_list  clearfix">
                        <div class="article">
                            <h1><a ><?php Qs::DsField('AC', 'title') ?></a></h1>
                            <div class="article_title clearfix">
                                <div class="article_date fl">
                                    <em>发表于<b><?php echo date('Y-m-d', QS::DsField('AC', 'inputTime', true)) ?></b></em>
                                </div>
                                <div class="article_num fr">
                                    <span>阅读量：<b><?php Qs::DsField('AC', 'hits') ?></b></span>
                                    <div class="article_share bdsharebuttonbox">
                                        <i class="icon-fenxiang"></i>
                                        <a href="#" class="bds_more" data-cmd="more">分享</a>
                                    </div>

                                </div>
                            </div>
                            <div class="article_summary" article="<?php Qs::DsField('AC', 'id') ?>">
                                <div class="summary_inner" style="min-height: 600px"><?php Qs::DsField('AC', 'content') ?>
                                    <!--出处-->
                                    <div class="article_from">
                                        <span class="statement">以上内容为原创作品，已获作者独家授权，转载者请注明出处。</span>
                                    </div>
                                </div>
                                <!--上一篇下一篇-->
                                <div class="up_down">
                                    <div>
                                        上一篇：<?php
                                        $prev = Qs::DsField('AC', 'prev', true);
                                        if ($prev) {
                                           $pretitle = iconv_substr($prev[1], 0, 18, 'UTF-8');
                                           echo '<a href="' . $prev[0] . '" class="main_hover">' . $pretitle . '</a>';
                                        } else {
                                           echo '木有了';
                                        }
                                        ?>
                                    </div>
                                    <div>
                                        下一篇：<?php
                                        $next = Qs::DsField('AC', 'next', true);
                                        if ($next) {
                                           $nexttitle = iconv_substr($next[1], 0, 18, 'UTF-8');
                                           echo '<a href="' . $next[0] . '" class="main_hover">' . $nexttitle . '</a>';
                                        } else {
                                           echo '正在更新中，请等待~';
                                        }
                                        ?>
                                    </div>
                                </div>
                                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'ChangyanComment')) ?>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="right_section fr">
                    <div class="infomation">
                        <h1>热点资讯</h1>
                        <ul>
                            <?php
                            Qs::Label('文章/老板内参', array('renderTpl'      => 'Pc_HotArticle', 'nodeIdentifier' => array(
                                  'laobanneican', 'jiancaiqiwen', 'shendujiexi', 'zhongbangtuijian'
                               ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 6, 'enablePage'     => false, 'listSubNode'    => true))
                            ?>
                        </ul>
                    </div>
                    <div class="erweima">
                        <div id="weixin_code"></div>
                        <span>扫一扫用手机浏览</span>
                    </div>
                    <div class="erweima">
                        <h1>微信扫码关注凤凰筑巢</h1>
                        <img src="/Statics/Skins/Pc/Images/icon_erweima_big.jpg">
                    </div>
                </div>
            </div>
        </div>
        <script>window._bd_share_config = {
              "common" : {
                 "bdSnsKey" : {},
                 "bdText" : "",
                 "bdMini" : "2",
                 "bdPic" : "",
                 "bdStyle" : "0",
                 "bdSize" : "16"
              }, "share" : {}
           };
           with (document)
              0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>

        <?php Qs::Sys('loadRequireJs', 'reference/referencedetail') ?>  
        <?php Qs::Label('静态类/网站底部');
        ?>
    </body>
</html>
