<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>老板内参-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('reference/style.css', 'slick.css', 'reference/referenceindex.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--导航-->
        <div class="head main_bg_light">
            <div class="head_box conwidth1100 clearfix">
                <a class="logo_img fl" href="/">
                    <img src="<?php Qs::Sys('loadImage', 'reference/test_logo_white.png') ?>">
                    <span><em>|</em>老板内参</span>
                </a>
                <ul class="fr clearfix">
                    <li><a class="mainbg_hover" href="/category/laobanneican.html">首页</a></li>
                    <li><a class="mainbg_hover" href="/category/jiancaiqiwen/1.html">建材奇闻</a></li>
                    <li><a class="mainbg_hover" href="/category/shendujiexi/1.html">深度解析</a></li>
                    <li><a class="mainbg_hover" href="/category/zhongbangtuijian/1.html">重磅推荐</a></li>
                </ul>
            </div>
        </div>

        <!--banner -->
        <div class="banner conwidth1100">
            <!--            <div class="banner_box">
                            <div class="item "><a href=""><img src="../../Images/test/test_banner1.jpg"></a></div>
                            <div class="item "><a href=""><img src="../../Images/test/test_company_new3.jpg"></a></div>
                        </div>
                        左右按钮
                        <div class="prev_btn banner_btn "><i class="icon-jiantou7"></i></div>
                        <div class="next_btn banner_btn "><i class="icon-jiantou6"></i></div>-->
        </div>
        <!--内容-->
        <div class="content conwidth1100">
            <!--行业资讯-->
            <ul class="trade_news clearfix">
                <?php
                Qs::Label('文章/老板内参', array('renderTpl'      => 'Pc_NewArticle', 'nodeIdentifier' => array(
                      'laobanneican', 'jiancaiqiwen', 'shendujiexi', 'zhongbangtuijian'
                   ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 3, 'enablePage'     => false, 'listSubNode'    => true))
                ?>
            </ul>
            <!--列表-->
            <div class="news_wrap clearfix">
                <div class="left_section fl">
                    <?php
                    Qs::Label('文章/老板内参', array('renderTpl'      => 'Pc_DefaultList', 'nodeIdentifier' => array(
                          'laobanneican', 'jiancaiqiwen', 'shendujiexi', 'zhongbangtuijian'
                       ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 5, 'enablePage'     => true, 'listSubNode'    => true))
                    ?>
                </div>
                <div class="right_section fr">
                    <div class="infomation">
                        <h1>热点资讯</h1>
                        <ul>
                            <?php
                            Qs::Label('文章/老板内参', array('renderTpl'      => 'Pc_HotArticle', 'nodeIdentifier' => array(
                                  'laobanneican', 'jiancaiqiwen', 'shendujiexi', 'zhongbangtuijian'
                               ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 6, 'enablePage'     => false, 'listSubNode'    => true))
                            ?>
                        </ul>
                    </div>
                    <div class="erweima">
                        <h1>微信扫码关注凤凰筑巢</h1>
                        <img src="/Statics/Skins/Pc/Images/icon_erweima.png">
                    </div>
                </div>
            </div>
        </div>
        <script>window._bd_share_config = {
              "common" : {
                 "bdSnsKey" : {},
                 "bdText" : "",
                 "bdMini" : "2",
                 "bdPic" : "",
                 "bdStyle" : "0",
                 "bdSize" : "16"
              }, "share" : {}
           };
           with (document)
              0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
        <?php Qs::Sys('loadRequireJs', 'reference/referenceindex') ?>
    </body>
</html>