<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('内容数据源/标准内容模型', 'AC');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>筑巢商学院内容-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">  
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <?php Qs::Sys('loadCss', array('college/style.css', 'college/collegeinfo.css', 'swiper.min.css')) ?>
    </head>
    <body>
        <!--返回，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--返回-->
            <div class="header_back_box fl">
                <a class="header_back" href="javascript:history.back();"><i class="icon-fanhuijian"></i></a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc"><?php Qs::DsField('AC', 'title') ?>-筑巢商学院</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="/category/zhuchaoschool.html">首页</a></li>
                    <li><a href="/category/kechengzhongxin/1.html">课程中心</a></li>
                    <li><a href="/category/dianshangzixun/1.html">电商资讯</a></li>
                    <li><a href="/category/jingdiananli/1.html">经典案例</a></li>
                </ul>
            </div>
        </div>
        <!--内容详情-->
        <div class="main_content">
            <div class="content_title">
                <h3><?php Qs::DsField('AC', 'title') ?></h3>

                <div class="writer_info">
                    <span><?php Qs::DsField('AC', 'author') ?></span>
                    <span class="date"><?php echo date('Y.m.d', QS::DsField('AC', 'inputTime', true)) ?></span>
                    <span>阅读量：<i><?php Qs::DsField('AC', 'hits') ?></i></span>
                </div>
            </div>
            <div class="module_content">
                <?php Qs::DsField('AC', 'content') ?>
                <div class="prev_next">
                    <p><em>上一篇：</em><?php
                        $prev = Qs::DsField('AC', 'prev', true);
                        if ($prev) {
                           $prevtitle = iconv_strlen($prev[1]) > 15 ? iconv_substr($prev[1], 0, 15) . '...' : $prev[1];
                           echo '<a style="color: #333;" href="' . $prev[0] . '">' . $prevtitle . '</a>';
                        } else {
                           echo '木有了';
                        }
                        ?>
                    </p>
                    <p><em>下一篇：</em><?php
                        $next = Qs::DsField('AC', 'next', true);
                        if ($next) {
                           $nexttitle = iconv_strlen($next[1]) > 15 ? iconv_substr($next[1], 0, 15) . '...' : $next[1];
                           echo '<a style="color: #333;" href="' . $next[0] . '">' . $nexttitle . '</a>';
                        } else {
                           echo '正在更新中，请等待~';
                        }
                        ?></p>
                </div>
            </div>
            <div class="relevant_box">
                <h3 class="relevant_title"><a href="/category/zhuchaoschool.html">相关推荐</a></h3>
                <ul class="relevant_list_box">
                    <?php
                    Qs::Label('文章/电商宝典', array('renderTpl'      => 'Mobile_RecommendArticle', 'nodeIdentifier' => array(
                          'zhuchaoschool'
                       ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 8, 'enablePage'     => false, 'listSubNode'    => true))
                    ?>
                </ul>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'college/collegeindex') ?>
    </body>
</html>