<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>电子学院首页</title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <meta name="description" content="凤凰筑巢-建材家居行业_市场_搜建材行业的所有信息就去凤凰筑巢网-家具、建材、装修、装修攻略、效果图!">
        <meta name="Keywords" content="凤凰筑巢,网上商城,家具,壁纸,壁灯,建材,攻略,建材攻略,建材价格,效果图,装修攻略,窗帘,壁画,装修流程">
        <link rel="stylesheet" href="../../Css/college/style.css"/>
        <link rel="stylesheet" href="../../Css/swiper.min.css"/>
        <link rel="stylesheet" href="../../Css/college/collegecenter.css"/>
    </head>
    <body>
        <!--返回，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--返回-->
            <div class="header_back_box fl">
                <a class="header_back" href="javascript:history.back();"><i class="icon-fanhuijian"></i></a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">电子学院</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="../college/collegeindex.html">首页</a></li>
                    <li><a href="../college/collegecenter.html">课程中心</a></li>
                    <li><a href="">电商资讯</a></li>
                    <li><a href="">精彩案例</a></li>
                </ul>
            </div>
        </div>
        <!--筛选-->
        <div class="choose_box">
            <dl class="choose_list clearfix">
                <dt class="choose_key fl">商铺基础建设</dt>
                <dd class="choose_value fl">
                    <div class="choose_value_info">
                        <a class="main_bg_light">商铺注册</a>
                        <a>开通商铺</a>
                        <a>资质认证</a>
                        <a>上架产品</a>
                    </div>
                </dd>
            </dl>
            <dl class="choose_list clearfix">
                <dt class="choose_key fl">商铺日常管理</dt>
                <dd class="choose_value fl">
                    <div class="choose_value_info">
                        <a>商铺装修</a>
                        <a>商品上下架</a>
                        <a>在线交易</a>
                        <a>营销工具</a>
                    </div>
                </dd>
            </dl>
        </div>
        <div class="class_item">
            <h3 class="class_title text_ellipsis main_hover"><a href="">世界工厂网云站</a></h3>

            <div class="writer_info clearfix">
                <div class="fl">
                    <span>发表时间：2015-12-26</span>
                    <span class="writer">作者：lqq</span>
                </div>
                <span class="look fr"><i class="icon-yan"></i>1111</span>
            </div>
            <div class="class_img">
                <a href=""> <img src="../../Images/test/test_pro_img.jpg" alt=""/></a>
            </div>
            <p class="class_text">
                一、什么是世界工厂网云站 云站：为您提供最强的建站服务、内容建设和效果监控。 通过云站的各项设
                置，开放的各种自定义装修功能，使网站更精美，创建出独立的企业官网；并提供……
            </p>

            <div class="user_action tr clearfix">
                <a class="study_btn fl main_bg">立即学习</a>
                <span>235人已学</span>
            </div>
        </div>
        <div class="class_item">
            <h3 class="class_title text_ellipsis main_hover"><a href="">世界工厂网云站</a></h3>

            <div class="writer_info clearfix">
                <div class="fl">
                    <span>发表时间：2015-12-26</span>
                    <span class="writer">作者：lqq</span>
                </div>
                <span class="look fr"><i class="icon-yan"></i>1111</span>
            </div>
            <div class="class_img">
                <a href=""> <img src="../../Images/test/test_pro_img.jpg" alt=""/></a>
            </div>
            <p class="class_text">
                一、什么是世界工厂网云站 云站：为您提供最强的建站服务、内容建设和效果监控。 通过云站的各项设
                置，开放的各种自定义装修功能，使网站更精美，创建出独立的企业官网；并提供……
            </p>

            <div class="user_action tr clearfix">
                <a class="study_btn fl main_bg">立即学习</a>
                <span>235人已学</span>
            </div>
        </div>
        <div class="class_item">
            <h3 class="class_title text_ellipsis main_hover"><a href="">世界工厂网云站</a></h3>

            <div class="writer_info clearfix">
                <div class="fl">
                    <span>发表时间：2015-12-26</span>
                    <span class="writer">作者：lqq</span>
                </div>
                <span class="look fr"><i class="icon-yan"></i>1111</span>
            </div>
            <div class="class_img">
                <a href=""> <img src="../../Images/test/test_pro_img.jpg" alt=""/></a>
            </div>
            <p class="class_text">
                一、什么是世界工厂网云站 云站：为您提供最强的建站服务、内容建设和效果监控。 通过云站的各项设
                置，开放的各种自定义装修功能，使网站更精美，创建出独立的企业官网；并提供……
            </p>

            <div class="user_action tr clearfix">
                <a class="study_btn fl main_bg">立即学习</a>
                <span>235人已学</span>
            </div>
        </div>
        <div class="class_item">
            <h3 class="class_title text_ellipsis main_hover"><a href="">世界工厂网云站</a></h3>

            <div class="writer_info clearfix">
                <div class="fl">
                    <span>发表时间：2015-12-26</span>
                    <span class="writer">作者：lqq</span>
                </div>
                <span class="look fr"><i class="icon-yan"></i>1111</span>
            </div>
            <div class="class_img">
                <a href=""> <img src="../../Images/test/test_pro_img.jpg" alt=""/></a>
            </div>
            <p class="class_text">
                一、什么是世界工厂网云站 云站：为您提供最强的建站服务、内容建设和效果监控。 通过云站的各项设
                置，开放的各种自定义装修功能，使网站更精美，创建出独立的企业官网；并提供……
            </p>

            <div class="user_action tr clearfix">
                <a class="study_btn fl main_bg">立即学习</a>
                <span>235人已学</span>
            </div>
        </div>
        <script data-main="../../Js/requireenter" id="require" app="college/collegeindex"
        src="../../Js/lib/require.js"></script>
    </body>
</html>