<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('栏目数据源/栏目SEO', 'category');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>筑巢商学院列表-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">  
        <meta name="description" content="<?php Qs::DsField('category', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('category', 'keyword') ?>">
        <?php Qs::Sys('loadCss', array('college/style.css', 'college/collegecenter.css', 'swiper.min.css')) ?>
    </head>
    <body>
        <!--返回，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--返回-->
            <div class="header_back_box fl">
                <a class="header_back" href="javascript:history.back();"><i class="icon-fanhuijian"></i></a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">筑巢商学院</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="/category/zhuchaoschool.html">首页</a></li>
                    <li><a href="/category/kechengzhongxin/1.html">课程中心</a></li>
                    <li><a href="/category/dianshangzixun/1.html">电商资讯</a></li>
                    <li><a href="/category/jingdiananli/1.html">经典案例</a></li>
                </ul>
            </div>
        </div>
        <!--筛选-->
        <?php
        Qs::Label('文章/电商宝典', array('renderTpl'      => 'Mobile_DefaultChoose', 'nodeIdentifier' => array(
              'kechengzhongxin'
        )));
        Qs::Label('文章/电商宝典', array('renderTpl' => 'Mobile_DefaultList', 'nodeIdentifier' => array(), 'titleLength' => 28, 'introLength' => 20, 'outputNum' => 4, 'enablePage' => false, 'listSubNode' => true));
        Qs::Sys('loadRequireJs', 'college/collegelist')
        ?>     
        <div class="copy">
				<p>增值电信业务经营许可证：豫 B2-20160047<br/>
					 &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME)*1000, 2) . 'ms'; ?></p>
		  </div>
    </body>
</html>