<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>电子学院首页</title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <meta name="description" content="凤凰筑巢-建材家居行业_市场_搜建材行业的所有信息就去凤凰筑巢网-家具、建材、装修、装修攻略、效果图!">
        <meta name="Keywords" content="凤凰筑巢,网上商城,家具,壁纸,壁灯,建材,攻略,建材攻略,建材价格,效果图,装修攻略,窗帘,壁画,装修流程">
        <link rel="stylesheet" href="../../Css/college/style.css"/>
        <link rel="stylesheet" href="../../Css/swiper.min.css"/>
        <link rel="stylesheet" href="../../Css/college/collegeindex.css"/>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <a href="../mall/index.html">
                    <span class="icon_logo">
                        <img src="../../Images/icon/icon_logo.png" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">电子学院</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="../college/collegeindex.html">首页</a></li>
                    <li><a href="../college/collegecenter.html">课程中心</a></li>
                    <li><a href="">电商资讯</a></li>
                    <li><a href="">精彩案例</a></li>
                </ul>
            </div>
        </div>
        <!--一列广告滑动-->
        <div class="module_ad3 module_ad clearfix  swiper-container">
            <div class="swiper-wrapper">
                <div class="module_ad_list swiper-slide">
                    <a href="">
                        <div class="module_ad_img">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                </div>
                <div class="module_ad_list swiper-slide">
                    <a href="">
                        <div class="module_ad_img">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="swiper-pagination"></div>
        </div>
        <!--商铺基础建设-->
        <div class="new_box">
            <h3 class="new_title"><a href="">商铺基础建设</a></h3>
            <div class="new_item">
                <a href="../reference/referenceinfo.html">
                    <div class="new_img">
                        <div class="new_table">
                            <img src="../../Images/test/test_pro_img.jpg" alt="">
                        </div>
                    </div>
                    <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

                    <p class="writer_info clearfix">
                        <span class="writer fl">神恩信息</span>
                        <span class="fl">2015-01-06</span>
                    </p>
                    <span class="look">浏览（123）</span>
                </a>
            </div>

            <div class="new_item no_img">
                <a href="../reference/referenceinfo.html">
                    <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

                    <p class="writer_info clearfix">
                        <span class="writer fl">神恩信息</span>
                        <span class="fl">2015-01-06</span>
                    </p>
                    <span class="look">浏览（123）</span>
                </a>
            </div>
        </div>
        <!--日常管理-->
        <div class="new_box">
            <h3 class="new_title"><a href="">日常管理</a></h3>
            <div class="new_item">
                <a href="../reference/referenceinfo.html">
                    <div class="new_img">
                        <div class="new_table">
                            <img src="../../Images/test/test_pro_img.jpg" alt="">
                        </div>
                    </div>
                    <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

                    <p class="writer_info clearfix">
                        <span class="writer fl">神恩信息</span>
                        <span class="fl">2015-01-06</span>
                    </p>
                    <span class="look">浏览（123）</span>
                </a>
            </div>
        </div>
        <!--营销推广-->
        <div class="new_box">
            <h3 class="new_title"><a href="">营销推广</a></h3>
            <div class="new_item">
                <a href="../reference/referenceinfo.html">
                    <div class="new_img">
                        <div class="new_table">
                            <img src="../../Images/test/test_pro_img.jpg" alt="">
                        </div>
                    </div>
                    <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

                    <p class="writer_info clearfix">
                        <span class="writer fl">神恩信息</span>
                        <span class="fl">2015-01-06</span>
                    </p>
                    <span class="look">浏览（123）</span>
                </a>
            </div>
        </div>
        <!--课程安排-->
        <div class="class_list">
            <h3 class="new_title"><a href="">课程安排</a></h3>
            <div class="class_list_box clearfix">
                <div class="new_item">
                    <a href="../reference/referenceinfo.html">
                        <div class="new_img">
                            <div class="new_table">
                                <img src="../../Images/test/test_pro_img.jpg" alt="">
                            </div>
                        </div>
                        <h4 class="list_title text_ellipsis">PBA使用了UCloud UHost用用的</h4>
                        <p class="new_text text_ellipsis">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>
                    </a>
                </div>
                <div class="new_item">
                    <a href="../reference/referenceinfo.html">
                        <div class="new_img">
                            <div class="new_table">
                                <img src="../../Images/test/test_pro_img.jpg" alt="">
                            </div>
                        </div>
                        <h4 class="list_title text_ellipsis">PBA使用了UCloud UHost用用的</h4>
                        <p class="new_text text_ellipsis">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>
                    </a>
                </div>
                <div class="new_item">
                    <a href="../reference/referenceinfo.html">
                        <div class="new_img">
                            <div class="new_table">
                                <img src="../../Images/test/test_pro_img.jpg" alt="">
                            </div>
                        </div>
                        <h4 class="list_title text_ellipsis">PBA使用了UCloud UHost用用的</h4>
                        <p class="new_text text_ellipsis">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>
                    </a>
                </div>
                <div class="new_item">
                    <a href="../reference/referenceinfo.html">
                        <div class="new_img">
                            <div class="new_table">
                                <img src="../../Images/test/test_pro_img.jpg" alt="">
                            </div>
                        </div>
                        <h4 class="list_title text_ellipsis">PBA使用了UCloud UHost用用的</h4>
                        <p class="new_text text_ellipsis">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>
                    </a>
                </div>
            </div>
        </div>
        <script data-main="../../Js/requireenter" id="require" app="college/collegeindex"
        src="../../Js/lib/require.js"></script>
    </body>
</html>