<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>电子学院首页-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">  
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <?php Qs::Sys('loadCss', array('college/style.css', 'college/collegeindex.css', 'swiper.min.css')) ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">电子学院</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a href="/category/zhuchaoschool.html">首页</a></li>
                    <li><a href="/category/kechengzhongxin/1.html">课程中心</a></li>
                    <li><a href="/category/dianshangzixun/1.html">电商资讯</a></li>
                    <li><a href="/category/jingdiananli/1.html">经典案例</a></li>
                </ul>
            </div>
        </div>
        <!--一列广告滑动-->
        <div class="module_ad3 module_ad clearfix  swiper-container">
            <div class="swiper-wrapper">
                <div class="module_ad_list swiper-slide">
                    <a >
                        <div class="module_ad_img">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                </div>
                <div class="module_ad_list swiper-slide">
                    <a >
                        <div class="module_ad_img">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="swiper-pagination"></div>
        </div>
        <!--商铺基础建设-->
        <div class="new_box">
            <h3 class="new_title"><a href="/category/shangpujichujianshe/1.html">商铺基础建设</a></h3>
            <?php
            Qs::Label('文章/电商宝典', array('renderTpl'      => 'Mobile_IndexArticle', 'nodeIdentifier' => array(
                  'shangpujichujianshe', 'shangjiachanpin', 'kaitongdianpu', 'zhuceshangpu'
               ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 3, 'enablePage'     => false, 'listSubNode'    => true))
            ?>     
        </div>
        <!--日常管理-->
        <div class="new_box">
            <h3 class="new_title"><a href="/category/richangguanli/1.html">日常管理</a></h3>
            <?php
            Qs::Label('文章/电商宝典', array('renderTpl'      => 'Mobile_IndexArticle', 'nodeIdentifier' => array(
                  'richangguanli', 'richangxiajiachanpin', 'richangshangjiachanpin', 'dianpushezhi'
               ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 3, 'enablePage'     => false, 'listSubNode'    => true))
            ?>
        </div>
        <!--营销推广-->
        <div class="new_box">
            <h3 class="new_title"><a href="/category/yingxiaotuiguang/1.html">营销推广</a></h3>
            <?php
            Qs::Label('文章/电商宝典', array('renderTpl'      => 'Mobile_IndexArticle', 'nodeIdentifier' => array(
                  'yingxiaotuiguang', 'shehuihuayingxiao', 'huodongyingxiao', 'pinpaiguanli', 'yingxiaoseo'
               ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 5, 'enablePage'     => false, 'listSubNode'    => true))
            ?>
        </div>
        <!--课程安排-->
        <div class="class_list">
            <h3 class="new_title"><a href="/category/kechengzhongxin/1.html">课程安排</a></h3>
            <div class="class_list_box clearfix">
                <?php
                Qs::Label('文章/电商宝典', array('renderTpl'      => 'Mobile_IndexRecomentArticle', 'nodeIdentifier' => array(
                      'kechengzhongxin'
                   ), 'titleLength'    => 28, 'introLength'    => 20, 'outputNum'      => 4, 'enablePage'     => false, 'listSubNode'    => true))
                ?>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'college/collegeindex') ?>      
    </body>
</html>