<?php
$routeInfo = $this->getRouteInfo();
$cls1 = $cls2 = $cls3 = $cls4 = $cls5 = $cls6 = $cls7 = $cls8 = $cls9 = $cls10 = $cls11 = $cls12 = $cls13 = '';
switch($routeInfo['action']){
   case 'account':
      $cls1 = 'main_bg_light';
      break;
   case 'company':
      $cls2 = 'main_bg_light';
      break;
   case 'accountsafe':
      $cls3 = 'main_bg_light';
      break;
   case 'addproduct':
      $cls4 = 'main_bg_light';
      break;
   case 'index':
      if('Product' == $routeInfo['controller']){
         $cls5 = 'main_bg_light';
      }
      break;
   case 'inquiry':
      $query = $this->di->get('request')->getQuery();
      if(isset($query['status'])){
         if(1 == $query['status']){
            $cls7 = 'main_bg_light';
         }else if(2 == $query['status']){
            $cls8 = 'main_bg_light';
         }
      }else{
         $cls6 = 'main_bg_light';
      }
      break;
   case 'addnews':
   case 'newslist':
      $cls9 = 'main_bg_light';
      break;
   case 'joblist':
   case 'addjob':
      $cls10 = 'main_bg_light';
      break;
   case 'setting':
      $cls11 = 'main_bg_light';
      break;
   case 'businessmsg':
      $cls12 = 'main_bg_light';
      break;
   case 'sysmsg':
      $cls13 = 'main_bg_light';
      break;
}

$out = '<div class="items_wrap fl">
         <dl>
             <dt><i class="icon-caozuochenggong"></i>账户中心</dt>
             <dd><a class="mainbg_hover_light '.$cls1.'" href="/account/index.html">基本信息</a></dd>
             <dd><a class="mainbg_hover_light '.$cls2.'" href="/account/company.html">企业信息</a></dd>
             <dd><a class="mainbg_hover_light '.$cls3.'" href="/account/safe.html">修改密码</a></dd>
         </dl>
         <dl>
             <dt><i class="icon-caozuochenggong"></i>产品中心</dt>
             <dd><a class="mainbg_hover_light '.$cls4.'" href="/product/addproduct/1.html">发布产品</a></dd>
             <dd><a class="mainbg_hover_light '.$cls5.'" href="/product/1.html">产品管理</a></dd>
         </dl>
         <dl>
             <dt><i class="icon-caozuochenggong"></i>询价单</dt>
             <dd><a class="mainbg_hover_light '.$cls6.'" href="/inquiry/1.html">全部</a></dd>
             <dd><a class="mainbg_hover_light '.$cls7.'" href="/inquiry/1.html?status=1">未回复</a></dd>
             <dd><a class="mainbg_hover_light '.$cls8.'" href="/inquiry/1.html?status=2">已回复</a></dd>
         </dl>
         <dl>
             <dt><i class="icon-caozuochenggong"></i>店铺设置</dt>
             <dd><a class="mainbg_hover_light '.$cls9.'" href="/site/news/1.html">店铺新闻</a></dd>
             <dd><a class="mainbg_hover_light '.$cls10.'" href="/site/job/1.html">招聘</a></dd>
             <dd><a class="mainbg_hover_light '.$cls11.'" href="/site/setting.html">店铺设置</a></dd>
         </dl>
         <dl>
             <dt><i class="icon-caozuochenggong"></i>消息</dt>
             <dd><a class="mainbg_hover_light '.$cls12.'" href="/account/businessmsg/1.html">服务消息</a></dd>
             <dd><a class="mainbg_hover_light '.$cls13.'" href="/account/sysmsg/1.html">系统消息</a></dd>
         </dl>
     </div>';

echo $out;