<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('CP', 'name') ?>－产品列表-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('dianpu/style.css', 'dianpu/prolist.css', 'swiper.min.css')) ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--商品分类列表导航-->
        <?php Qs::Label('企业网站/产品', array('renderTpl' => 'Mobile_ProductList', 'outputNum' => 6, 'enablePage' => false)); ?>
        <div id='contact'><span><a class='phone'></a></span></div>
        <div id="contactWrap">
            <div class="wrap">
                <div class="bg"></div>
                <div class="detail">
                    <h2><i class="icon-lianxiwomen main"></i>联系我们</h2>

                    <p>电&nbsp;&nbsp;&nbsp;话：<a href="tel:<?php Qs::DsField('CP', 'contact') ?>"><?php Qs::DsField('CP', 'contact') ?></a></p>

                    <p>联系人：<?php Qs::DsField('CP', 'providername') ?></p>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'dianpu/prolist')
        ?> 
    </body>
</html>