<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('商品数据源/商品信息', 'goods');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('goods', 'name') ?>－产品详情-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('swiper.min.css', 'company/style.css', 'company/proinfo.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--内容-->
        <div class="l_main">
            <!--产品展示-->
            <?php Qs::Label('企业网站/产品', array('renderTpl' => 'Mobile_GoodsContent')) ?>
        </div>
        <!--版权所有-->
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'company/proinfo')
        ?> 
    </body>
</html>