<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业设置', 'CS');
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('CP', 'name') ?>－关于我们-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/aboutus.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--内容-->
        <div class="l_main">
            <!--关于我们-->
            <div class="module_title about_us">
                <i class="icon-aboutus"></i><span>关于我们</span>
            </div>
            <!--公司介绍-->
            <div class="module_title">
                <i class="icon-gsjianjie"></i><span>企业介绍</span>
            </div>
            <div class="about_content hide">
                <?php Qs::DsField('CS', 1)
                ?>
            </div>
            <!--企业文化-->
            <div class="module_title">
                <i class="icon-qiyewenhua"></i><span>企业文化</span>
            </div>
            <div class="about_content hide">
                <?php Qs::DsField('CS', 2)
                ?>
            </div>
            <!--企业资质-->
            <div class="module_title">
                <i class="icon-zizhi"></i><span>企业资质</span>
            </div>
            <div class="about_content hide">
                <?php Qs::DsField('CS', 3)
                ?>
            </div>
            <!--联系我们-->
            <div class="module_title">
                <i class="icon-lianxiwomen"></i><span>联系我们</span>
            </div>
            <div class="about_content hide">
                <?php Qs::DsField('CS', 4)
                ?>
            </div>

        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'company/aboutus')
        ?> 
    </body>
</html>