<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业设置', 'CS');
Qs::Ds('内容数据源/企业信息', 'CP');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('CP', 'name') ?>－关于我们-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('CP', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('CP', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/employ.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--内容-->
        <div class="l_main">
            <!--公司介绍-->
            <div class="module_title">
                <i></i><span>关于我们</span><i></i>
            </div>
            <div class="employ_ele intro">
                <h3><i></i>企业介绍</h3>
                <div class="employ_detail hide">
                    <?php Qs::DsField('CS', 1)
                    ?>
                </div>
            </div>
            <div class="employ_ele culture">
                <h3><i></i>企业文化</h3>
                <div class="employ_detail hide">
                    <?php Qs::DsField('CS', 2)
                    ?>
                </div>
            </div>
            <div class="employ_ele zizhi">
                <h3><i></i>企业资质</h3>
                <div class="employ_detail hide">
                    <?php Qs::DsField('CS', 3)
                    ?>
                </div>
            </div>
            <div class="employ_ele connect">
                <h3><i></i>联系我们</h3>
                <div class="employ_detail hide">
                    <?php Qs::DsField('CS', 4)
                    ?>
                </div>
            </div>
        </div>
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
        <?php Qs::Sys('loadRequireJs', 'company/aboutus') ?> 
    </body>
</html>