<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业设置', 'CS');
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('CP', 'name') ?>－招聘中心-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('dianpu/style.css', 'dianpu/aboutus.css')) ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::DsField('CP', 'logo') ?>" alt="<?php Qs::DsField('CP', 'name') ?>"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc"><?php Qs::DsField('CP', 'name') ?></h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <ul class="top_nav_list">
                    <li><a  href="/">首页</a></li>
                    <li><a  href="/about.html?intro">企业介绍</a></li>
                    <li><a  href="/about.html?culture">企业文化</a></li>
                    <li><a href="/about.html?zizhi">企业资质</a></li>
                    <li ><a href="/about.html?connect">联系我们</a></li>
                </ul>
            </div>
        </div>

        <!--列表-->
        <div class="items_box hide intro">
            <!--标题-->
            <div class="module_title">
                <a ><i class="icon-gsjianjie"></i>企业介绍</a>
            </div>
            <div class="items_info">
                <?php Qs::DsField('CS', 1)
                ?>
            </div>
        </div>
        <!--列表-->
        <div class="items_box hide culture">
            <!--标题-->
            <div class="module_title">
                <a ><i class="icon-qiyewenhua"></i>企业文化</a>
            </div>
            <div class="items_info">
                <?php Qs::DsField('CS', 2)
                ?>
            </div>
        </div>
        <!--列表-->
        <div class="items_box hide qiyezizhi">
            <!--标题-->
            <div class="module_title">
                <a ><i class="icon-zizhi"></i>企业资质</a>
            </div>
            <div class="items_info ">
                <?php Qs::DsField('CS', 3)
                ?>
            </div>
        </div>
        <!--列表-->
        <div class="items_box hide connect">
            <!--标题-->
            <div class="module_title">
                <a ><i class="icon-lianxiwomen"></i>联系我们</a>
            </div>
            <div class="items_info contact_us">
                <?php Qs::DsField('CS', 4)
                ?>
            </div>
        </div>
        <div id='contact'><span><a class='phone'></a></span></div>
        <div id="contactWrap">
            <div class="wrap">
                <div class="bg"></div>
                <div class="detail">
                    <h2><i class="icon-lianxiwomen main"></i>联系我们</h2>

                    <p>电&nbsp;&nbsp;&nbsp;话：<a href="tel:15639707313">15639707313</a></p>

                    <p>联系人：张大海</p>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'dianpu/aboutus')
        ?> 
    </body>
</html>