<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业标准内容模型', 'AC');
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('dianpu/style.css', 'dianpu/join.css')) ?>
    </head>
    <body>
        <!--返回，搜索,名称-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--投送简历-->
        <div class="itemsbox">
            <h2><?php Qs::DsField('AC', 'title') ?></h2>
            <ul class="join_li clearfix">
                <li>部门：<?php Qs::DsField('AC', 'department') ?></li>
                <li>人数：<?php Qs::DsField('AC', 'number') ?>人</li>
                <li class="line">截止时间：<?php echo date('Y-m-d', QS::DsField('AC', 'endTime', true)) ?></li>
                <li class="line">电话：<?php Qs::DsField('AC', 'tel') ?></li>
            </ul>
            <p><?php Qs::DsField('AC', 'content') ?></p>
        </div>
        <div id='contact'><span><a class='phone'></a></span></div>
        <div id="contactWrap">
            <div class="wrap">
                <div class="bg"></div>
                <div class="detail">
                    <h2><i class="icon-lianxiwomen main"></i>联系我们</h2>
                    <p>电&nbsp;&nbsp;&nbsp;话：<a href="tel:<?php Qs::DsField('AC', 'tel') ?>"><?php Qs::DsField('AC', 'tel') ?></a></p>

                </div>
            </div>
        </div>
        <div id='contact'><span><a class='phone'></a></span></div>
        <div id="contactWrap">
            <div class="wrap">
                <div class="bg"></div>
                <div class="detail">
                    <h2><i class="icon-lianxiwomen main"></i>联系我们</h2>

                    <p>电&nbsp;&nbsp;&nbsp;话：<a href="tel:<?php Qs::DsField('CP', 'contact') ?>"><?php Qs::DsField('CP', 'contact') ?></a></p>

                    <p>联系人：<?php Qs::DsField('CP', 'providername') ?></p>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'dianpu/join')
        ?>
    </body>
</html>