<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业标准内容模型', 'AC');
Qs::Ds('内容数据源/企业信息', 'CP');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="description" content="<?php Qs::DsField('CP', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('CP', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/employ.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--内容-->
        <div class="l_main">
            <!--新闻动态-->
            <div class="module_title">
                <i></i><span><a href="/joinus.html">招聘中心</a></span><i></i>
            </div>
            <div class="employ_ele">
                <h3><i></i><?php Qs::DsField('AC', 'title') ?></h3>
                <div class="employ_detail">
                    <p>
                        任职部门：<?php Qs::DsField('AC', 'department') ?>
                    </p>
                    <p>
                        招聘人数：<?php Qs::DsField('AC', 'number') ?>
                    </p>
                    <p>
                        联系电话：<?php Qs::DsField('AC', 'tel') ?>
                    </p>  
                    <p>
                        截止时间：<?php echo date('Y-m-d', QS::DsField('AC', 'endTime', true)) ?>
                    </p>
                    <p>
                        <?php Qs::DsField('AC', 'content') ?>
                    </p><br>
                    <div class="prev_next">
                        <p><em>上一篇：</em><?php
                            $prev = Qs::DsField('AC', 'prev', true);
                            if ($prev) {
                               $pretitle = mb_substr($prev[1], 0, 13);
                               echo '<a href="' . $prev[0] . '">' . $pretitle . '</a>';
                            } else {
                               echo '木有了';
                            }
                            ?>
                        </p>
                        <p><em>下一篇：</em><?php
                            $next = Qs::DsField('AC', 'next', true);
                            if ($next) {
                               $nexttitle = mb_substr($next[1], 0, 13);
                               echo '<a href="' . $next[0] . '">' . $nexttitle . '</a>';
                            } else {
                               echo '正在更新中，请等待~';
                            }
                            ?></p>
                    </div>
                </div>

            </div>
        </div>
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
        <?php Qs::Sys('loadRequireJs', 'company/employdetail') ?>
    </body>
</html>