<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('CP', 'name') ?>－搜索-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/search.css')) ?>
    </head>
    <body>
        <!--头部-->
        <div class="header">
            <div class="header_left">
                <span class="icon-fenlei"></span>
            </div>
            <div class="header_title"><?php Qs::DsField('CP', 'name') ?></div>
        </div>
        <!--导航-->
        <div class="classify">
            <ul>
                <li><a href="/">首页</a></li>
                <li><a href="/productlist/1.html">产品中心</a></li>
                <li><a href="/newscenter.html">新闻中心</a></li>
                <li><a href="/caselist/1.html">成功案例</a></li>
                <li><a href="/joinus.html">招聘中心</a></li>
                <li><a href="/about.html">关于我们</a></li>
                <!--        <li><a href="connect.html">联系我们</a></li>
                        <li><a href="zizhi.html">企业资质</a></li>-->
            </ul>
        </div>
        <!--内容-->
        <div class="l_main">
            <div class="m_search">
                <input type="text" placeholder="请输入你要查找的产品" >
                <span><i class="icon-sousuo"></i></span>
            </div>
            <!--            <div class="search_detail">
                            <p><i class="icon-sousuo"></i>小白</p>
                <p><i class="icon-sousuo"></i>小白</p>
                <p><i class="icon-sousuo"></i>小白</p>
                <p><i class="icon-sousuo"></i>小白</p>
                <p><i class="icon-sousuo"></i>小白</p>
                <p><i class="icon-sousuo"></i>小白</p>
                <p><i class="icon-sousuo"></i>小白</p>
                <p><i class="icon-sousuo"></i>小白</p>
                <span class="main">清除历史记录</span>
                        </div>-->
        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'company/search')
        ?>
    </body>
</html>