<!DOCTYPE html><?php
Qs::Ds('内容数据源/企业标准内容模型', 'AC');
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('company/style.css', 'company/newsdetail.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--内容-->
        <div class="l_main">
            <div class="news_title">
                <h3><?php Qs::DsField('AC', 'title') ?></h3>
                <p class="clearfix">
                    <span>发表时间：<?php echo date('Y-m-d', QS::DsField('AC', 'inputTime', true)) ?></span>
                    <span>浏览：<?php Qs::DsField('AC', 'hits') ?></span>
                </p>
            </div>
            <div class="news_detail">
                <?php Qs::DsField('AC', 'content') ?><br/>
                <div class="prev_next">
                    <p><em>上一篇：</em><?php
                        $prev = Qs::DsField('AC', 'prev', true);
                        if ($prev) {
                           $pretitle = mb_substr($prev[1], 0, 13);
                           echo '<a href="' . $prev[0] . '">' . $pretitle . '</a>';
                        } else {
                           echo '木有了';
                        }
                        ?>
                    </p>
                    <p><em>下一篇：</em><?php
                        $next = Qs::DsField('AC', 'next', true);
                        if ($next) {
                           $nexttitle = mb_substr($next[1], 0, 13);
                           echo '<a href="' . $next[0] . '">' . $nexttitle . '</a>';
                        } else {
                           echo '正在更新中，请等待~';
                        }
                        ?></p>
                </div>
            </div>
            <?php
            Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
            Qs::Sys('loadRequireJs', 'company/newsdetail')
            ?>
        </div>
    </body>
</html>