<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/企业标准内容模型', 'AC');
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('dianpu/style.css', 'dianpu/newsdetail.css')) ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--内容详情-->
        <div class="main_content" newsid="<?php Qs::DsField('AC', 'id') ?>">
            <div class="content_title">
                <h3><?php Qs::DsField('AC', 'title') ?></h3>

                <div class="writer_info">
                    <span class="date">发表时间：<?php echo date('Y-m-d', QS::DsField('AC', 'inputTime', true)) ?></span>
                    <span>阅读量：<i><?php Qs::DsField('AC', 'hits') ?></i></span>
                </div>
            </div>
            <div class="module_content">
                <?php Qs::DsField('AC', 'content') ?><br/>
                <div class="up_down">
                    <div>
                        上一篇：<?php
                        $prev = Qs::DsField('AC', 'prev', true);
                        if ($prev) {
                           $pretitle = iconv_substr($prev[1], 0, 13, 'UTF-8');
                           echo '<a href="' . $prev[0] . '">' . $pretitle . '</a>';
                        } else {
                           echo '木有了';
                        }
                        ?>                    </div>
                    <div>
                        下一篇：<?php
                        $next = Qs::DsField('AC', 'next', true);
                        if ($next) {
                           $nexttitle = iconv_substr($next[1], 0, 13, 'UTF-8');
                           echo '<a href="' . $next[0] . '">' . $nexttitle . '</a>';
                        } else {
                           echo '正在更新中，请等待~';
                        }
                        ?>                    </div>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'dianpu/newsdetail')
        ?>
    </body>
</html>