<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/店铺设置', 'setting');
Qs::Ds('内容数据源/企业案例模型', 'case');
Qs::Ds('内容数据源/企业信息', 'CP');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('case', 'title'); ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('swiper.min.css', 'dianpu/style.css', 'dianpu/caseinfo.css')) ?>
    </head>
    <body>
        <!--返回，-->
        <div class="headbar w clearfix">
            <!--返回-->
            <div class="header_back_box fl">
                <a class="header_back" href="/caselist/1.html"><i class="icon-fanhuijian"></i></a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc"><span>1</span>/ <b></b></h2>
            </div>
        </div>
        <!--案例内容-->
        <div id="caseinfo" class="module_ad3 module_ad clearfix  swiper-container">
            <div class="swiper-wrapper">
                <?php
                $content = Qs::DsField('case', 'content', true);
                $out = '';
                foreach ($content as $value) {
                   $out .= '<div class="module_ad_list swiper-slide">
                    <a>
                        <div class="module_ad_img"
                             style="background: url(' . $value['src'] . '@365w_365h_1c_1e.src) no-repeat center  ;">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                     <h3 class="case_title">' . Qs::DsField('case', 'title', true) . '</h3>
                    <p class="case_text">' . $value['intro'] . '</p>
                </div>';
                }
                echo $out;
                ?>

            </div>
            <div class="swiper-pagination"></div>
        </div>
        <div id='contact'><span><a class='phone'></a></span></div>
        <div id="contactWrap">
            <div class="wrap">
                <div class="bg"></div>
                <div class="detail">
                    <h2><i class="icon-lianxiwomen main"></i>联系我们</h2>

                    <p>电&nbsp;&nbsp;&nbsp;话：<a href="tel:15639707313">15639707313</a></p>

                    <p>联系人：张大海</p>
                </div>
            </div>
        </div>
        <!--分享保存-->
        <?php
        Qs::Sys('loadRequireJs', 'dianpu/caseinfo')
        ?>
    </body>
</html>