<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
    <title>成功案例列表</title>
    <link rel="stylesheet" href="../../Css/company/style.css">
    <link rel="stylesheet" href="../../Css/company/caselist.css">
</head>
<body>
<!--头部-->
<?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
<!-- 内容-->
<div class="l_main" id="l_main">
    <div class="case">
        <div class="case_list">
            <a class="case_img" href="#"><img src="../../Images/test/test_company_zizhi.jpg"></a>
            <h2><a href="#">金水区凤凰城</a></h2>
            <div class="case_intro">
                <p>
                    <span>装修面积：<em>120</em>m<sup>2</sup></span>
                    <span>风格：<em>田园风格</em></span>
                </p>
                <p>
                    主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉
                </p>
            </div>
        </div>
        <div class="case_list">
            <a class="case_img" href="#"><img src="../../Images/test/test_company_zizhi.jpg"></a>
            <h2><a href="#">金水区凤凰城</a></h2>
            <div class="case_intro">
                <p>
                    <span>装修面积：<em>120</em>m<sup>2</sup></span>
                    <span>风格：<em>田园风格</em></span>
                </p>
                <p>
                    主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉
                </p>
            </div>
        </div>
        <div class="case_list">
            <a class="case_img" href="#"><img src="../../Images/test/test_company_zizhi.jpg"></a>
            <h2><a href="#">金水区凤凰城</a></h2>
            <div class="case_intro">
                <p>
                    <span>装修面积：<em>120</em>m<sup>2</sup></span>
                    <span>风格：<em>田园风格</em></span>
                </p>
                <p>
                    主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉
                </p>
            </div>
        </div>
        <div class="case_list">
            <a class="case_img" href="#"><img src="../../Images/test/test_company_zizhi.jpg"></a>
            <h2><a href="#">金水区凤凰城</a></h2>
            <div class="case_intro">
                <p>
                    <span>装修面积：<em>120</em>m<sup>2</sup></span>
                    <span>风格：<em>田园风格</em></span>
                </p>
                <p>
                    主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉
                </p>
            </div>
        </div>
        <div class="case_list">
            <a class="case_img" href="#"><img src="../../Images/test/test_company_zizhi.jpg"></a>
            <h2><a href="#">金水区凤凰城</a></h2>
            <div class="case_intro">
                <p>
                    <span>装修面积：<em>120</em>m<sup>2</sup></span>
                    <span>风格：<em>田园风格</em></span>
                </p>
                <p>
                    主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉主要做家装别墅，偶有涉及到工装，项目有天骄园，东亚逸品阁，偶有 预约
                    参观工哈远洋山水主要做家装，别墅，偶有涉
                </p>
            </div>
        </div>
    </div>
    <!--版权所有-->
    <div class="copyright">
        <p>辉煌世家</p>
        <p>技术支持：郑州神恩信息技术有限公司</p>
        <p>豫ICP备11020782号-15- 23.77ms</p>
    </div>
</div>
<script data-main="../../Js/requireenter" id="require" app="company/caselist" src="../../Js/lib/require.js"></script>
</body>
</html>