<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/店铺设置', 'setting');
Qs::Ds('内容数据源/企业案例模型', 'case');
Qs::Ds('内容数据源/企业信息', 'CP');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <title><?php Qs::DsField('case', 'title'); ?></title>
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('swiper.min.css', 'company/style.css', 'company/caseinfo.css')) ?>
    </head>
    <body>

        <!-- 内容-->
        <div class="l_main" id="l_main"  newsid="<?php Qs::DsField('case', 'id') ?>">
            <p class="goback"><i class="icon-fanhuijian"></i></p>
            <!--一列广告滑动-->
            <div class= "swiper-container">
                <div class="swiper-wrapper">
                    <?php
                    $content = Qs::DsField('case', 'content', true);
                    foreach ($content as $index => $value) {
                       echo '<div class="swiper-slide">
                        <img src="' . $value['src'] . '">
                    </div>';
                    }
                    ?>
                </div>
                <div class="swiper-pagination"></div>
            </div>
            <p class="case_num"><em>1</em>/<span><?php echo $index + 1; ?></span></p>
            <div class="case_intro">
                <h2><?php Qs::DsField('case', 'title'); ?></h2>
                <p><?php Qs::DsField('case', 'intro'); ?>
                </p>
            </div>
        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'company/caseinfo')
        ?>
    </body>
</html>