<!DOCTYPE html>
<?php
use App\Yunzhan\Content\Constant;
Qs::Ds('内容数据源/企业标准内容模型', 'CS', array('newsid' => Constant::INFO_INTRO_ID));
Qs::Ds('内容数据源/企业信息', 'CP');
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title><?php Qs::DsField('CP', 'name') ?>－首页-<?php Qs::DsField('CP', 'description') ?></title>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <meta name="description" content="<?php Qs::DsField('setting', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('setting', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('dianpu/style.css', 'swiper.min.css', 'dianpu/index.css')) ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <?php Qs::Label('云站/网站顶部', array('renderTpl' => 'Mobile_CompanyTop',)) ?>
        <!--一列广告滑动-->
        <div class="module_ad3 module_ad clearfix  swiper-container">
            <div class="swiper-wrapper">
                <?php
                $banners = QS::DsField('setting', 'banner', true);
                foreach ($banners as $banner) {
                   if (false === strpos($banner['image'], '@')) {
                      $image = $banner['image'] . '@640w_200h_1e_1c.src';
                   } else {
                      if (strpos($banner['image'], '.src')) {
                         $ret = explode('.src', $banner['image']);
                         $image = $ret[0] . '_200h' . '.src';
                      } else {
                         $image = $ret[0] . '_200h' . '.src';
                      }
                   }

                   $url = $banner['url'];
                   if ($url) {
                      echo '<div class="module_ad_list swiper-slide">
                    <a href="' . $url . '">
                        <div class="module_ad_img" style="background: url(' . $image . ') no-repeat">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                </div>';
                   } else {
                      echo '<div class="module_ad_list swiper-slide">
                        <div class="module_ad_img" style="background: url(' . $image . ') no-repeat">
                            <div class="module_ad_box"></div>
                        </div>
                </div>';
                   }
                }
                ?>
            </div>
            <div class="swiper-pagination"></div>
        </div>
        <!--公司介绍-->
        <div class="items_box">
            <!--标题-->
            <div class="module_title">
                <a href="/about.html"><i class="icon-gsjianjie"></i>公司介绍</a>
            </div>
            <div class="jianjie">
                <p>
                    <?php
                    $inrodata = Qs::DsField('CS', 'content', true);
                    echo iconv_substr(strip_tags($inrodata), 0, 74, 'UTF-8')
                    ?> <a href="/about.html" style="float: right">查看详情>></a></p>
                    <?php
                    $facade = Qs::DsField('setting', 'facade', true);
                    $facadeset = 0;
                    if (count($facade)) {
                       echo '<a href="/about.html"> <img src="' . $facade[0]['image'] . '@188w_116h_1e_1c.src" alt=""></a>';
                       $facadeset = 1;
                    }
                    if (iconv_strpos($inrodata, '<img')) {
                       $imgs = mb_split('data-original="', $inrodata);
                       $nowimgs = array_slice($imgs, 1, 3);
                       foreach ($nowimgs as $index => $value) {
                          if ($index == (1 - $facadeset)) {
                             echo '<img src="' . mb_split('"', $value)[0] . '@188w_116h_1e_1c.src" alt="">';
                             break;
                          }
                          echo'<img  src="' . mb_split('"', $value)[0] . '@188w_116h_1e_1c.src" alt="">';
                       }
                    }
                    ?>
            </div>
        </div>
        <!--产品展示-->
        <div class="items_box">
            <!--标题-->
            <div class="module_title">
                <a href="/productlist/1.html"><i class="icon-chanpin"></i>产品展示</a>
            </div>
            <?php Qs::Label('企业网站/产品', array('renderTpl' => 'Mobile_IndexProductList', 'outputNum' => 4, 'enablePage' => false)); ?>
        </div>
        <div id='contact'><span><a class='phone'></a></span></div>
        <div id="contactWrap">
            <div class="wrap">
                <div class="bg"></div>
                <div class="detail">
                    <h2><i class="icon-lianxiwomen main"></i>联系我们</h2>

                    <p>电&nbsp;&nbsp;&nbsp;话：<a href="tel:<?php Qs :: DsField('CP', 'contact') ?>"><?php Qs::DsField('CP', 'contact') ?></a></p>

                    <p>联系人：<?php Qs::DsField('CP', 'providername') ?></p>
                </div>
            </div>
        </div>
        <?php
        Qs::Label('云站/网站底部', array('renderTpl' => 'Mobile_CompanyBottom',));
        Qs::Sys('loadRequireJs', 'dianpu/index')
        ?>
    </body>
</html>
