<?php
$tree = $this->getGroupTree();
$groups = $tree->getChildren(0, 1, true);
$out = '<div class="group_list hide">';
$select1 = '<option value="0">全部分组</option>';
$select2 = '<option value="0">默认分组</option>';
$pro = '';
$result = $this->getProductGroupList();
$products = $result[0];
$total = $result[1];

if(count($groups)){
   foreach($groups as $group){
      $children = $tree->getChildren($group->getId(), 1, true);
      $select1.='<option value="'.$group->getId().'">'.$group->getName().'</option>';
      $select2.='<option value="'.$group->getId().'">'.$group->getName().'</option>';
      if(count($children)){
         foreach($children as $one){
            $select1.='<option value="'.$one->getId().'">&nbsp;&nbsp;&nbsp;'.$one->getName().'</option>';
            $select2.='<option value="'.$one->getId().'">&nbsp;&nbsp;&nbsp;'.$one->getName().'</option>';
         }
      }
   }
}
$allSelect = $select1;
$query = $this->getQuery();
if(isset($query['group']) && $query['group']){
   $group = $this->getGroup($query['group']);
   if($group){
      $allSelect = '<option value="'.$group->getId().'">'.$group->getName().'</option>' . $select1;
   }
}

if(count($products)){
   foreach($products as $product){
      $pgs = $product->getPgs();
      $groupName = '';
      if(count($pgs)){
         foreach($pgs as $pg){
            $group = $pg->getGroup();
            $groupName = $group->getName();
            break;
         }
      }

      $name = $product->getBrand() . ' '. $product->getTitle() . ' '. $product->getDescription();
      $number = $product->getNumber();
      $url = $this->getSiteProductUrl($number);
      $image = $this->getImageCdnUrl($product->getDefaultImage());
      
      $pro .= '<div class="list_items clearfix" fh-num="'.$number.'">
                <div class="list_name">
                    <span class="check" ><em style="display:none"><i></i></em></span>
                    <a href="'.$url.'" class="list_img" target="_blank"><img src="'.$image.'" alt="'.$name.'"/></a>
                    <h3><a href="'.$url.'" target="_blank">'.$name.'</a></h3>
                </div>
                <div class="list_group">'. $groupName .'</div>
                <div class="list_action">
               <select>';
      if($groupName){
         $pro.='<option value="'.$group->getId().'">'.$groupName.'</option>';
      }
      $pro .= $select2 . '</select></div></div>';
   }
}
$out .='<div class="search_select" style="margin-bottom:10px">
         <select>
            '.$allSelect.'
         </select>
     </div><div class="prolist_edit hide">
                <span class="check"><em><i></i></em>全选</span>
                <span>将选中的产品添加到</span>
                    <select>
                        '.$select2.'
                    </select>
            </div>
            <div class="list_title">
                <div class="list_name">产品</div>
                <div class="list_group">所属分组</div>
                <div class="list_action">操作</div>
            </div>'.$pro.'</div>';

$paging = $this->getPaging($total);
if($this->getParam('enablePage') && count($products) && $paging['total'] > 0){
   $out1 = '';
   $currentPage = $paging['current'];
   $cls = "";
   $out .= '<div class="page_list hide"><p>';
   if ($currentPage > 1) {
      $out.='<a href="'. $this->getPageUrl($currentPage - 1).'" class="prev_page">&lt; 上一页</a>';
   }else{
      $out.='<a class="prev_page">&lt; 上一页</a>';
   }
   if ($currentPage > 5) {
      $out.='<a href="'. $this->getPageUrl(1).'">1</a>... ';
      for ($i = ($currentPage - 2); $i <= $paging['total'] && $i <= $currentPage + 2; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a  class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
   } else {
      for ($i = 1; $i <= $paging['total'] && $i <= 6; $i++) {
         $cls = "";
         $nowPageUrl = 'href="'. $this->getPageUrl($i).'"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
      if ($paging['total'] > 6) {
         $out1 .='... ' . '<a href="'. $this->getPageUrl(7).'">7</a>';
      }
   }
   $out .= $out1;
   if ($paging['total'] > 0 && $currentPage != $paging['total']) {
      $out .= '<a href="'. $this->getPageUrl($currentPage + 1).'" class="next_page no_marginR" >下一页 &gt;</a>';
   }else{
      $out .= '<a class="next_page no_marginR" >下一页 &gt;</a>';
   }

   $out .= '</p></div>';
}

echo $out;




