<?php
$node = $this->getDefalutNode($this->getRouteNodeIdentifier());
$allIdents = $this->getSubNodeIds($node->getId());
$subindetifiers = array();
foreach ($allIdents as $indetifiers) {
   $subindetifiers[] = $indetifiers->getNodeIdentifier();
}
array_push($subindetifiers, $this->getRouteNodeIdentifier());
$out = '<div class="choose_box" ident="' . implode(',', $subindetifiers) . '"> ';
if ($node->getNodeIdentifier() == 'dianshangzixun' || $node->getNodeIdentifier() == 'jingdiananli') {
   echo $out . '</div>';
   return;
}
$indetifier = $this->invokeParams['nodeIdentifier'][0];
$node0 = $this->getNodeByNodeIndentifier($indetifier);
$subNodes = $this->getSubNode($node0->getId());
foreach ($subNodes as $value) {
   $cls = $node->getNodeIdentifier() == $value->getNodeIdentifier() ? 'main' : '';
   $href = $node->getNodeIdentifier() == $value->getNodeIdentifier() ? '' : 'href="/category/' . $value->getNodeIdentifier() . '/1.html"';
   $out .= '    <dl class="choose_list clearfix">                  
   <a ' . $href . ' ><dt class="choose_key fl ' . $cls . '">' . $value->getText() . '</dt></a>
                        <dd class="choose_value fl">
                            <div class="choose_value_info">';
   $subsubNodes = $this->getSubNodeIds($value->getId());
   foreach ($subsubNodes as $value2) {
      $cls = $node->getNodeIdentifier() == $value2->getNodeIdentifier() ? 'main_bg_light' : '';
      $href = $node->getNodeIdentifier() == $value2->getNodeIdentifier() ? '' : 'href="/category/' . $value2->getNodeIdentifier() . '/1.html"';
      $out.='<a class="' . $cls . '" ' . $href . '>' . $value2->getText() . '</a>';
   }
   $out.=' </div>
                        </dd>
                        </dl>';
}
$out .= '</div>';
echo $out;
