<?php
$indetifier = $this->invokeParams['nodeIdentifier'][0];
$node0 = $this->getNodeByNodeIndentifier($indetifier);
$subNodes = $this->getSubNodeIds($node0->getId());
$subindetifiers = array();
foreach ($subNodes as $value) {
   $subindetifiers[] = $value->getNodeIdentifier();
}
array_push($subindetifiers, $indetifier);
$this->invokeParams['nodeIdentifier'] = $subindetifiers;
$items = $this->execute();
$out = '';
foreach ($items as $index => $info) {
   $url = $this->getInfoUrl($info->getId());
   $out .= '<div class="module_ad_list swiper-slide">
                    <a href="' . $url . '">
                        <div class="module_ad_img" style="background: url(' . $this->getImgcdn($info->getDefaultPicUrl()[0], 320, 160) . '?_nosprite)">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                </div>';
}
echo $out;
?>

