<?php
$node0 = $this->getDefalutNode($this->getRouteNodeIdentifier());
$subNodes = $this->getSubNodeIds($node0->getId());
$subindetifiers = array();
foreach ($subNodes as $value) {
   $subindetifiers[] = $value->getNodeIdentifier();
}
array_push($subindetifiers, $node0->getNodeIdentifier());
$this->invokeParams['nodeIdentifier'] = $subindetifiers;
$infoList = $this->execute();
if (!$infoList) {
   echo "<script>window.location = '/'</script>";
   return false;
}
$items = is_array($infoList) ? $infoList[0] : $infoList;
$out = '';
$out1 = '';
foreach ($items as $index => $item) {
   $imgurl = '';
   $defpic = $item->getDefaultPicUrl()[0];
   $infourl = $this->getInfoUrl($item->getId());
   if ($defpic) {
      $imgurl = '<a href="' . $infourl . '"> <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImgcdn($defpic, 740, 404) . '" alt=""/></a>';
   }
   $out .='<div class="class_item">
                    <h3 class="class_title  main_hover"><a href="' . $infourl . '">' . $item->getTitle() . '</a></h3>
                    <div class="writer_info clearfix">
                        <div class="fl">
                            <span>发表时间：' . date('Y-m-d', $item->getInputTime()) . '</span>
                        </div>
                        <span class="look fr"><i class="icon-yan"></i>' . $item->getHits() . '</span>
                    </div>
                    <div class="class_info clearfix">
                    <div class="class_img fl">' . $imgurl . '                        
                    </div>
                    <div class="class_article fr">
                    <p class="class_text">' . $item->getIntro() . '
                    </p>
                    <div class="user_action tr clearfix">
                        <a class="study_btn fl main_bg" href="' . $infourl . '">立即阅读</a>
                        <span>' . $item->getHits() . '人已学</span>
                    </div>
                    </div>
                    </div>
                </div>';
}
$a = $this->getPaging($infoList[1]);
if ($this->getParam('enablePage') && $a['total'] > 1) {

   $currentPage = $a['current'];
   $pageOne = ''; //首页要加的类名
   $pageLast = '';  //未页要加的类名
   $pageFirstUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], 1) . '"';
   $pageLastUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], $a['total']) . '"';
   if ($currentPage == 1) {
      $pageOne = 'now_page';
      $pageFirstUrl = '#';
   }
   if ($currentPage == $a['total']) {
      $pageLast = 'now_page';
      $pageLastUrl = '';
   }
   $cls = "";
   $out .= ' <div class="page_list">
                        <p>';
   $out .='<a class="' . $pageOne . '" ' . $pageFirstUrl . '>首页</a>';
   if ($currentPage > 1) {
      $out.='<a href="' . $this->getPageUrl($a['nodeIdentifier'], $currentPage - 1) . '">&lt; 上一页</a>';
   }
   if ($currentPage > 5) {
      $out.='<a href="' . $this->getPageUrl($a['nodeIdentifier'], 1) . '">1</a>... ';
      for ($i = ($currentPage - 2); $i <= $a['total'] && $i <= $currentPage + 2; $i++) {
         $cls = "";
         $nowPageUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], $i) . '"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a  class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
   } else {
      for ($i = 1; $i <= $a['total'] && $i <= 6; $i++) {
         $cls = "";
         $nowPageUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], $i) . '"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
      if ($a['total'] > 6) {
         $out1 .='... ' . '<a href="' . $this->getPageUrl($a['nodeIdentifier'], 7) . '">7</a>';
      }
   }
   $out .= $out1;
   if ($a['total'] > 0 && $currentPage != $a['total']) {
      $out .= '<a href="' . $this->getPageUrl($a['nodeIdentifier'], $currentPage + 1) . '">下一页 &gt;</a>';
   }
   $out .= '<a class="' . $pageLast . '" ' . $pageLastUrl . '>尾页</a>';
   $out .= '</p>
                    </div>';
}

echo $out;
?>