<?php
$indetifier = $this->invokeParams['nodeIdentifier'][0];
$node0 = $this->getNodeByNodeIndentifier($indetifier);
$subNodes = $this->getSubNodeIds($node0->getId());
$subindetifiers = array();
foreach ($subNodes as $value) {
   $subindetifiers[] = $value->getNodeIdentifier();
}
array_push($subindetifiers, $indetifier);
$this->invokeParams['nodeIdentifier'] = $subindetifiers;
$items = $this->execute();
$out = $last = '';
foreach ($items as $index => $info) {
   $node = $this->getNode($info->getNodeId());
   $out .= ' <div class="class_li">
                        <div class="class_li_img">
                            <img src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-lazy="' . $this->getImgcdn($info->getDefaultPicUrl()[0], 261, 120) . '" alt=""/>
                        </div>
                        <h3 class="class_li_h3 text_ellipsis"><a href="' . $this->getInfoUrl($info->getId()) . '">[' . $node->getText() . ']' . $info->getTitle() . '</a></h3>
                        <p class="class_li_text">' . $info->getIntro() . '</p>
                        <a href="' . $this->getInfoUrl($info->getId()) . '" class="read_more main_bg_light">立即查看</a>
                    </div>';
}
echo $out;
