<?php
$node = $this->getDefalutNode($this->getIvokeNodeIdentifier());
$out = '<dt>' . $node->getText() . '</dt>';
$infolist = $this->execute();
foreach ($infolist as $info) {
	$detailinfo = $this->getDetail($info->getId());
	$url = '';
	if ($info->getCmodelId() == 2) {
		$url = ' href="' . $detailinfo[1]->getLinkUrl() . '" target="out"';
	} else if ($info->getCmodelId() == 1) {
		$url = ' href="' . $this->getInfoUrl($info->getId()) . '"';
	}
	$out .= '<dd>
                <a ' . $url . '>' . $info->getTitle() . '</a>
            </dd>';
}
echo $out;
