<?php
if ($this->getRouteNodeIdentifier() == 'laobanneican') {
   $out = '<ul class="new_box" ident="' . implode(',', $this->invokeParams['nodeIdentifier']) . '">';
   $infoList = $this->execute();
} else {
   $out = '<ul class="new_box" ident="' . $this->getRoute()['nodeIdentifier'] . '">';
   $infoList = $this->getArticleList();
}
if (!$infoList) {
   echo "<script>window.location = '/'</script>";
   return false;
}
$items = is_array($infoList) ? $infoList[0] : $infoList;
$out1 = ' <div class="module_ad3 module_ad clearfix  swiper-container"> <div class="swiper-wrapper">';
$node = $this->getDefalutNode($this->getRouteNodeIdentifier());
foreach ($items as $key => $value) {
   if ($key < 3) {
      $defpic = $value->getDefaultPicUrl()[0];
      $infourl = $this->getInfoUrl($value->getId());
      $out1.='<div class="module_ad_list swiper-slide">
                    <a href="' . $infourl . '">
                       <h2>'.$value->getTitle().'</h2>
                        <div class="module_ad_img swiper-lazy" data-background="' . $this->getImgcdn($defpic, 320, 160) . '" style="background-image:none;">
                            <div class="module_ad_box"></div>
                        </div>
                    </a>
                </div>';
   }
}
$out1.='</div>
            <div class="swiper-pagination"></div>
        </div>';
foreach ($items as $index => $item) {
   $imgcls = $imgurl = '';
   $defpic = $item->getDefaultPicUrl()[0];
   $infourl = $this->getInfoUrl($item->getId());
   if ($defpic) {
      $imgurl = '<div class="new_img">
                        <div class="new_table">
                            <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImgcdn($defpic, 110, 68) . '" alt="">
                        </div>
                    </div>';
   } else {
      $imgcls = 'class="no_img"';
   }
   $out .=' <li  ' . $imgcls . ' >
                <a href="' . $infourl . '">
                      ' . $imgurl . '
                    <p class="new_text">' . $item->getTitle() . '</p>
                    <p class="writer_info clearfix">
                        <span class="fl">' . date('Y-m-d', $item->getInputTime()) . '</span>
                    </p>
                    <span class="look">浏览（' . $item->getHits() . '）</span>
                </a>
            </li>';
}
$out.='</ul>';
echo $out1 . $out;
?>
