<?php
if ($this->getRouteNodeIdentifier() == 'laobanneican') {
   $items = $this->execute('hits desc');
} else {
   $items = $this->getArticleList('hits desc');
}
$out = $last = '';
foreach ($items as $index => $info) {
   if ($index == count($items) - 1) {
      $last = 'no_bb';
   }
   $out .= '<li class="clearfix ' . $last . '">
                    <a href="' . $this->getInfoUrl($info->getId()) . '"><img src="' . $this->getImgcdn($info->getDefaultPicUrl()[0], 60, 40) . '">
                       <p>' . $info->getTitle() . '</p></a>
                </li>';
}
echo $out;
