<?php
if ($this->getRouteNodeIdentifier() == 'laobanneican') {
   $items = $this->execute();
} else {
   $items = $this->getArticleList();
}
$out = '';
foreach ($items as $info) {
   $out .= '<li>
                    <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImgcdn($info->getDefaultPicUrl()[0], 360, 200) . '">
                    <a href="' . $this->getInfoUrl($info->getId()) . '">' . $info->getTitle() . '</a>
                </li>';
}
echo $out;
