<div class="header_top">
    <div class="conwidth clearfix">
        <div class="fl">
            欢迎来到凤凰筑巢！ <a class="login_btn main_hover">请登录</a> <a class="register_btn main_hover">注册</a>
        </div>
        <ul class="fr header_top_nav main_hover">
            <li><a href="">我的询价单</a></li>
            <li class="line"></li>
            <li><a href="">会员中心 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">我是 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">供应商专区</a></li>
            <li class="line"></li>
            <li><a href="">运营商专区</a></li>
            <li class="line"></li>
            <li><a href="">网站地图 <i class="icon-xiangxiajiantou"></i></a></li>
            <li class="line"></li>
            <li><a href="">帮助中心</a></li>
            <li class="line"></li>
            <li class="more_btn mainbg_hover"><a>关注我们 <i class="iicon-xiangxiajiantou"></i></a>

                <div class="pull_more main_bg">
                    <a href="">邀请好友</a>
                    <a href="">加入收藏</a>
                    <a href="">新浪微博</a>
                    <a href="">邀请好友</a>
                    <a href="">加入收藏</a>
                    <a href="">新浪微博</a>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--搜索-->
<div class="header_search">
    <div class="header_search_inner conwidth clearfix">
        <div class="icon_logo fl">
            <img src="../../Images/test/test_iocn_logo.png" alt="凤凰筑巢LOGO">
        </div>
        <div class="header_search_box fr clearfix">
            <div class="search_box">
                <input type="text" placeholder="搜索您的问题">
                <span class="search_button">
                    搜索
                </span>
            </div>
            <div class="search_right_btn noselect fr mainbd_hover">
                <a href="../cart/cart.html">
                    <span>联系客服</span>
                </a>
            </div>
            <div class="search_right_btn noselect fr mainbd_hover">
                <a href="../mall/index.html">
                    <span>返回商城首页</span>
                </a>
            </div>
        </div>
    </div>
</div>