<?php
$list = $this->getAddressList();
$out='';
if(count($list)){
   $out.='<div class="address_container clearfix">';
   foreach($list as $index => $address){
      $id = $address->getId();
      $username = $address->getUsername();
      $province = $this->getArea($address->getProvince());
      $city = $this->getArea($address->getCity());
      $district = $this->getArea($address->getDistrict());
      $addressInfo = $address->getAddress();
      $phone = $address->getPhone();
      $isDefault = $address->getIsDefault();
      $cls = $isDefault ? 'main_light' : '';
      $cls1 = '';
      if(2 == $index || 5 == $index){
         $cls1 = 'no_mr';
      }
      $out.='<div class="address_ele '.$cls1.'" fh-index="'.$id.'">
                <span class="address_border address_borderT"></span>
                <span class="address_border address_borderB"></span>
                <div class="address_title clearfix">
                    <div class="address_name fl">
                        <i class="icon-rentou3"></i>
                        '.$username.'
                    </div>
                    <div class="address_handle fr">';
      if(!$isDefault){
         $out.='<span class="defult_btn main_bg main_bg_light main_border_light">默认</span>';
      }            
      $out.='<span class="edit_btn">编辑</span>
                        <span class="iconfont del_btn">删除</span>
                    </div>
                </div>
                <div class="address_detail" style="text-align:left">
                    <i class="icon-dizhi"></i>
                    <p>'.$province.$city.$district.$addressInfo.'</p>
                </div>
                <div class="address_phone">
                    <i class="icon-shouji"></i>
                    '.$phone.'
                </div>
                <i class="icon-duihao1 right_logo '.$cls.'" ></i>
            </div>';
   }
   $out.='</div>';
}
echo $out;