<?php
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<div class="headbar w clearfix main_bg">
    <!--logo-->
    <div class="header_left fl">
        <a href="/">
            <span class="icon_logo">
                <img src="<?php Qs::DsField('CP', 'logo') ?>" alt="<?php Qs::DsField('CP', 'name') ?>"/>
            </span>
        </a>
    </div>
    <!--标题-->
    <div class="header_title">
        <h2 class=" tc"><?php Qs::DsField('CP', 'name') ?></h2>
    </div>
    <!--更多按钮-->
    <div class="header_right fr">
        <span class="more_icon"><i class="icon-xiala"></i></span>
    </div>
    <!--下拉列表-->
    <div class="top_nav_box hide">
        <ul class="top_nav_list">
            <li><a href="/">首页</a></li>
            <?php
            $bool = Qs::DsField('setting', 'product', true);
            if ($bool) {
               echo '<li><a href="/productlist/1.html">产品中心</a></li>';
            }
            $bool = Qs::DsField('setting', 'case', true);
            if ($bool) {
               echo '<li><a href="/caselist/1.html">成功案例</a></li>';
            }
            $bool = Qs::DsField('setting', 'news', true);
            if ($bool) {
               echo '<li><a href="/newscenter.html">新闻中心</a></li>';
            }
            $bool = Qs::DsField('setting', 'zhaopin', true);
            if ($bool) {
               echo '<li><a href="/joinus.html">招聘中心</a></li>';
            }
            $bool = Qs::DsField('setting', 'aboutus', true);
            if ($bool) {
               echo '<li><a href="/about.html">关于我们</a></li>';
            }
            ?> 
        </ul>
    </div>
</div>