<div class="header">
    <div class="header_left">
        <span class="icon-fenlei"></span>
    </div>
    <div class="header_title"><?php Qs::DsField('CP', 'name') ?></div>
    <div class="header_right">
        <a href="/search.html">
            <span class="icon-sousuo"></span>
        </a>
    </div>
</div>
<!--导航-->
<div class="classify">
    <ul>
        <li><a href="/">首页</a></li>
        <li><a href="/productlist/1.html">产品中心</a></li>
        <li><a href="/newscenter.html">新闻中心</a></li>
        <li><a href="/joinus.html">招聘中心</a></li>
        <li><a href="/about.html">关于我们</a></li>
        <!--        <li><a href="connect.html">联系我们</a></li>
                <li><a href="zizhi.html">企业资质</a></li>-->
    </ul>
</div>