<?php
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<div class="header">
    <div class="header_left">
        <span class="icon-fenlei"></span>
    </div>
    <div class="header_title"><?php Qs::DsField('CP', 'name') ?></div>
    <div class="header_right">
        <a href="/search.html">
            <span class="icon-sousuo"></span>
        </a>
    </div>
</div>
<!--导航-->
<div class="classify">
    <ul>
        <li><a href="/">首页</a></li>
        <?php
        $bool = Qs::DsField('setting', 'product', true);
        if ($bool) {
           echo '<li><a href="/productlist/1.html">产品中心</a></li>';
        }
        $bool = Qs::DsField('setting', 'case', true);
        if ($bool) {
           echo '<li><a href="/caselist/1.html">成功案例</a></li>';
        }
        $bool = Qs::DsField('setting', 'news', true);
        if ($bool) {
           echo '<li><a href="/newscenter.html">新闻中心</a></li>';
        }
        $bool = Qs::DsField('setting', 'zhaopin', true);
        if ($bool) {
           echo '<li><a href="/joinus.html">招聘中心</a></li>';
        }
        $bool = Qs::DsField('setting', 'aboutus', true);
        if ($bool) {
           echo '<li><a href="/about.html">关于我们</a></li>';
        }
        ?>
    </ul>
</div>