<div class="l_top ">
    <div class="conwidth clearfix">
        <div class="l_top_left">
            <a href="/">
                <img src="<?php Qs::DsField('CP', 'logo') ?>" alt="<?php Qs::DsField('CP', 'name') ?>">
                <span><?php Qs::DsField('CP', 'name') ?></span>
            </a>
        </div>
        <div class="l_top_right icon-erweima">
            <div class="erweima_box">
                <div class="qrcode" id="qrcode1" company="<?php Qs::DsField('CP', 'company') ?>" >
                </div>
                <p>扫一扫，用手机查看</p>
            </div>
        </div>
    </div>
</div>
<!--导航和搜索-->
<div class="l_nav ">
    <div class="conwidth">
        <ul class="clearfix ">
            <li class="mainbd_hover active_hover "><a href="/">首页</a></li>
            <li class="mainbd_hover active_hover"><a href="/productlist/1.html">产品中心</a></li>
            <li class="mainbd_hover active_hover">
                <a href="/newscenter.html">新闻中心</a>
                <div class="nav_box">
                    <ul>
                        <li class="active_hover"><a href="/companynews.html">企业新闻</a></li>
                        <li class="active_hover"><a href="/industrynews.html">行业新闻</a></li>
                    </ul>
                </div>
            </li>
            <li class="mainbd_hover active_hover"><a href="/joinus.html">招聘中心</a></li>
            <li class="mainbd_hover active_hover">
                <a href="/about.html">关于我们</a>
                <div class="nav_box">
                    <ul>
                        <li class="active_hover"><a href="/about.html?intro">企业介绍</a></li>
                        <li class="active_hover"><a href="/about.html?culture">企业文化</a></li>
                        <li class="active_hover"><a href="/about.html?zizhi">企业资质</a></li>
                        <li class="active_hover"><a href="/about.html?connect">联系我们</a></li>
                    </ul>
                </div>
            </li>
        </ul>
        <div class="search">
            <input type="text">
            <i class="icon-sousuo"></i>
        </div>
    </div>
</div>