<?php
Qs::Ds('内容数据源/店铺设置', 'setting');
?>
<div class="l_top ">
    <div class="conwidth clearfix">
        <div class="l_top_left">
            <a href="/">
                <img src="<?php Qs::DsField('CP', 'logo') ?>" alt="<?php Qs::DsField('CP', 'name') ?>">
                <span><?php Qs::DsField('CP', 'name') ?></span>
            </a>
        </div>
        <span class="phone"><i class="icon-lianxiwomen"></i><?php Qs::DsField('CP', 'contact') ?></span>
        <div class="l_top_right icon-erweima">
            <div class="erweima_box">
                <div class="qrcode" id="qrcode1" company="<?php Qs::DsField('CP', 'company') ?>" >
                </div>
                <p>扫一扫，用手机查看</p>
            </div>
        </div>
    </div>
</div>
<!--导航和搜索-->
<div class="l_nav ">
    <div class="conwidth">
        <ul class="clearfix ">
            <li class="mainbd_hover active_hover "><a href="/">首页</a></li>
            <?php
            $bool = Qs::DsField('setting', 'product', true);
            if ($bool) {
               echo '<li class="mainbd_hover active_hover product_nav"><a href="/productlist/1.html">产品中心</a></li>';
            }
            $bool = Qs::DsField('setting', 'case', true);
            if ($bool) {
               echo '<li class="mainbd_hover active_hover case_nav"><a href="/caselist/1.html">案例中心</a></li>';
            }
            $bool = Qs::DsField('setting', 'news', true);
            if ($bool) {
               echo '<li class="mainbd_hover active_hover news_nav">
                <a href="/newscenter.html">新闻中心</a>
                <div class="nav_box">
                    <ul>
                        <li class="active_hover"><a href="/companynews.html">企业新闻</a></li>
                        <li class="active_hover"><a href="/industrynews.html">行业新闻</a></li>
                    </ul>
                </div>
            </li>';
            }
            $bool = Qs::DsField('setting', 'zhaopin', true);
            if ($bool) {
               echo '<li class="mainbd_hover active_hover zhaopin_nav"><a href="/joinus.html">招聘中心</a></li>';
            }
            $bool = Qs::DsField('setting', 'aboutus', true);
            if ($bool) {
               echo '<li class="mainbd_hover active_hover aboutus_nav">
                <a href="/about.html">关于我们</a>
                <div class="nav_box">
                    <ul>
                        <li class="active_hover"><a href="/about.html?intro">企业介绍</a></li>
                        <li class="active_hover"><a href="/about.html?culture">企业文化</a></li>
                        <li class="active_hover"><a href="/about.html?zizhi">企业资质</a></li>
                        <li class="active_hover"><a href="/about.html?connect">联系我们</a></li>
                    </ul>
                </div>
            </li>';
            }
            ?>
        </ul>
        <div class="search">
            <input type="text">
            <i class="icon-sousuo"></i>
        </div>
    </div>
</div>