<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>产品列表-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
		  <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
		  <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
		  <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
		  <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('mall/style.css', 'mall/prolist.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_MallTop')) ?>
        <div class="header_search">
            <div class="header_search_inner conwidth clearfix">
                <div class="icon_logo fl">
                    <img src="../../Images/test/test_iocn_logo.png" alt="凤凰筑巢LOGO">
                </div>
                <div class="header_search_box fr clearfix">
                    <div class="search_box">
                        <input type="text" placeholder="圣诞节跨年幸福购">
                        <span class="search_button">
                            搜索
                        </span>
                    </div>
                    <div class="search_right_btn noselect fr mainbd_hover">
                        <a href="../cart/cart.html">
                            <i class="icon-bianji main"></i>
                            <span>发布询价单</span>
                        </a>
                    </div>
                    <div class="search_right_btn noselect fr mainbd_hover">
                        <a href="../cart/cart.html">
                            <i class="icon-bianji main"></i>
                            <span>发布询价单</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('商品类/商城头部', array('renderTpl' => 'ProductTop',)) ?>
        <div class="content conwidth">
            <!--站点指示-->
            <?php Qs::Label('商品类/分类商品列表', array('renderTpl' => 'ClassifyNav')); ?>
            <div class="pro_list clearfix">
                <!--左侧-->
                <div class="left_side fl">
                    <!--筛选条件-->

                    <?php Qs::Label('商品类/分类商品列表', array('renderTpl' => 'CategoryQuery', 'outputNum' => 10)); ?>
                    <!--产品展示-->
                    <div class="pro_show">
                        <?php Qs::Label('商品类/分类商品列表', array('renderTpl' => 'ProductList', 'outputNum' => 10, 'enablePage' => true)); ?>
                        <!--分页-->
                    </div>
                </div>
                <!--右侧-->
                <div class="right_side fr">
                    <?php Qs::Label('商品类/分类商品列表', array('renderTpl' => 'ProductHot', 'outputNum' => 4)); ?>                    
                </div>
            </div>

        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'MallDefault',)) ?>
        <?php Qs::Sys('loadRequireJs', 'mall/prolist') ?>
    </body>
</html>