<?php
$infoList = $this->execute();
if (!$infoList) {
   echo "<script>window.location = '/'</script>";
   return false;
}
$items = is_array($infoList) ? $infoList[0] : $infoList;
$out = '';
foreach ($items as $index => $item) {
   $infourl = $this->getInfoUrl($item->getId());
   $itemInfo = $this->getContent($item->getId());
   $out .= '<div class="itemsbox">
    <h2><a href="' . $infourl . '" style="color:#000;">' . $item->getTitle() . '</a></h2>
</div>';
};
echo $out;
?>