<?php
$infoList = $this->execute();
if (!$infoList) {
   echo "<script>window.location = '/'</script>";
   return false;
}
$items = is_array($infoList) ? $infoList[0] : $infoList;
$out = '<ul class="new_box">';
foreach ($items as $index => $item) {
   $infourl = $this->getInfoUrl($item->getId());
   $itemInfo = $this->getContent($item->getId());
   $out .=' <div class="employ_ele">
                <h3><i></i>' . $item->getTitle() . '<a href="' . $infourl . '">详细>></a></h3>
                <div class="employ_detail">
                    <p>
                        任职部门： ' . $itemInfo->getDepartment() . '
                    </p>
                    <p>
                        招聘人数：' . $itemInfo->getNumber() . '
                    </p> 
                    <p>
                        发布时间：' . date('Y-m-d', $item->getInputTime()) . '
                    </p>
                </div>
            </div>';
   $out .= '<li class="no_img">
        <a href="../dianpu/newsdetail.html">
            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>
            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌</p>
            <p class="writer_info clearfix">
                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>';
}
$out .= '</ul>';
echo $out;
?>
<ul class="new_box">
    <li class="no_img">
        <a href="../dianpu/newsdetail.html">
            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>

            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌</p>

            <p class="writer_info clearfix">

                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>
    <li>
        <a href="../dianpu/newsdetail.html">
            <img src="../../Images/test/test_pro_img.jpg" alt="">

            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>

            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

            <p class="writer_info clearfix">

                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>
    <li>
        <a href="../dianpu/newsdetail.html">
            <img src="../../Images/test/test_pro_img.jpg" alt="">

            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>

            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

            <p class="writer_info clearfix">

                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>
    <li class="no_img">
        <a href="../dianpu/newsdetail.html">
            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>

            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌</p>

            <p class="writer_info clearfix">

                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>
    <li>
        <a href="../dianpu/newsdetail.html">
            <img src="../../Images/test/test_pro_img.jpg" alt="">

            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>

            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

            <p class="writer_info clearfix">

                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>
    <li class="no_img">
        <a href="../dianpu/newsdetail.html">
            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>

            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌移动式动态空气消毒机南昌安尔森牌</p>

            <p class="writer_info clearfix">

                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>
    <li>
        <a href="../dianpu/newsdetail.html">
            <img src="../../Images/test/test_pro_img.jpg" alt="">

            <h3 class="new_title">卡萨帝灵珑传奇热水器</h3>

            <p class="new_text">南昌安尔森牌 移动式动态空气消毒机南昌安尔森牌</p>

            <p class="writer_info clearfix">

                <span class="fl">2015-01-06</span>
            </p>
            <span class="look">浏览（123）</span>
        </a>
    </li>
</ul>