<?php
$node0 = $this->getDefalutNode($this->getRouteNodeIdentifier());
$subNodes = $this->getSubNodeIds($node0->getId());
$subindetifiers = array();
foreach ($subNodes as $value) {
   $subindetifiers[] = $value->getNodeIdentifier();
}
array_push($subindetifiers, $node0->getNodeIdentifier());
$this->invokeParams['nodeIdentifier'] = $subindetifiers;
$infoList = $this->execute();
if (!$infoList) {
   echo "<script>window.location = '/'</script>";
   return false;
}
$items = is_array($infoList) ? $infoList[0] : $infoList;
$out = '<ul class="new_box news_list" ident="' . implode(',', $subindetifiers) . '">';
foreach ($items as $index => $item) {
   $defpic = $item->getDefaultPicUrl()[0];
   $infourl = $this->getInfoUrl($item->getId());
   $imgurl = $this->getImgcdn($defpic, 110, 68);
   $out .='<li>
        <a href="' . $infourl . '">
            <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $imgurl . '" alt="">
            <h3 class="new_title">' . $item->getTitle() . '</h3>
            <p class="writer_info clearfix">
                <span class="fl">' . date('Y-m-d', $item->getInputTime()) . '</span>
            </p>
            <span class="look">浏览（' . $item->getHits() . '）</span>
        </a>
    </li>';
}

echo $out . '</ul>';
?>
