<?php
$out = '';
$limit = (int) $this->invokeParams['outputNum'];
$lists = $this->getCaseList(true, 0, $limit);
foreach ($lists['items'] as $list) {
   $out .= '<div class="case_list">
    <a href="/casedetail/' . $list->getId() . '.html" class="case_list_a">
        <img src="' . $this->getImgcdn($list->getDefaultPicUrl()[0], 384, 384) . '" alt=""/>
        <h3>' . $list->getTitle() . '</h3>
        <p class="case_text">' . $list->getIntro() . '</p>
    </a>
</div>';
}

echo $out;
?>