<?php
$infoList = $this->execute();
if (!$infoList) {
   echo "<script>window.location = '/'</script>";
   return false;
}
$items = is_array($infoList) ? $infoList[0] : $infoList;
$out = '<div class="recruit_wrap">'
        . '<div class="recruit_title">
                <div class=" recruit_name">招聘名称</div>
                <div class=" recruit_category">招聘类别</div>
                <div class=" recruit_city">招聘人数</div>
                <div class=" recruit_date">发布时间</div>
            </div>';
$out1 = '';
foreach ($items as $index => $item) {
   $infourl = $this->getInfoUrl($item->getId());
   $itemInfo = $this->getContent($item->getId());
   $out .=' <div class="recruit_table">     
                <div class=" recruit_name"> <a href="' . $infourl . '">   ' . $item->getTitle() . ' </a></div>
                <div class=" recruit_category"><a href="' . $infourl . '">   ' . $itemInfo->getDepartment() . '</a></div>
                <div class=" recruit_city"><a href="' . $infourl . '">   ' . $itemInfo->getNumber() . '</a></div>
                <div class=" recruit_date"><a href="' . $infourl . '">   ' . date('Y-m-d', $item->getInputTime()) . '</a></div>
            </div>';
}
$out.='</div>';
$a = $this->getPaging($infoList[1]);
if ($this->getParam('enablePage') && $a['total'] > 1) {

   $currentPage = $a['current'];
   $pageOne = ''; //首页要加的类名
   $pageLast = '';  //未页要加的类名
   $pageFirstUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], 1) . '"';
   $pageLastUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], $a['total']) . '"';
   if ($currentPage == 1) {
      $pageOne = 'now_page';
      $pageFirstUrl = '#';
   }
   if ($currentPage == $a['total']) {
      $pageLast = 'now_page';
      $pageLastUrl = '';
   }
   $cls = "";
   $out .= ' <div class="page_list">
                        <p>';
   $out .='<a class="' . $pageOne . '" ' . $pageFirstUrl . '>首页</a>';
   if ($currentPage > 1) {
      $out.='<a href="' . $this->getPageUrl($a['nodeIdentifier'], $currentPage - 1) . '">&lt; 上一页</a>';
   }
   if ($currentPage > 5) {
      $out.='<a href="' . $this->getPageUrl($a['nodeIdentifier'], 1) . '">1</a>... ';
      for ($i = ($currentPage - 2); $i <= $a['total'] && $i <= $currentPage + 2; $i++) {
         $cls = "";
         $nowPageUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], $i) . '"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a  class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
   } else {
      for ($i = 1; $i <= $a['total'] && $i <= 6; $i++) {
         $cls = "";
         $nowPageUrl = 'href="' . $this->getPageUrl($a['nodeIdentifier'], $i) . '"';
         if ($i == $currentPage) {
            $cls = "main_bg main_border";
            $nowPageUrl = '';
         }
         $out .= '<a class="' . $cls . '" ' . $nowPageUrl . '>' . $i . '</a>';
      }
      if ($a['total'] > 6) {
         $out1 .='... ' . '<a href="' . $this->getPageUrl($a['nodeIdentifier'], 7) . '">7</a>';
      }
   }
   $out .= $out1;
   if ($a['total'] > 0 && $currentPage != $a['total']) {
      $out .= '<a href="' . $this->getPageUrl($a['nodeIdentifier'], $currentPage + 1) . '">下一页 &gt;</a>';
   }
   $out .= '<a class="' . $pageLast . '" ' . $pageLastUrl . '>尾页</a>';
   $out .= '</p>
                    </div>';
}

echo $out;
?>
