<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>404</title>
        <?php Qs::Sys('loadCss', array('kelepc/style.css', 'kelepc/app/404.css')) ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_KeleTop')) ?>
        <div class="nopage">
            <div class="nopage_img">
                <div class="nopage_img_content">
                </div>
            </div>
            <dl>
                <dt><img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_404_404.png') ?>" alt=""/></dt>
                <dd>
                    <a href="/" class="index">返回首页</a>
                    <a href="javascript:history.go(-1)" class="change">返回上页</a>
                </dd>
            </dl>
        </div>
        <?php
        Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_KeleBottom'));
        Qs::Sys('loadRequireJs', 'kelepc/com')
        ?>
    </body>
</html>