<?php Qs::Ds('用户数据源/供应商', 'User'); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>个人中心</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css')) ?>
    </head>
    <body>
        <!--个人中心头部-->
        <div class="head_wrap main_bg_light">
            <div class="head_box conwidth clearfix">
                <a class="logo_img fl" href="#"><img src="<?php Qs::Sys('loadImage', 'login/icon/icon_logo_fff.png') ?>"> </a>
                <ul class="fr clearfix">
                    <li><a class="mainbg_hover" href="#">首页</a></li>
                    <li><a class="mainbg_hover" href="#">产品中心</a></li>
                    <li><a class="mainbg_hover" href="#">询价单</a></li>
                    <li><a class="mainbg_hover" href="#">账号中心</a></li>
                    <li><a class="mainbg_hover" href="#">店铺设置</a></li>
                </ul>
            </div>
        </div>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <div class="items_wrap fl">
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>产品中心</dt>
                    <dd><a class="main_bg_light" href="#">发布产品</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">产品管理</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">产品分组</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>询价单</dt>
                    <dd><a class="mainbg_hover_light" href="#">全部</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">未回复</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">已回复</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-caozuochenggong"></i>账户中心</dt>
                    <dd><a class="mainbg_hover_light" href="/account/index.html">基本信息</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">我的地址</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">修改密码</a></dd>
                </dl>
            </div>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">个人信息</h1>
                <div class="form_box">
                    <?php 
                    $name = Qs::DsField('User', 'name',true);
                    $phone = Qs::DsField('User', 'phone',true);
                    if($name == $phone){
                       $canChange = '';
                    }else{
                       $canChange = 'disabled';
                    }
                    ?>
                    <div class="form_list">
                        <label><em class="main">*</em>用户名:</label>
                        <input type="text" id='name' value="<?php echo $name; ?>" fh-type="nickname" <?php echo $canChange?>>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>真实姓名:</label>
                        <input type="text" id="realName" value="<?php Qs::DsField('User', 'realName') ?>" reg="[\u4e00-\u9fa5]{2,6}" tip-value="请输入2-6位中文" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别:</label>
                        <?php
                        $checkArray = array(1 => '', 2 => '', 3 => '');
                        $sex = Qs::DsField('User', 'sex', true);
                        if ($sex == 1) {
                           $checkArray[1] = 'checked';
                        } elseif ($sex == 2) {
                           $checkArray[2] = 'checked';
                        } else {
                           $checkArray[3] = 'checked';
                        }
                        ?>
                        <div class="radio margin-left">
                            <label for="sex">
                                <input id="sex" name="sex" type="radio"  value="1" <?php echo $checkArray[1] ?>>
                                <i></i>
                                <span>男</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="sex2">
                                <input id="sex2" name="sex" type="radio"  value="2" <?php echo $checkArray[2] ?>>
                                <i></i>
                                <span>女</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="sex3">
                                <input id="sex3" name="sex" type="radio" value="3" <?php echo $checkArray[3] ?>>
                                <i></i>
                                <span>保密</span>
                            </label>
                        </div>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>手机号码:</label>
                        <input type="text" id="phone" value="<?php Qs::DsField('User', 'phone') ?>" disabled>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>部门:</label>
                        <input type="text" id="department" value="<?php Qs::DsField('User', 'department') ?>" required fh-type="length" minlength="2" maxlength="20"  required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>职位:</label>
                        <input type="text" id="position" value="<?php Qs::DsField('User', 'position') ?>" required fh-type="length" minlength="2" maxlength="20"  required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>邮箱:</label>
                        <input type="text" id="email" value="<?php Qs::DsField('User', 'email') ?>" fh-type="email" fh-type="email"  required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>展示电话:</label>
                        <input type="text" id="showPhone" value="<?php Qs::DsField('User', 'showPhone') ?>" fh-type="phone"  required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>QQ:</label>
                        <input type="text" id="qq" value="<?php Qs::DsField('User', 'qq') ?>" fh-type="qq" required>
                    </div>

                    <?php
                    $fax = Qs::DsField('User', 'fax', true);
                    $tel = Qs::DsField('User', 'tel', true);
                    if ($fax != null) {
                       $faxArray = explode('-', $fax);
                    } else {
                       $faxArray = array(0 => '', 1 => '', 2 => '');
                    }
                    if ($tel != null) {
                       $telArray = explode('-', $fax);
                    } else {
                       $telArray = array(0 => '', 1 => '', 2 => '');
                    }
                    ?>

                    <div class="form_list">
                        <label>座机:</label>
                        <input class="tel_china" id="telCountry" tip-target="#telNum" type="text" value="<?php echo $telArray[0]?>" reg="[1-9][0-9]{1,3}" tip-value="国家区号为2-3位数字">
                        <span class="tel_line">-</span>
                        <input class="tel_code" id="telArea" tip-target="#telNum" type="text" value="<?php echo $telArray[1]?>" reg="0[1-9][0-9]{1,2}" tip-value="区号为以0开头3-4位数">
                        <span class="tel_line">-</span>
                        <input class="tel_num" id="telNum" type="text" value="<?php echo $telArray[2]?>" fh-type="tel">
                    </div>
                    <div class="form_list">
                        <label>传真:</label>
                        <input class="tel_china" id="faxCountry" tip-target="#faxNum" type="text" value="<?php echo $faxArray[0]?>" reg="[1-9][0-9]{1,3}" tip-value="国家区号为2-3位数字">
                        <span class="tel_line">-</span>
                        <input class="tel_code" id="faxArea" tip-target="#faxNum" type="text" value="<?php echo $faxArray[1]?>" reg="0[1-9][0-9]{1,2}" tip-value="区号为以0开头3-4位数">
                        <span class="tel_line">-</span>
                        <input class="tel_num" id="faxNum"  type="text" value="<?php echo $faxArray[2]?>" fh-type="fax">
                    </div>
                    <div class="action_btn">
                        <label></label>
                        <a class="main_bg" id="submit">可选</a>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'provider/basicinfo') ?>
    </body>
</html>