<?php
Qs::Ds('用户数据源/供应商', 'User');
Qs::Ds('商城数据源/商城数据', 'site');
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>我的信息-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css')) ?>
        <style>
            div.radio i {
                width: 16px;
                height: 16px;
                width:16px\9\0;
                height:16px\9\0;
                *width:0;
                *height:0;
            }
        </style>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧') ?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">个人信息</h1>
                <div class="form_box">
                    <?php
                    $name = Qs::DsField('User', 'name', true);
                    $phone = Qs::DsField('User', 'phone', true);
                    if ($name == $phone) {
                       $canChange = '';
                    } else {
                       $canChange = 'disabled';
                    }
                    ?>
                    <div class="form_list">
                        <label><em class="main">*</em>用户名:</label>
                        <input type="text" id='name' value="<?php echo $name; ?>" reg="^[\w]{3,10}$" tip-value="请输入3-10位字母数字下划线" required <?php echo $canChange ?>>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别:</label>
                        <?php
                        $checkArray = array(1 => '', 2 => '', 3 => '');
                        $sex = Qs::DsField('User', 'sex', true);
                        if ($sex == 1) {
                           $checkArray[1] = 'checked';
                        } elseif ($sex == 2) {
                           $checkArray[2] = 'checked';
                        } else {
                           $checkArray[3] = 'checked';
                        }
                        ?>
                        <div class="radio margin-left">
                            <label for="sex">
                                <input id="sex" name="sex" type="radio"  value="1" <?php echo $checkArray[1] ?>>
                                <i></i>
                                <span>男</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="sex2">
                                <input id="sex2" name="sex" type="radio"  value="2" <?php echo $checkArray[2] ?>>
                                <i></i>
                                <span>女</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="sex3">
                                <input id="sex3" name="sex" type="radio" value="3" <?php echo $checkArray[3] ?>>
                                <i></i>
                                <span>保密</span>
                            </label>
                        </div>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>手机号码:</label>
                        <input type="text" id="phone" value="<?php Qs::DsField('User', 'phone') ?>" disabled>
                    </div>
                    <div class="form_list">
                        <label>部门:</label>
                        <input type="text" id="department" value="<?php Qs::DsField('User', 'department') ?>" required fh-type="length" minlength="2" maxlength="20" >
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>职位:</label>
                        <input type="text" id="position" value="<?php Qs::DsField('User', 'position') ?>" required fh-type="length" minlength="2" maxlength="20"  required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>邮箱:</label>
                        <input type="text" id="email" value="<?php Qs::DsField('User', 'email') ?>" fh-type="email" fh-type="email"  required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>联系人:</label>
                        <input type="text" id="realName" value="<?php Qs::DsField('User', 'realName') ?>" reg="[\u4e00-\u9fa5]{2,6}" required tip-value="请输入2-6位中文"> 此姓名在网站内容页展示以便联系
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>联系电话:</label>
                        <input type="text" id="showPhone" value="<?php Qs::DsField('User', 'showPhone') ?>" reg="[0-9\-]{7,25}"  required tip-value="请输入展示电话"> 此电话号码是公开展示在网页上的号码
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>QQ:</label>
                        <input type="text" id="qq" value="<?php Qs::DsField('User', 'qq') ?>" fh-type="qq" placeholder="此QQ可以直接在线聊天" required>
                    </div>

                    <?php
                    $fax = Qs::DsField('User', 'fax', true);
                    $tel = Qs::DsField('User', 'tel', true);
                    if ($fax != null) {
                       $faxArray = explode('-', $fax);
                    } else {
                       $faxArray = array(0 => '', 1 => '', 2 => '');
                    }
                    if ($tel != null) {
                       $telArray = explode('-', $tel);
                    } else {
                       $telArray = array(0 => '', 1 => '', 2 => '');
                    }
                    ?>

                    <div class="form_list">
                        <label>座机:</label>
                        <input class="tel_china" id="telCountry" value="86" placeholder="86" tip-target="#telNum" type="text" value="<?php echo $telArray[0] ?>" reg="[1-9][0-9]{1,3}" tip-value="国家区号为2-3位数字">
                        <span class="tel_line">-</span>
                        <input class="tel_code" id="telArea" placeholder="区号" tip-target="#telNum" type="text" value="<?php echo $telArray[1] ?>" reg="0[1-9][0-9]{1,2}" tip-value="区号为以0开头3-4位数">
                        <span class="tel_line">-</span>
                        <input class="tel_num" id="telNum" placeholder="手机号" type="text" value="<?php echo $telArray[2] ?>" fh-type="tel">
                    </div>
                    <div class="form_list">
                        <label>传真:</label>
                        <input class="tel_china" id="faxCountry" value="86" placeholder="86" tip-target="#faxNum" type="text" value="<?php echo $faxArray[0] ?>" reg="[1-9][0-9]{1,3}" tip-value="国家区号为2-3位数字">
                        <span class="tel_line">-</span>
                        <input class="tel_code" id="faxArea" placeholder="区号" tip-target="#faxNum" type="text" value="<?php echo $faxArray[1] ?>" reg="0[1-9][0-9]{1,2}" tip-value="区号为以0开头3-4位数">
                        <span class="tel_line">-</span>
                        <input class="tel_num" id="faxNum" placeholder="传真号"  type="text" value="<?php echo $faxArray[2] ?>" fh-type="fax">
                    </div>
                    <div class="form_list">
                        <div class="action_btn">
                            <a class="main_bg" id="submit">保存</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
        <?php Qs::Sys('loadRequireJs', 'provider/basicinfo') ?>
    </body>
</html>