<?php
Qs::Ds('用户数据源/企业信息', 'User');
Qs::Ds('商城数据源/商城数据', 'site');
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>企业信息-<?php Qs::DsField('site', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('site', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('site', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/user_index1.css')) ?>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧') ?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">个人信息</h1>
                <div class="form_box">
                    <div class="form_list">
                        <label><em class="main">*</em>企&nbsp;业&nbsp;名：</label>
                        <input type="text" id="name" class="checkField" value="<?php Qs::DsField('User', 'name') ?>" reg='^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){3,15}$' tip-value="请输入3-15位企业名称" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>企业类型：</label>
                        <select id="type">
                            <option value="1">国有企业</option>
                            <option value="2">集体企业</option>
                            <option value="3">私营企业</option>
                            <option value="4">股份制企业</option>
                            <option value="5">联营企业</option>
                            <option value="6">外商投资企业</option>
                            <option value="7">港、澳、台企业</option>
                            <option value="8">股份合作企业</option>
                            <option value="9">个体工商</option>
                            <option value="10">其他企业</option>
                        </select>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>经营模式：</label>
                        <div class="radio margin-left">
                            <label for="tradeMode1">
                                <input id="tradeMode1" name="tradeMode" type="radio" tabindex="2" value="1" checked>
                                <i></i>
                                <span>生产型</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="tradeMode2">
                                <input id="tradeMode2" name="tradeMode" type="radio" tabindex="3" value="2">
                                <i></i>
                                <span>贸易型</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="tradeMode3">
                                <input id="tradeMode3" name="tradeMode" type="radio" tabindex="4" value="3">
                                <i></i>
                                <span>服务型</span>
                            </label>
                        </div>
                        <div class="radio">
                            <label for="tradeMode4">
                                <input id="tradeMode4" name="tradeMode" type="radio" tabindex="4" value="4">
                                <i></i>
                                <span>服务型</span>
                            </label>
                        </div>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>主营产品：</label>
                        <?php
                        $products = Qs::DsField('User', 'products', true);
                        $products = empty($products) ? array() : $products;
                        for ($i = 0; $i < 4; $i++) {
                           if (0 == $i) {
                              echo '<input class="middle_input checkField" id="product' . ($i + 1) . '"  type="text" value="' . (isset($products[$i]) ? $products[$i] : '') . '" reg="^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){1,6}$" tip-value="请输入1-6位产品名称" required>';
                           } else {
                              echo '<input class="middle_input checkField" id="product' . ($i + 1) . '"  type="text" value="' . (isset($products[$i]) ? $products[$i] : '') . '" reg="^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){1,6}$" tip-value="请输入1-6位产品名称">';
                           }
                        }
                        ?>
                    </div>

                    <div class="form_list">
                        <label><em class="main">*</em>企业地址：</label>
                        <select class="company province" id="province" reg="^[\d]{6}$" tip-target="#district" tip-value="请选择省份" fh-value="<?php Qs::DsField('User', 'province'); ?>">
                            <option value="0">请选择</option>
                        </select>
                        <select class="company city" id="city" reg="^[\d]{6}$" tip-target="#district" tip-value="请选择城市" fh-value="<?php Qs::DsField('User', 'city'); ?>">
                            <option value="0">请选择</option>
                        </select>
                        <select class="company district" id="district" reg="^[\d]{6}$" tip-target="#district" tip-value="请选择县区" fh-value="<?php Qs::DsField('User', 'district'); ?>">
                            <option value="0">请选择</option>
                        </select>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>详细地址：</label>
                        <input type="text"  class="checkField" id="address" value="<?php Qs::DsField('User', 'address') ?>" reg='^([^<>]){3,15}$' tip-value="请输入3-30位详细地址" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>邮编：</label>
                        <input type="text" class="checkField" id="postCode" value="<?php Qs::DsField('User', 'postCode') ?>" reg='^[1-9]\d{5}$' tip-value="请输入正确的邮编" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>公司简介：</label>
                        <input type="text" id="description" class="checkField" value="<?php Qs::DsField('User', 'description') ?>" reg='^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){3,15}$' tip-value="请输入3-15位企业名称" required>
                    </div>
                    <div class="form_list">
                        <label class="label_uploading"><em class="main">*</em>公司logo：</label>
                        <ul class="img_uploading clearfix">
                            <?php
                            $img = Qs::DsField('User', 'logo', true);
                            if ($img) {
                               echo '<li class="logo">
                                <img id="logo" src="' . $img . '">
                                <em class="deleteImg">删除</em>
                            </li>
                            <li class="img_plus logo hide">
                                <p>+</p>
                                <span>添加照片</span>
                            </li>';
                            } else {
                               echo '
                            <li class="img_plus logo">
                                <p>+</p>
                                <span>添加照片</span>
                            </li>';
                            }
                            ?>

                        </ul>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>客户群体：</label>
                        <input type="text" id="customer" class="checkField" value="<?php Qs::DsField('User', 'customer') ?>" reg='^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){3,15}$' tip-value="请输入3-20位主要用户群体" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>品牌：</label>
                        <input type="text" id="brand" class="checkField" value="<?php Qs::DsField('User', 'brand') ?>" reg='^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){3,15}$' tip-value="请输入3-20位品牌名称" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>注册资金：</label>
                        <input type="text" id="registerCapital" class="checkField" value="<?php Qs::DsField('User', 'registerCapital') ?>" fh-type="number" required> 万元
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>注册年份：</label>
                        <input type="text" id="registerYear" class="checkField" value="<?php Qs::DsField('User', 'registerYear') ?>" reg='^[12][0-9]{3}$' tip-value="请输入四位数年份" required>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>注册地址：</label>
                        <select class="register province" id="registerProvince"  reg="^[\d]{6}$" tip-target="#registerDistrict" tip-value="请选择省份" fh-value="<?php Qs::DsField('User', 'registerProvince'); ?>">
                            <option value="0">请选择</option>
                        </select>
                        <select class="register city" id="registerCity" reg="^[\d]{6}$" tip-target="#registerDistrict" tip-value="请选择城市" fh-value="<?php Qs::DsField('User', 'registerCity'); ?>">
                            <option value="0">请选择</option>
                        </select>
                        <select class="register district" id="registerDistrict" reg="^[\d]{6}$" tip-target="#registerDistrict" tip-value="请选择区县" fh-value="<?php Qs::DsField('User', 'registerDistrict'); ?>">
                            <option value="0">请选择</option>
                        </select>
                    </div>
                    <div class="form_list">
                        <label><em class="main">*</em>法人：</label>
                        <input type="text" id="legalPerson" class="checkField" value="<?php Qs::DsField('User', 'legalPerson') ?>" reg='^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]){2,6}$' tip-value="请输入2-6位名字" required>
                    </div>
                    <div class="form_list">
                        <label>开户银行：</label>
                        <input type="text" id="bank" class="checkField" value="<?php Qs::DsField('User', 'bank') ?>" reg='^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]){3,15}$' tip-value="请输入3-15位银行名称">
                    </div>
                    <div class="form_list">
                        <label>开户帐号：</label>
                        <input type="text" id="bankAccount" class="checkField" value="<?php Qs::DsField('User', 'bankAccount') ?>" fh-type="num" tip-value="请输入3-15位企业名称">
                    </div>
                    <div class="form_list">
                        <div class="action_btn">
                            <a class="main_bg" id="submit">保存</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
        <?php Qs::Sys('loadRequireJs', 'provider/companyinfo') ?>
    </body>
</html>