<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>发布信息</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'lib/default.css', 'lib/reset.css', 'usercenter/publish_info.css')) ?>
        <style type="text/css" rel="stylesheet">
            .ke-icon-upload {
                background-position: 0px -496px;
                width: 50px;
                height: 16px;
                height: 16px;
            }
        </style>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">上架产品信息</h1>
                <?php Qs::Label('供应商/商品内容', array('renderTpl' => 'ProductChange')) ?>
            </div>
        </div>
    </div>
    <div class="hide" id="editorUpload"></div>
    <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
    <?php Qs::Sys('loadRequireJs', 'provider/productchange') ?>
</body>
</html>