<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>功能介绍-可乐云商</title>
        <?php Qs::Sys('loadCss', array('kelepc/style.css', 'slick.css', 'kelepc/app/function.css')) ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_KeleTopWithBanner')) ?>
        <!--banner-->
        <!--内容-->
        <div class="l_main ">
            <div class="case_title conwidth">
                <h3>解决方案</h3>
                <p>互联网行业解决方案领导品牌，值得信赖！</p>
            </div>
            <div class="function_ele function_first img_left">
                <div class="function_box conwidth">
                    <div class="function_img fl">
                        <div>
                            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_function1.jpg') ?>" alt="">
                        </div>

                    </div>
                    <div class="function_detail fr">
                        <h2>功能强大，使用便捷</h2>
                        <h4>商城功能强大，使用简单便捷</h4>
                        <p>商城呈现了它强大的功能体系，不仅基本的功能应有尽有，还可以根据客户需求对系统进行精简或是扩充，
                            避免客户所担心得网站的功能不齐全或过于繁杂问题，让客户的体验指数达到最高。</p>
                    </div>
                </div>
            </div>
            <div class="function_ele ">
                <div class="function_box conwidth">
                    <div class="function_img fr">
                        <div>
                            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_function2.jpg') ?>" alt="">
                        </div>

                    </div>
                    <div class="function_detail fl">
                        <h2>PC、手机、平板多重解决方案</h2>
                        <h4>PC、平板、手机自成一体、三管齐下</h4>
                        <p>系统不仅有电脑端，也同样注重移动端的开发，包括手机web端以及手机APP端的建设。
                            消费者通过相应设备访问网站时系统会自适应为对应网站模式。</p>
                    </div>
                </div>
            </div>
            <div class="function_ele img_left">
                <div class="function_box conwidth">
                    <div class="function_img fl">
                        <div>
                            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_function3.jpg') ?>" alt="">
                        </div>

                    </div>
                    <div class="function_detail fr">
                        <h2>搜索</h2>
                        <h4>全站式搜索</h4>
                        <p>商城内有全站商品搜索功能，方便用户进行筛选。</p>
                    </div>
                </div>
            </div>
            <div class="function_ele ">
                <div class="function_box conwidth">
                    <div class="function_img fr">
                        <div>
                            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_function4.jpg') ?>" alt="">
                        </div>

                    </div>
                    <div class="function_detail fl">
                        <h2>O2O营销模式</h2>
                        <h4>消费者可以在线下通过微信扫描商品二维码进入商品购买页，实现线下对线上的营销模式。</h4>
                        <p>商城为客户提供了营销的功能接口，线下对线上、线上对线下的营销模式在商城上都有体现。
                            消费者通过微信扫一扫功能即可直接进入商品详情页进行商品购买，增加了购买的体验指数。</p>
                    </div>
                </div>
            </div>
            <div class="function_ele img_left">
                <div class="function_box conwidth">
                    <div class="function_img fl">
                        <div>
                            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_function5.jpg') ?>" alt="">
                        </div>

                    </div>
                    <div class="function_detail fr">
                        <h2>微信公众号营销模式</h2>
                        <h4>平台打通了手机网站和微信公众号，企业可以通过商户控制台对微信菜单、打开页面等进行配置。</h4>
                        <p>商城打通了移动web端与微信公众号，企业可以在为新公众号里实现多种营销模式，用户可以在移动web端进行网站访问，
                            符合当下消费者的生活习惯。</p>

                    </div>
                </div>
            </div>
            <div class="function_ele ">
                <div class="function_box conwidth">
                    <div class="function_img fr">
                        <div>
                            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_function6.jpg') ?>" alt="">
                        </div>

                    </div>
                    <div class="function_detail fl">
                        <h2>商城帮助手册</h2>
                        <h4>商城帮助手册</h4>
                        <p>商城为消费者提供的帮助手册，包括如何购买，任何疑难问题的解答等。</p>
                    </div>
                </div>
            </div>
        </div>
        <!--底部-->
        <?php
        Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_KeleBottom'));
        Qs::Sys('loadRequireJs', 'kelepc/index')
        ?>

    </body>
</html>