<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>忘记密码</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/login.css')); ?>

    </head>
    <body>
        <div class="wrap">
            <div class="wrap_inner">
                <!--logo-->
                <div class="logo_register">
                    <div class="icon_logo fl">
                        <img src="<?php Qs::Sys('loadImage', 'login/icon/icon_logo_fff.png') ?>" alt="凤凰筑巢LOGO">
                    </div>
                    <h3 class="fl">供应商</h3>
                    <a href="register.html" class="register_a fr">还没有筑巢账号？30秒注册</a>
                </div>
                <div class="login_box">
                    <div class="login_header">
                        <h4 class="login_title">忘记密码</h4>
                        <div class="login_form" id="nameForm">
                            <form action="">
                                <div class="login_form_input">
                                    <input class="form_text" type="text" fh-type="phone" id="username" placeholder="请输入注册时使用的手机号" required>
                                    <div class="input_code clearfix">
                                        <input class="fl code" type="text" fh-type="imgCode" id="imgCode" autocomplete="off" placeholder="图片验证码" required>
                                        <a class="icode_image" >
                                            <img alt="图片验证码" title="看不清换一张" id="codeImg" src="/">
                                            <i class="icon-svgupdate" id="changeCodeImg"></i>
                                        </a>
                                    </div>
                                </div>
                                <!--提交-->
                                <input class="submit_btn main_bg_light" type="submit" id="nameFormSubmit" value="验证身份"/>
                            </form>
                        </div>
                        <div class="login_form hide" id="passwordForm" >
                            <form action="">
                                <div class="login_form_input">
                                    <input class="fl code" type="text" fh-type="phoneAuthCode" id="phoneAuthCode" autocomplete="off" placeholder="请输入短信验证码" required>
                                    <input class="form_text" type="password" fh-type="password" id="password" placeholder="请输入新密码" required>
                                    <input class="form_text" type="password" fh-type="password" id="passwordAgain" placeholder="请再次输入新密码" required>
                                </div>
                                <input class="submit_btn main_bg_light" type="submit" id="passwordFormSubmit" value="重置密码"/>
                            </form>
                        </div>
                        <!--成功-->
                        <div class="login_form tc success hide" id="successForm">
                            <i class="icon-duihaoyuanquan main_light"></i>
                            <p>新密码设置成功，请您牢记新密码</p>
                            <!--返回首页-->
                            <a class="main_border_light return_btn mainbg_hover_light" href="/">返回首页</a>
                            <a class="main_border_light return_btn mainbg_hover_light" href="/login.html">立即登录</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--版权 begin-->
        <div class="login_footer">
            <ul class="copy_nav clearfix">
                <li>
                    <a href="" target="_blank">关于我们</a>
                    <span></span>
                </li>
                <li>
                    <a href="" target="_blank">联系我们</a>
                    <span></span>
                </li>
                <li>
                    <a href="" target="_blank">友情链接</a>
                    <span></span>
                </li>
                <li>
                    <a href="" target="_blank">帮助中心</a>
                    <span></span>
                </li>
                <li>
                    <a href="" target="_blank">意见反馈</a>
                    <span></span>
                </li>
                <li>
                    <a href="" target="_blank">高薪聘请</a>
                    <span></span>
                </li>
                <li>
                    <a href="" target="_blank">法律声明</a>
                </li>
            </ul>
            <div class="copyright">© 2015 LaoKeBa.com 凤凰筑巢 保留所有权利</div>
            <div class="copy_icp">Copyright 2008-2016 GongChang.com All Rights Reserved 豫ICP备11020782号-15- 23.77ms</div>
        </div>
        <script data-main="/Statics/Skins/Pc/Js/requireenter.js" id="require" app="provider/forget" src="/Statics/Skins/Pc/Js/lib/require.js"></script>
    </body>
</html>