<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>产品列表页</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/prolist.css')) ?>
    </head>
    <body>
        <?php Qs::Label('供应商/用户中心头部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧') ?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">管理产品<a class="main_bg_light fr" href="/product/addproduct/1.html"><em>+</em>发布产品</a></h1>
                <div class="notice main_bg_light">
                    <a href="#"><i class="main icon-notice"></i> 按照要求填写可以提升产品上架权限 </a>
                </div>
                <!--搜索-->
                <?php Qs::Label('供应商/产品列表', array('renderTpl' => 'Query')) ?>
                <!--产品列表-->
                <?php Qs::Label('供应商/产品列表', array('renderTpl' => 'ProductList', 'outputNum' => 6, 'enablePage' => true)) ?>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_ProviderBottom')) ?>
        <?php Qs::Sys('loadRequireJs', 'provider/prolist') ?>
    </body>
</html>