<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>产品列表页</title>
        <?php Qs::Sys('loadCss', array('usercenter/style1.css', 'usercenter/prolist.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <div class="items_wrap fl">
                <dl>
                    <dt><i class="icon-product main"></i>产品中心</dt>
                    <dd><a class="main_bg_light" href="#">发布产品</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">产品管理</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">产品分组</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-xunjia main"></i>询价单</dt>
                    <dd><a class="mainbg_hover_light" href="#">全部</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">未回复</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">已回复</a></dd>
                </dl>
                <dl>
                    <dt><i class="icon-zhanghao main"></i>账户中心</dt>
                    <dd><a class="mainbg_hover_light" href="#">基本信息</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">我的地址</a></dd>
                    <dd><a class="mainbg_hover_light" href="#">修改密码</a></dd>
                </dl>
            </div>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">管理产品<a class="main_bg_light fr" href="#"><em>+</em>发布新闻</a></h1>
                <div class="notice main_bg_light">
                    <a href="#"><i class="main icon-notice"></i> 产品上架权限为3条， 剩余2条！如何提升产品上架权限 ？</a>
                </div>
                <!--搜索-->
                <?php Qs::Label('供应商/产品列表', array('renderTpl' => 'Query')) ?>
                <!--产品列表-->
                <?php Qs::Label('供应商/产品列表', array('renderTpl' => 'ProductList', 'outputNum' => 6, 'enablePage' => true)) ?>
            </div>
        </div>
        <?php Qs::Sys('loadRequireJs', 'provider/prolist') ?>
    </body>
</html>