<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>询价单</title>
        <?php Qs::Sys('loadCss', array('usercenter/style.css', 'usercenter/inquiry.css')) ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_ProviderTop')); ?>
        <!--个人中心-->
        <div class="content conwidth clearfix">
            <!--左侧列表-->
            <?php Qs::Label('供应商/用户中心左侧')?>
            <!--右侧内容-->
            <div class="content_wrap fr">
                <h1 class="items_title">收到的询价单</h1>
                <!--回复 未回复-->
                <ul class="reply clearfix">
                    <li class="main_bg">全部</li>
                    <li>回复</li>
                    <li>未回复</li>
                </ul>
                <?php Qs::Label('供应商/询价单', array('renderTpl' => 'usercenterList','outputNum' => 1))?>
                <div class="inquiry_delete ">
                    <span class="check"><em><i></i></em>全选</span>
                    <span class="btn btn_del">删除</span>
                </div>
            </div>
        </div>
    </div>
    <script data-main="../../Js/requireenter" app="usercenter/inquiry" id="require" src="../../Js/lib/require.js"></script>
</body>

</html>