<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>可乐云商首页</title>
        <?php Qs::Sys('loadCss', array('kelepc/style.css', 'slick.css', 'kelepc/app/index.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_KeleTopWithBanner')) ?>
        <!--banner-->
        <!--解决方案-->
        <div class="l_case conwidth">
            <div class="case_title">
                <h3>解决方案</h3>
                <p>互联网行业解决方案领导品牌，值得信赖！</p>
            </div>
            <div class="case_box">
                <div class="case_ele">
                    <div class="case_logo case_logo1">
                        <i class="icon-gouwulanzin "></i>
                        <!--<img src="Images/icon/icon_case1.png" alt="">-->
                    </div>
                    <h4>农村电商解决方案</h4>
                    <p>30年前，家庭联产责任承包制，解决了土地上种东西归谁的问题；
                        现在，农村电商要解决的是这块土地上的东西卖给谁的问题。</p>
                </div>
                <div class="case_ele">
                    <div class="case_logo case_logo2">
                        <i class="icon-shuiguo "></i>
                        <!--<img src="Images/icon/icon_case2.png" alt="">-->
                    </div>
                    <h4>生鲜水果解决方案</h4>
                    <p>适用于短时间内保存的食用类产品，如水果、蔬菜、海鲜。线上下单、极速送达，
                        成就未来城市生鲜水果超市的必然趋势。</p>
                </div>
                <div class="case_ele">
                    <div class="case_logo  case_logo3">
                        <i class="icon-xihumeizhuang"></i>
                        <!--<img src="Images/icon/icon_case3.png" alt="">-->
                    </div>
                    <h4>美妆洗护解决方案</h4>
                    <p>线上宣传积累用户；线上下单,线下发货。
                        电子商务必定是互联网+时代洗护产品的主要销售模式。</p>
                </div>
                <div class="case_ele">
                    <div class="case_logo  case_logo4">
                        <i class="icon-iconketing"></i>
                        <!--<img src="Images/icon/icon_case4.png" alt="">-->
                    </div>
                    <h4>家具家居解决方案</h4>
                    <p>减少家具购买的繁琐过程,为家具商家、定制商城缩减用户选购的时间成本,
                        提升用户体验。</p>
                </div>
            </div>
            <div class="case_prev case_arrow"><i class="icon-arrow_left"></i></div>
            <div class="case_next case_arrow"> <i class="icon-arrow_right"></i></div>
        </div>
        <!--为什么选择可乐云商-->
        <div class="l_why">
            <div class="why_content conwidth">
                <div class="why_title">
                    <h2>为什么选择可乐云商？</h2>
                    <div class="why_title_btn">
                        <span class="main_bg">公司资质</span>
                        <span>产品优势</span>
                        <span>服务机制</span>
                    </div>
                </div>
                <div class="why_list clearfix">
                    <div class="why_ele why_left">
                        <i class=" fl icon-fuwuqigaikuang"></i>
                        <h4>拥有强有力的硬件支持</h4>
                        <p>可乐云商虽起步不早，但对行业的认知却很高，不仅处在具有行业代表性的凤凰城商场......</p>
                    </div>
                    <div class="why_ele why_right">
                        <i class=" fr why_logo2 icon-case"></i>
                        <h4>拥有实际操作的成功案例</h4>
                        <p>凤凰筑巢由凤凰城的大环境产生，网站运营完全由公司内部人员操作，保证亲身体验其中......</p>
                    </div>
                    <div class="why_ele why_left">
                        <i class=" fl why_logo3 icon-babiaoxitong"></i>
                        <h4>业务集中，针对性强</h4>
                        <p>公司没有杂乱的分散业务，旗下的可乐云商只针对电子商务类型的网站建设。力争做电子......</p>
                    </div>
                    <div class="why_ele why_right">
                        <i class=" fr icon-biaozhunmoban02"></i>
                        <h4>全程服务，资料齐全</h4>
                        <p>对于使用可乐云商系统的客户，公司提供全程的建站服务，包括申请域名、备案，帮助上......</p>
                    </div>
                    <div class="why_ele why_left">
                        <i class=" fl icon-wodetuandui"></i>
                        <h4>团队精良，分工明确</h4>
                        <p>可乐云商有PHP、H5、IOS、安卓开发等各类专业技术工程师。在快速完成网站建设的......</p>
                    </div>
                </div>
                <div class="why_list clearfix hide">
                    <div class="why_ele why_left">
                        <i class=" fl icon-duozhongduan"></i>
                        <h4>突破传统，多终端适配。</h4>
                        <p>传统PC站、移动设备、微信公众号三位一体，一个后台操作，突破传统。结合微信营销，提高市场竞争力，实现直接经营粉丝和用户的外送系统平台。</p>
                    </div>
                    <div class="why_ele why_right">
                        <i class=" fr why_logo2 icon-hangye"></i>
                        <h4>功能齐全，多行业适用。</h4>
                        <p>通过大量的市场调研，结合每个行业的特性，进行深入开发，使最终的解决方案不仅贴合消费者的需求，还能带动市场的大潮流。</p>
                    </div>
                    <div class="why_ele why_left">
                        <i class=" fl why_logo3 icon-jiage"></i>
                        <h4>价格适中，易于接受。</h4>
                        <p>可乐云商采用多种价格模式，针对不同层次客户的不同需求。每年公司运营团队会举办两期网站运营课程培训，对于网站运营好的企业会赠送丰厚的增值服务或免除相应网站维护费用。</p>
                    </div>
                    <div class="why_ele why_right">
                        <i class=" fr icon-duotu"></i>
                        <h4>套餐多样，功能齐全。</h4>
                        <p>可乐云商拥有多种套餐类型，轻奢、定制，任意选择、各有千秋。同时支持PC+移动+微信三站一体的网站体系，还有后台管理APP，手机管店，随时随地更新动态、管理店铺。</p>
                    </div>
                    <div class="why_ele why_left">
                        <i class=" fl icon-bianjie"></i>
                        <h4>功能强大、使用便捷。</h4>
                        <p>系统稳定、流程清晰、操作简便、界面友好、可定制化精简/扩充 。</p>
                    </div>
                </div>
                <div class="why_list clearfix hide">
                    <div class="why_ele why_left">
                        <i class=" fl icon-yiduiyi"></i>
                        <h4>专职客服，一对一服务。</h4>
                        <p>专业的售前、售中、售后咨询客服，及时解答，快速解决客户运营前/中遇到的各种问题。</p>
                    </div>
                    <div class="why_ele why_right">
                        <i class=" fr why_logo2 icon-zixun"></i>
                        <h4>客户运营，全程咨询服务。</h4>
                        <p>运营团队全程提供运营方面的支持，传授客户网站运营技巧，提升网站的知名度。</p>
                    </div>
                    <div class="why_ele why_left">
                        <i class=" fl why_logo3 icon-shijian"></i>
                        <h4>7*8小时售后服务。</h4>
                        <p>为保证商家系统的正常使用，可乐云商7*8小时售后服务，及时解决客户反馈的问题。</p>
                    </div>
                    <div class="why_ele why_right">
                        <i class="fr icon-peixun"></i>
                        <h4>定期网站营销培训。</h4>
                        <p>网站营销团队每年组织两期运营知识课程培训，让客户不仅拥有商城，还熟知互联网+的营销理念。</p>
                    </div>
                    <div class="why_ele why_left">
                        <i class=" fl icon-zengzhi"></i>
                        <h4>增值配套服务。</h4>
                        <p>强大的技术团队根据市场及形式变化，会定期更新系统功能，保障客户使用最新应用。</p>
                    </div>
                </div>
            </div>
        </div>
        <!--研发动态-->
        <!--        <div class="l_condition conwidth">
                    <div class="case_title">
                        <h3>研发动态</h3>
                        <p>互联网行业解决方案领导品牌，值得信赖！</p>
                    </div>
                    <div class="condition_inner ">
                        <div class="condition_box clearfix">
                            <div class="condition_ele ">
                                <h4><i></i><a href="">可乐云商微商城功能启动</a></h4>
                                <p>在PC商城，手机商城的基础之上，可乐云商推出了专为微信定制开发的可乐云商微商城。
                                    微商城基于微信API接口深度定制开发，是对普通手机商城在微信中的功能......</p>
                            </div>
                            <div class="condition_ele ">
                                <h4><i></i><a href="">可乐云商微商城功能启动</a></h4>
                                <p>在PC商城，手机商城的基础之上，可乐云商推出了专为微信定制开发的可乐云商微商城。
                                    微商城基于微信API接口深度定制开发，是对普通手机商城在微信中的功能......</p>
                            </div>
                            <div class="condition_ele ">
                                <h4><i></i><a href="">可乐云商微商城功能启动</a></h4>
                                <p>在PC商城，手机商城的基础之上，可乐云商推出了专为微信定制开发的可乐云商微商城。
                                    微商城基于微信API接口深度定制开发，是对普通手机商城在微信中的功能......</p>
                            </div>
                            <div class="condition_ele ">
                                <h4><i></i><a href="">可乐云商微商城功能启动</a></h4>
                                <p>在PC商城，手机商城的基础之上，可乐云商推出了专为微信定制开发的可乐云商微商城。
                                    微商城基于微信API接口深度定制开发，是对普通手机商城在微信中的功能......</p>
                            </div>
                            <div class="condition_ele ">
                                <h4><i></i><a href="">可乐云商微商城功能启动</a></h4>
                                <p>在PC商城，手机商城的基础之上，可乐云商推出了专为微信定制开发的可乐云商微商城。
                                    微商城基于微信API接口深度定制开发，是对普通手机商城在微信中的功能......</p>
                            </div>
                        </div>
                    </div>
                </div>-->
        <!--侧边栏-->
        <div class="online">
            <div class="online_ele  ">
                <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=1134902426&site=qq&menu=yes">
                    <i class="icon-qq main"></i>
                    <p class="main">在线客服</p>
                    <span class="main_bg"></span>
                </a>
            </div>
            <div class="online_ele  no_mb">
                <a href="">
                    <i class="icon-dianhua2 main"></i>
                    <p class="main">电话联系</p>
                    <span class="main_bg"></span>
                    <div class='block'>
                        <em>电话：0371-55221883</em>
                        <span class="main_bg"></span>
                    </div>
                </a>
            </div>
        </div>
        <!--底部-->
        <?php
        Qs::Label('静态类/网站底部', array('renderTpl' => 'Pc_KeleBottom'));
        Qs::Sys('loadRequireJs', 'kelepc/index')
        ?>
    </body>
</html>