<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>帮助中心首页--新闻列表</title>
        <?php Qs::Sys('loadCss', array('help/helpstyle.css', 'help/helplist.css')); ?>
    </head>
    <body>
        <?php Qs::Label('静态类/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="../mall/index.html">首页</a>
            <span>&gt;</span>
            <a href="/category/help.html">帮助中心</a>
        </div>
        <!--帮助中心-->
        <div class="main_content clearfix conwidth">
            <!--左侧内容-->
            <div class="help_left_nav fl">
                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_LeftBar')); ?>
            </div>
            <!--右侧内容-->
            <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterList', 'outputNum' => 8)) ?>
        </div>
        <?php Qs::Label('静态类/网站底部') ?>
        <script data-main="/Statics/Skins/Pc/Js/requireenter.js" app="help/help" id="require" src="/Statics/Skins/Pc/Js/lib/require.js"></script>
    </body>
</html>