<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('栏目数据源/栏目SEO', 'category');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>帮助中心-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('category', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('category', 'keyword') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">		  
        <?php Qs::Sys('loadCss', array('help/helpstyle.css', 'help/helplist.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a class="main_hover" href="/index.html">首页</a>
            <span>&gt;</span>
            <a class="main_hover" href="/category/help.html">帮助中心</a>
        </div>
        <!--帮助中心-->
        <div class="main_content clearfix conwidth">
            <!--左侧内容-->
            <div class="help_left_nav fr">
                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_LeftBar')); ?>
            </div>
            <!--右侧内容-->
            <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterList', 'outputNum' => 8)) ?>
        </div>
        <?php Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'help/help');
        ?>
    </body>
</html>
