<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('栏目数据源/栏目SEO', 'category');
?>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>帮助中心-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('category', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('category', 'keyword') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">		  
        <?php Qs::Sys('loadCss', array('help/helpstyle.css', 'help/helpindex.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--站点指示-->
        <div class="site conwidth">
            <a href="/index.html">首页</a>
            <span>&gt;</span>
            <a href="/category/help.html">帮助中心</a>
        </div>
        <!--帮助中心-->
        <div class="main_content clearfix conwidth">
            <!--左侧内容-->
            <div class="help_left_nav fr">
                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_LeftBar')); ?>
            </div>
            <!--右侧内容-->
            <div class="right_content fl">
                <!--热门问题-->
                <h3>热门问题</h3>
                <ul class="hot_question clearfix main_hover">
                    <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HotQuestions', 'outputNum' => 8)); ?>
                </ul>
                <!--问题导航-->
                <h3>问题导航</h3>

                <div class="question_nav">
                    <ul class="question_item">
                        <li class="question_li">
                            <div class="question_img">
                                <i class="icon-zhanghu"></i>
                            </div>
                            <h4>帐号管理</h4>

                            <div class="question_sub_menu">
                                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterIndex', 'identifier' => 'zhanghaoguanli', 'type' => 2)) ?>
                            </div>
                        </li>
                        <li class="question_li">
                            <div class="question_img">
                                <i class="icon-caigoujinhuo"></i>
                            </div>
                            <h4>采购中心</h4>

                            <div class="question_sub_menu">
                                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterIndex', 'identifier' => 'caigouzhongxin', 'type' => 2)) ?>
                            </div>
                        </li>
                        <li class="question_li">
                            <div class="question_img">
                                <i class="icon-feature"></i>
                            </div>
                            <h4>供应商服务</h4>

                            <div class="question_sub_menu">
                                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterIndex', 'identifier' => 'gongyingshangfuwu', 'type' => 2)) ?>
                            </div>
                        </li>
                        <li class="question_li">
                            <div class="question_img">
                                <i class="icon-shangou"></i>
                            </div>
                            <h4>特色栏目</h4>

                            <div class="question_sub_menu">
                                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterIndex', 'identifier' => 'teselanmu', 'type' => 2)) ?>
                            </div>
                        </li>
                    </ul>
                    <ul class="question_item list_2">
                        <li class="question_li">
                            <div class="question_img">
                                <i class="icon-webiccaigouxuqiuhover"></i>
                            </div>
                            <h4>积分商城</h4>
                            <div class="question_sub_menu">
                                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterIndex', 'identifier' => 'jifenshangcheng', 'type' => 2)) ?>
                            </div>
                        </li>
                        <li class="question_li">
                            <div class="question_img">
                                <i class="icon-1"></i>
                            </div>
                            <h4>维权指南</h4>

                            <div class="question_sub_menu">
                                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_HelpCenterIndex', 'identifier' => 'weiquanzhinan', 'type' => 2)) ?>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'help/help'); ?>
    </body>
</html>
