<?php
$out = '<div class="module_ad3 module_ad clearfix  swiper-container">
	 <div class="swiper-wrapper">';
$locationId = $this->getAdsLocationId('手机端', '首页', 'banner');
$ads = $this->getAds($locationId);
if (count($ads)) {
   foreach ($ads as $ad) {
      $url = $ad->getContentUrl();
      $image = $this->getImageFromCdn($ad->getImage(), 414, 207);
      $out .= '<div class="module_ad_list swiper-slide">
				<a href="' . $url . '">
					 <div class="module_ad_img" style="background: url(' . $image . ');">
						  <div class="module_ad_box"></div>
					 </div>
				</a>
		  </div>';
   }
}
$out .= '</div>
	 <div class="swiper-pagination"></div>
</div>';

$out .= '<ul class="nav_radius100 module_nav clearfix">
	 <li>
	 <a href="http://' . \Cntysoft\RT_SYS_SITE_NAME . '/classifylist.html">
            <div class="nav_img">
                <i class="icon-fenlei1"></i>
            </div>
            <h2 class="nav_title">全部分类</h2>
        </a>
	 </li>
	 <li>
	 <a href="http://' . $this->getBuyerSiteName() . '/quotationlist/1.html">
            <div class="nav_img">
                <i class="icon-xunjia1"></i>
            </div>
            <h2 class="nav_title">我的询价</h2>
        </a>
	 </li>
	 <li>
	 <a href="http://' . $this->getBuyerSiteName() . '">
            <div class="nav_img">
                <i class="icon-gerenzhongxin"></i>
            </div>
            <h2 class="nav_title">个人中心</h2>
        </a>
	 </li>
	 <li>
	 <a href="http://' . \Cntysoft\RT_SYS_SITE_NAME . '/category/help.html">
            <div class="nav_img">
                <i class="icon-bangzhuzhongxin"></i>
            </div>
            <h2 class="nav_title">帮助中心</h2>
        </a>
	 </li>
	 <li>
	 <a href="http://' . \Cntysoft\RT_SYS_SITE_NAME . '/category/laobanneican.html">
            <div class="nav_img">
                <i class="icon-neican"></i>
            </div>
            <h2 class="nav_title">老板内参</h2>
        </a>
	 </li>
	 <li>
	 <a href="http://' . \Cntysoft\RT_SYS_SITE_NAME . '/category/zhuchaoschool.html">
            <div class="nav_img">
                <i class="icon-gongyingshang"></i>
            </div>
            <h2 class="nav_title">筑巢商学院</h2>
        </a>
	 </li>
</ul>';

$out .= '<div class="module_title">
	 <a href="/category/laobanneican.html">老板内参<i class="icon-gengduo"></i></a>	 
</div>
<ul class="new_box">';
$laobanneicai = $this->getNodeInfoByIdentifier('laobanneican');
$subNodes = $this->getSubNodesByIdentifier('laobanneican');
$nodeIds = array(
   $laobanneicai->getId()
);
foreach ($subNodes as $node) {
   $nodeIds[] = $node->getId();
}
$articles = $this->getInfoListByNodeAndStatusNotPage($nodeIds);
foreach ($articles as $article) {
   $out .= '<li>
		  <a href="/article/' . $article->getId() . '.html">
				<img src="' . $this->getImageFromCdn($article->getDefaultPicUrl()[0], 80, 50) . '" alt=""/>
				<p class="new_text">' . $article->getTitle() . '</p>
				<p class="new_date tr">' . date('Y-m-d', $article->getInputTime()) . '</p>
		  </a>
	 </li>';
}
$out .= '</ul>';
$goodsLists = $this->getGoodsList(array(), false, 'hits DESC', 0, 4);
$out .= '<div class="module_title">
	 <a>热门商品</a>
</div><div class="card_box">
	 <!--card3-->
	 <ul class="card3">';
foreach ($goodsLists as $list) {
   $url = $this->getProductUrl($list->getNumber());
   $out .= '<li>
				<a href="' . $url . '">
					 <div class="pro_img">
						  <div class="pro_table">
								<img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImageFromCdn($list->getDefaultImage(), 108, 62) . '" alt=""/>
						  </div>
					 </div>

					 <p class="pro_text">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</p>

					 <p class="pro_price add_color">¥' . ($list->getPrice() > 0 ? $list->getPrice() : "面议") . '</p>
				</a>
		  </li>';
}
$out .= '</ul>
</div>';
echo $out;
Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors', 'identifier' => 'zhuangshicailiao', 'floor' => 1));
Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors', 'identifier' => 'jiaju', 'floor' => 2));
Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors', 'identifier' => 'jiashijiafang', 'floor' => 3));
//Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors','identifier' => 'zhinengjiaju','floor' => 4));
//Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors','identifier' => 'wujingongju','floor' => 5));
//Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors','identifier' => 'diangongdianliao','floor' => 6));
//Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors','identifier' => 'jiegoucailiao','floor' => 7));
//Qs::Label('商品类/商品内容页', array('renderTpl' => 'Mobile_IndexFloors','identifier' => 'dingzhi','floor' => 8));

?>
