<?php
$goodsInfo = $this->getProductByNumber();
$goodsDetail = $goodsInfo->getDetail();
$category = $goodsInfo->getCategory();
$goodStatus = $goodsInfo->getStatus();
$statusText = '';
if ($goodStatus != 3) {
	$statusText = ' hide';
}
$name = ($goodsInfo->getBrand() . $goodsInfo->getTitle() . $goodsInfo->getDescription());

$out = '<div class="site conwidth">
				<a href="/index.html">首页</a>';
$out .= '<span>&gt;</span>
				<a href="/productclassify/' . $category->getId() . '/1.html">' . $category->getName() . '</a>';
$out .= '<span>&gt;</span>
				<a>' . $name . '</a></div>';
$out .= '<div class="l_main conwidth">
    <!--商品展示-->
    <div class="pro_display clearfix">
        <!--左侧图片展示-->
        <div class="pro_show fl">
            <div class="pro_show_content">
                <h3 class=" clearfix">
                    <div class="fl">
                        <p>' . $name . '</p>
                    </div>
                </h3>';
$images = $goodsDetail->getImages();
$bigImage = $smallImage = '';
$i = 1;
foreach ($images as $image) {
   if ($i == 1) {
      $bigImage .= '<div class="big_img">
                    <img src="' . $this->getImageFromCdn($image[0], 888, 556) . '" alt="">
                    <span class="next icon-jiantou6"></span>
                    <span class="prev icon-jiantou7"></span>
                </div>';
   }
   $i = 2;
   $smallImage .= '<div> <img src="' . $this->getImageFromCdn($image[0], 110, 69) . '" big="' . $this->getImageFromCdn($image[0], 888, 556) . '" alt=""></div>';
}
$out .= $bigImage . '</div>
            <div class="share clearfix">
                <div class="bdsharebuttonbox"><a class="bds_more" data-cmd="more"><i
                        class="main icon-fenxiang1"></i>分享</a></div>';
if ($this->checkLogin() && $this->checkCollect($goodsInfo->getId())) {
   $out .= ' <span class="collect_btn"><em>|</em><i class="main icon-shoucang"></i>已收藏</span>';
} else {
	$out .= ' <span class="collect_btn can_collect"><em>|</em><i class="main icon-shoucang"></i>收藏</span>';
}
$out .= '<div class="pro_code">
                    <i class="icon-erweima"></i>
                    <div class="pro_code_box">
                        <p>扫一扫&nbsp;&nbsp;用手机查看此页</p>
                        <div class="code_img">                            
                        </div>
                    </div>
                </div></div>
        </div>';
$provider = $goodsInfo->getProvider();
$company = $goodsInfo->getCompany();
$out .= '<div class="pro_about fr">
            <h3>编号：' . $goodsInfo->getNumber() . '</h3>
            <p class="pro_price main">￥' . ($goodsInfo->getPrice() > 0 ? $goodsInfo->getPrice() : "面议") . '</p>
            <div class="pro_local_box">
                <div class="pro_local">
                    <span class="local_intro">发&nbsp;货&nbsp;地：</span>
                    <div class="local_detail">
                        <span>' . $this->getAreaFromCode($company->getProvince()) . '</span><span>' . $this->getAreaFromCode($company->getCity()) . '</span>
                    </div>
                </div>
                <div class="pro_local">
                    <span class="local_intro">主营产品：</span>
                    <div class="local_detail">';
$products = explode(',', $company->getProducts());
foreach ($products as $product) {
   $out .= '<span>' . $product . '</span>';
}
$out .= '</div>
                </div>
            </div>
            <div class="company_code">
                <h4><a href="http://' . $company->getSubAttr() . '.' . \Cntysoft\RT_ZHUCHAO_SITE_DOMAIN . '">' . $company->getName() . '</a></h4>';
if ($company->getSubAttr()) {
   $out .= '<div class="company_code_img" url="http://' . $company->getSubAttr() . '.' . \Cntysoft\RT_ZHUCHAO_SITE_DOMAIN . '">
                </div>';
}
$out .= '</div>
            <div class="pro_connect">
                <div class="connect_btn' . $statusText . '"><i class="icon-dianhua2"></i>联系方式</div>
                <div class="online_btn zaixian_xunjia' . $statusText . '"><i class="icon-tubiao"></i>在线询价</div>
            </div>
        </div>
    </div>';
$out .= '<div class="small_img clearfix">' . $smallImage . '</div>';
$out .= '<div class="l_pro_info clearfix">
        <!--相关信息-->
        <div class="related_info fl">
            <h3 class="main_bg">相关信息</h3>';
$cid = $goodsInfo->getCategoryId();
$cond = array(
	'categoryId = ?1 AND status = 3',
	'bind' => array(
		1 => $cid
	)
);
$goodsLists = $this->getGoodsList($cond, false, 'id DESC', 0, 5);
foreach ($goodsLists as $goodsList) {
   if ($goodsList->getId() == $goodsInfo->getId()) {
      continue;
   }
   $url = $this->getProductUrl($goodsList->getNumber());
   $out .= '<div class="related_pro">
                <a href="' . $url . '"> <img src="' . $this->getImageFromCdn($goodsList->getDefaultImage(), 220, 137) . '" alt=""> </a>
                <p class="pro_intro"><a href="' . $url . '" class="main_hover">' . $goodsList->getTitle() . '</a></p>
                <p class="pro_price main">￥' . ($goodsList->getPrice() > 0 ? $goodsList->getPrice() : "面议") . '</p>
            </div>';
}
$out .= '</div><div class="m_pro_info fr">
		  <h3 class="pro_infor_nav clearfix">
				<span class="main_bg">商品信息</span>
				<span>详细属性</span>
				<span>联系方式</span>
				<span>评价</span>
		  </h3>';
$out .= '<div class="pro_info"><div class="pro_info_content">' . $goodsDetail->getIntroduction() . '</div></div>';
$attribute = $goodsDetail->getAttribute();
$out .= '<div class="pro_info l_parameter hide">
	 <table>
		  <tbody>';
foreach ($attribute as $key => $value) {
   if (count($value)) {
      $out .= '<tr>
					 <th colspan="2">' . $key . '</th>
				</tr>';
      foreach ($value as $attrs => $attr) {
         $out .= '<tr>
                   <td class="c_key">' . $attrs . '</td>
                   <td>' . $attr . '</td>
               </tr>';
      }
   }
}
$out .= '</tbody>
	 </table>
</div>';

if ($provider) {
   $providerDetail = $provider->getProfile();
   $out .= '<div class="pro_info hide">
                <div class="connect_box">
                    <div>
                        <div class="connect_ele">
                            <span class="icon-dianhua1 main_light"></span>
                            <h4>电话</h4>
                            <p>' . $providerDetail->getShowPhone() . '</p>
                        </div>
                        <div class="connect_ele">
                            <span class="icon-youxiang main_light"></span>
                            <h4>邮箱</h4>
                            <p>' . $providerDetail->getEmail() . '</p>
                        </div>
                    </div>
                    <div>
                        <div class="connect_ele">
                            <span class="icon-weixin main_light"></span>
                            <h4>QQ</h4>
                            <p>' . $providerDetail->getQq() . '</p>
                        </div>
                        <div class="connect_ele">
                            <span class="icon-iconfontzuobiao main_light"></span>
                            <h4>地址</h4>
                            <p>' . $this->getAreaFromCode($company->getProvince()) . $this->getAreaFromCode($company->getCity()) . $this->getAreaFromCode($company->getDistrict()) . $company->getAddress() . '</p>
                        </div>
                    </div>
                </div>
            </div>';
}
$out .= '<div class="pro_info"><div class="pro_info_content"></div></div>
</div>
</div>
</div>';
echo $out;
?>
