<?php
$out = '<div class="banner">
    <div class="banner_box">';
$locationId = $this->getAdsLocationId('电脑端', '首页', 'banner');
$ads = $this->getAds($locationId);
if (count($ads)) {
	foreach ($ads as $ad) {
		$url = $ad->getContentUrl();
		$image = $this->getImageFromCdn($ad->getImage(), 710, 400);
		$bgcolor = $ad->getBgcolor();
		$out .= '<div class="item" style="background-color: #' . $bgcolor . '"><a target="_blank" href="' . $url . '"><img src="' . $image . '"></a></div>';
	}
}
$out .= '</div><div class="banner_login_box">
            <div class="login_box">';
if (!$this->checkLogin()) {
	$out .= '<div class="login_user clearfix">
                    <a href=""><img src="/Statics/Skins/Pc/Images/lazyicon.png" alt=""/></a>
                    <h3 class="text_ellipsis">上午好，采购经理</h3>
                    <p class="text_ellipsis">欢迎来到凤凰筑巢！</p>
                </div>
                <div class="login_action">
                    <a class="main_bg" href="http://' . $this->getBuyerSiteName() . '/login.html">登录</a>
                    <a href="http://' . $this->getBuyerSiteName() . '/register.html">注册</a>
                </div>';
} else {
	$curUser = $this->getCurUser();
	$detail = $curUser->getProfile();
	$out .= '<div class="login_user clearfix">
                    <a href="http://' . $this->getBuyerSiteName() . '/login.html"><img src="' . $this->getImageFromCdn($detail->getAvatar(), 75, 53) . '" alt=""/></a>
                    <h3 class="text_ellipsis">上午好，采购经理</h3>
                    <p class="text_ellipsis">欢迎来到凤凰筑巢！</p>
                </div>
					 <div class="login_action">
                    <a class="main_bg" href="http://' . $this->getBuyerSiteName() . '/login.html">个人中心</a>
                    <a class="main_bg" href="/category/help.html">帮助中心</a>
                </div>';
}

$out .= '</div>
            <!--快报-->
            <div class="login_news">
                <h3>筑巢商学院</h3>
                <div class="main_hover login_news_list">';
$laobanneicai = $this->getNodeInfoByIdentifier('zhuchaoschool');
$subNodes = $this->getSubNodesByIdentifier('zhuchaoschool');
$nodeIds = array(
	$laobanneicai->getId()
);
foreach ($subNodes as $node) {
	$nodeIds[] = $node->getId();
}
$articles = $this->getInfoListByNodeAndStatusNotPage($nodeIds);
foreach ($articles as $article) {
	$out .= '<a href = "/article/' . $article->getId() . '.html"><i>' . $article->getTitle() . ' </i><span cla'
			  . 'ss = "date">' . date('m-d', $article->getInputTime()) . '</span></a>';
}
$out .= '</div>
</div><div class="login_news login_news2">
            <h3>筑巢公告</h3>
            <div class="main_hover login_news_list">';
$zhuchaogonggao = $this->getNodeInfoByIdentifier('zhuchaogonggao');
$articles = $this->getInfoListByNodeAndStatusNotPage($zhuchaogonggao->getId());
foreach ($articles as $article) {
	$out .= '<a href="/article/' . $article->getId() . '.html">'
			  . '<i>' . $article->getTitle() . ' </i><span class="date">' . date('m-d', $article->getInputTime()) . '</span></a>';
}
            $out .= '</div>
        </div>
</div>
</div><div class="sale_pro conwidth">
    <ul class="clearfix">';
$goodsLists = $this->getGoodsList(array(), false, 'hits DESC', 0, 4);
foreach ($goodsLists as $list) {
	$url = $this->getProductUrl($list->getNumber());
	$out .= '<li>
            <a href="' . $url . '">
                <img src="' . $this->getImageFromCdn($list->getDefaultImage(), 150, 150) . '" alt=""/>

                <div class="pro_text_box">
                    <h3 class="text_ellipsis">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</h3>

                    <p class="text_ellipsis">' . $list->getDetail()->getAdvertText() . '</p>
                    <span class="pro_text_tip">￥' . ($list->getPrice() > 0 ? $list->getPrice() : "面议") . '</span>
                </div>
                <span class="sale_tip main_bg">
                    热
                </span>
            </a>
        </li>';
}
$out .= '</ul>
</div><h3 class="module_title conwidth">
    <a href=""> <img src="/Statics/Skins/Pc/Images/mall/icon/icon_aboutus_title.png" alt=""/></a>
</h3><div class="about_us conwidth clearfix">
    <!--品牌广告-->
    <div class="brand_ad fl about_item">
        <a class="item_title main_bg">品牌广告</a>';
$locationId = $this->getAdsLocationId('电脑端', '首页', 'body1');
$ads = $this->getAds($locationId);
if (count($ads)) {
	foreach ($ads as $ad) {
		$url = $ad->getContentUrl();
		$image = $this->getImageFromCdn($ad->getImage(), 710, 400);
		$bgcolor = $ad->getBgcolor();
		$out .= '<a target="_blank" href="' . $url . '" class="brand_ad_img">
            <img src="' . $image . '" alt=""/>
            <p class="text_ellipsis">' . $ad->getName() . '</p>
        </a>';
		break;
	}
}

$out .= '</div>';
$laobanneicai = $this->getNodeInfoByIdentifier('laobanneican');
$subNodes = $this->getSubNodesByIdentifier('laobanneican');
$nodeIds = array(
	$laobanneicai->getId()
);
foreach ($subNodes as $node) {
	$nodeIds[] = $node->getId();
}
$articles = $this->getInfoListByNodeAndStatusNotPage($nodeIds);
$out .= '<div class="about_news fl about_item">
        <a href="/category/laobanneican.html" class="item_title main_bg">老板内参</a>

        <div class="about_news_items main_hover">';
$i = 1;
foreach ($articles as $article) {
	if ($i == 1) {
		$out .= '<div class="about_news_list">
                <h4><a href="/article/' . $article->getId() . '.html">' . $article->getTitle() . '</a></h4>
                <p>
                    ' . $article->getIntro() . '
                </p>
                <img src="' . $this->getImageFromCdn($article->getDefaultPicUrl()[0], 196, 138) . '" alt=""/>
            </div>';
	} else {
		$out .= '<div class="about_news_list">
                <h4><a href="/article/' . $article->getId() . '.html"><i></i>' . $article->getTitle() . '</a></h4>
                <span class="date">' . date('Y-m-d', $article->getInputTime()) . '</span>
            </div>';
	}
	$i = 2;
}
$out .= '</div>
    </div>';

$out .= '<div class="about_right_box fl about_item">
        <a class="item_title main_bg">采购实况</a>
        <div class="about_right_item">';
foreach ($goodsLists as $list) {
	$url = $this->getProductUrl($list->getNumber());
	$out .= '<div class="about_right_list">
                <span class="address text_ellipsis">河南省郑州市</span>
                <span class="time">' . rand(1, 10) . '秒前</span>
                <h4 class="text_ellipsis main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h4>
            </div>';
}
$out .= '</div>
</div></div><h3 class="module_title conwidth">
    <a href=""> <img src="/Statics/Skins/Pc/Images/mall/icon/icon_pro_title.png" alt=""/></a>
</h3><div class="pro_card conwidth">
    <ul class="clearfix">';
$goodsLists = $this->getGoodsList(array(), false, 'inputTime DESC', 0, 5);
foreach ($goodsLists as $list) {
	$url = $this->getProductUrl($list->getNumber());
	$out .= '<li>
            <p class="card_price">¥' . ($list->getPrice() > 0 ? $list->getPrice() : "面议") . '</p>
            <a href="' . $url . '" class="card_img"><img src="' . $this->getImageFromCdn($list->getDefaultImage(), 212, 212) . '" alt=""/></a>

            <div class="card_text_box">
                <h3 class="text_ellipsis main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h3>
                <i class="jiantou icon-jiantou-copy"></i>
            </div>
            <span class="pro_card_tip">
                <b>新品</b>
                <i class="icon-biaoqian main"></i>
            </span>
        </li>';
}
$out .= '</ul>';
$superNodes = $this->getSuperNodes();
foreach ($superNodes as $super) {
	$out .= '</div><div class="module_title conwidth clearfix">
    <a href=""> <img src="/Statics/Skins/Pc/Images/mall/icon/icon_pro_title.png" alt=""/></a>
</div><div class="pro_list clearfix conwidth">';
	$nodes = $this->getNodePath($super->getId());
	$cond = array('categoryId IN (' . implode(',', $nodes) . ') AND status = 3');
	$goodsLists = $this->getGoodsList($cond, false, 'hits DESC', 0, 1);
	foreach ($goodsLists as $list) {
		$url = $this->getProductUrl($list->getNumber());
		$out .= '<div class="pro_item fl">
        <a class="pro_img" href="' . $url . '">
            <img src="' . $this->getImageFromCdn($list->getDefaultImage(), 219, 220) . '" alt=""/>
        </a>
        <h3 class="pro_text text_ellipsis main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h3>

        <span class="pro_price">' . ($list->getPrice() > 0 ? "￥" . $list->getPrice() : "￥面议") . '</span>
    </div>';
	}
	$goodsLists = $this->getGoodsList($cond, false, 'hits DESC', 1, 4);
	$out .= '<div class="pro_item fl pro_banner noselect">
	 <a class="switch_btn switch_left_btn left_btn1"><i class="icon-jiantou4"></i></a>
	 <a class="switch_btn switch_right_btn right_btn1"><i class="icon-jiantou2"></i></a>
	 <div class="pro_banner_box" pro-box="pro-box1">';
	foreach ($goodsLists as $list) {
		$url = $this->getProductUrl($list->getNumber());
		$out .= '<div class="pro_banner_li clearfix">
				<div class="fl pro_banner_text">
					 <h3 class="pro_text text_ellipsis main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h3>
					 <p class="pro_tip">
						  <span>' . $list->getDetail()->getAdvertText() . '</span>
					 </p>
					 <p class="pro_banner_price">' . ($list->getPrice() > 0 ? "￥" . $list->getPrice() : "￥面议") . '</p>
				</div>
				<a class="pro_banner_img"><img src="' . $this->getImageFromCdn($list->getDefaultImage(), 219, 220) . '" alt=""/></a>
		  </div>';
	}
	$out .= '</div>
</div>';
	$goodsLists = $this->getGoodsList($cond, false, 'hits DESC', 5, 6);
	foreach ($goodsLists as $list) {
		$url = $this->getProductUrl($list->getNumber());
		$out .= '<div class="pro_item fl">
        <a class="pro_img" href="' . $url . '">
            <img src="' . $this->getImageFromCdn($list->getDefaultImage(), 219, 220) . '" alt=""/>
        </a>
        <h3 class="pro_text text_ellipsis main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h3>

        <span class="pro_price">' . ($list->getPrice() > 0 ? "￥" . $list->getPrice() : "￥面议") . '</span>
    </div>';
	}
}
$out .= '</div>';
echo $out;
?>














