<?php
$identifierInfo = $this->getCategoryInfoByIdentifier($this->invokeParams['identifier']);
$out = '<div class="module_title conwidth clearfix">
    <a><b>' . $this->invokeParams['floor'] . 'F</b><span> / ' . $identifierInfo->getName() . '</span></a>
</div>';
$nodes = $this->getNodePath($identifierInfo->getId());
$cond = array('categoryId IN (' . implode(',', $nodes) . ') AND status = 3');
$goodsLists = $this->getGoodsList($cond, false, 'inputTime DESC', 0, 11);
$out .= '<div class="pro_list clearfix conwidth">';
$i = 0;
foreach ($goodsLists as $list) {
   $i++;
   if ($i > 1) {
      break;
   }
   $url = $this->getProductUrl($list->getNumber());
   $out .= '<div class="pro_item fl">
        <a class="pro_img" href="' . $url . '">
            <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImageFromCdn($list->getDefaultImage(), 220, 137) . '" alt=""/>
        </a>
        <h3 class="pro_text main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h3>

        <span class="pro_price">' . ($list->getPrice() > 0 ? "￥" . $list->getPrice() : "￥面议") . '</span>
    </div>';
}
$out .= '<div class="pro_item fl pro_banner noselect">
	 <a class="switch_btn switch_left_btn left_btn' . $this->invokeParams['floor'] . '"><i class="icon-jiantou4"></i></a>
	 <a class="switch_btn switch_right_btn right_btn' . $this->invokeParams['floor'] . '"><i class="icon-jiantou2"></i></a>
	 <div class="pro_banner_box" pro-box="pro-box' . $this->invokeParams['floor'] . '">';
$i = 0;
foreach ($goodsLists as $list) {
   $i++;
   if ($i < 2) {
      continue;
   }
   if ($i > 5) {
      break;
   }
   $url = $this->getProductUrl($list->getNumber());
   $out .= '<div class="pro_banner_li clearfix">
				<div class="fl pro_banner_text">
					 <h3 class="pro_text main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h3>
					 <p class="pro_tip">
						  <span>' . $list->getDetail()->getAdvertText() . '</span>
					 </p>
					 <p class="pro_banner_price">' . ($list->getPrice() > 0 ? "￥" . $list->getPrice() : "￥面议") . '</p>
				</div>
				<a class="pro_banner_img" href="' . $url . '"><img src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-lazy="' . $this->getImageFromCdn($list->getDefaultImage(), 480, 300) . '"/></a>
		  </div>';
}
$out .= '</div>
</div>';
$i = 0;
foreach ($goodsLists as $key => $list) {
   $i++;
   if ($i < 6) {
      continue;
   }
   if ($i > 11) {
      break;
   }
   $cls = 'no_bb';
   if ($key == 5) {
      $cls = 'no_br border-left';
   }
   $url = $this->getProductUrl($list->getNumber());
   $out .= '<div class="pro_item fl ' . $cls . '">
        <a class="pro_img" href="' . $url . '">
            <img class="lazy" src="http://statics-b2b.fhzc.com/Pc/Images/lazyicon.png" data-original="' . $this->getImageFromCdn($list->getDefaultImage(), 220, 137) . '" alt=""/>
        </a>
        <h3 class="pro_text main_hover"><a href="' . $url . '">' . $list->getBrand() . $list->getTitle() . $list->getDescription() . '</a></h3>

        <span class="pro_price">' . ($list->getPrice() > 0 ? "￥" . $list->getPrice() : "￥面议") . '</span>
    </div>';
}
$out .= '</div>';
echo $out;
?>



