<!DOCTYPE html>
<?php
Qs::Ds('内容数据源/标准内容模型', 'AC');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php Qs::DsField('AC', 'title') ?></title>
        <meta name="description" content="<?php Qs::DsField('AC', 'intro') ?>">
        <meta name="keywords" content="<?php Qs::DsField('AC', 'keywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('college/style.css', 'college/collegeinfo.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--导航-->
        <div class="head main_bg_light">
            <div class="head_box conwidth1100 clearfix">
                <a class="logo_img fl" href="/">
                    <img src="<?php Qs::Sys('loadImage', 'reference/test_logo_white.png') ?>">
                    <span><em>|</em>商学院</span>
                </a>
                <ul class="fr clearfix">
                    <?php
                    $nodeIdentifier = Qs::DsField('AC', 'nodeIdentifier', true);
                    $sign2 = '';
                    $sign3 = $nodeIdentifier == 'dianshangzixun' ? 'main_bg' : '';
                    $sign4 = $nodeIdentifier == 'jingdiananli' ? 'main_bg' : '';
                    if (strlen($sign3) == 0 && strlen($sign4) == 0) {
                       $sign2 = 'main_bg';
                    }
                    echo '<li><a class="mainbg_hover" href="/category/zhuchaoschool.html">首页</a></li>
                    <li><a class=" ' . $sign2 . ' mainbg_hover" href="/category/kechengzhongxin/1.html">课程中心</a></li>
                    <li><a class=" ' . $sign3 . ' mainbg_hover" href="/category/dianshangzixun/1.html">电商资讯</a></li>
                    <li><a class=" ' . $sign4 . ' mainbg_hover" href="/category/jingdiananli/1.html">经典案例</a></li>';
                    ?>
                </ul>
            </div>
        </div>
        <!--课程中心-->
        <div class="center_main clearfix conwidth1100">
            <div class="fl main_left">
                <div class="content_title">
                    <h3><?php Qs::DsField('AC', 'title') ?></h3>

                    <div class="writer_info clearfix">
                        <div class="fl">
                            <span>发表时间：<?php echo date('Y-m-d', QS::DsField('AC', 'inputTime', true)) ?></span>
                            <span class="read">浏览：<?php Qs::DsField('AC', 'hits') ?></span>
                        </div>
                        <div class="fr share"><span>分享到：</span>
                            <div class="bdsharebuttonbox bdshare-button-style0-16" data-bd-bind="1459217014014">
                                <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                                <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                                <a  class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                                <a  class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>
                                <a  class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="module_content" style="min-height: 600px" article="<?php Qs::DsField('AC', 'id') ?>">
                    <?php Qs::DsField('AC', 'content') ?>
                    <!--上一篇下一篇-->                    
                </div>
                <div class="up_down">
                    <div>
                        上一篇：<?php
                        $prev = Qs::DsField('AC', 'prev', true);
                        if ($prev) {
                           $pretitle = iconv_substr($prev[1], 0, 18, 'UTF-8');
                           echo '<a href="' . $prev[0] . '" class="main_hover">' . $pretitle . '</a>';
                        } else {
                           echo '木有了';
                        }
                        ?>
                    </div>
                    <div>
                        下一篇：<?php
                        $next = Qs::DsField('AC', 'next', true);
                        if ($next) {
                           $nexttitle = iconv_substr($next[1], 0, 18, 'UTF-8');
                           echo '<a href="' . $next[0] . '" class="main_hover">' . $nexttitle . '</a>';
                        } else {
                           echo '正在更新中，请等待~';
                        }
                        ?>
                    </div>
                </div>
                <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'ChangyanComment')) ?>
            </div>
            <div class="fr main_right">
                <div class="erweima">
                    <div id="weixin_code"></div>
                    <span>扫一扫用手机浏览</span>
                </div>
                <h3 class="right_title"><a >最近发布</a></h3>
                <?php
                Qs::Label('文章/电商宝典', array('renderTpl' => 'Pc_ContentRightArticle', 'nodeIdentifier' => array('zhuchaoschool'), 'titleLength' => 28, 'introLength' => 20, 'outputNum' => 8, 'enablePage' => false, 'listSubNode' => true))
                ?>  
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'college/collegeinfo');
        ?>
    </body>
</html>
