<!DOCTYPE html>
<?php Qs::Ds('内容数据源/标准内容模型', 'AC');Qs::Ds('商城数据源/商城数据', 'sites'); ?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>课程详情-筑巢商学院-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
		  <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
		  <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
		  <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
		  <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('college/style.css', 'college/collegeinfo.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_LaoBan',)) ?>
        <!--导航-->
        <div class="head main_bg_light">
            <div class="head_box conwidth1100 clearfix">
                <a class="logo_img fl" href="/">
                    <img src="<?php Qs::Sys('loadImage', 'reference/test_logo_white.png') ?>">
                    <span><em>|</em>商学院</span>
                </a>
                <ul class="fr clearfix">
                    <?php
                    $nodeIdentifier = Qs::DsField('AC', 'nodeIdentifier', true);
                    $sign2 = '';
                    $sign3 = $nodeIdentifier == 'dianshangzixun' ? 'main_bg' : '';
                    $sign4 = $nodeIdentifier == 'jingdiananli' ? 'main_bg' : '';
                    if (strlen($sign3) == 0 && strlen($sign4) == 0) {
                       $sign2 = 'main_bg';
                    }
                    echo '<li><a class="mainbg_hover" href="/category/zhuchaoschool.html">首页</a></li>
                    <li><a class=" ' . $sign2 . ' mainbg_hover" href="/category/kechengzhongxin/1.html">课程中心</a></li>
                    <li><a class=" ' . $sign3 . ' mainbg_hover" href="/category/dianshangzixun/1.html">店商资讯</a></li>
                    <li><a class=" ' . $sign4 . ' mainbg_hover" href="/category/jingdiananli/1.html">经典案例</a></li>';
                    ?>
                </ul>
            </div>
        </div>
        <!--课程中心-->
        <div class="center_main clearfix conwidth1100">
            <div class="fl main_left">
                <div class="content_title">
                    <h3><?php Qs::DsField('AC', 'title') ?></h3>

                    <div class="writer_info">
                        <span>发表时间：<?php echo date('Y-m-d', QS::DsField('AC', 'inputTime', true)) ?></span>
                        <span class="writer">作者：<?php Qs::DsField('AC', 'author') ?></span>
                        <span>浏览：<?php Qs::DsField('AC', 'hits') ?></span>
                    </div>
                </div>
                <div class="module_content" style="min-height: 600px">
                    <?php Qs::DsField('AC', 'content') ?>
                    <!--上一篇下一篇-->                    
                </div>
                <div class="prev_next">
                    <p><em>上一篇：</em><?php
                        $prev = Qs::DsField('AC', 'prev', true);
                        if ($prev) {
                           echo '<a style="font-size: 14px;color: #666;"  href="' . $prev[0] . '">' . iconv_substr($prev[1], 0, 18) . '</a>';
                        } else {
                           echo '木有了';
                        }
                        ?>
                    </p>
                    <p><em>下一篇：</em><?php
                        $next = Qs::DsField('AC', 'next', true);
                        if ($next) {
                           echo '<a style="font-size: 14px;color: #666;" href="' . $next[0] . '">' . iconv_substr($next[1], 0, 18) . '</a>';
                        } else {
                           echo '正在更新中，请等待~';
                        }
                        ?></p>
                </div>
            </div>
            <div class="fr main_right">
                <h3 class="right_title"><a >最近发布</a></h3>
                <?php
                Qs::Label('文章/电商宝典', array('renderTpl' => 'ContentRightArticle', 'nodeIdentifier' => array('zhuchaoschool'), 'titleLength' => 28, 'introLength' => 20, 'outputNum' => 8, 'enablePage' => false, 'listSubNode' => true))
                ?>  
            </div>
        </div>
        <?php Qs::Label('静态类/网站底部', array('renderTpl' => 'MallDefault',)) ?>
        <?php Qs::Sys('loadRequireJs', 'reference/referenceindex') ?>      
    </body>
</html>