<?php Qs::Ds('商城数据源/商城数据', 'sites'); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>筑巢商学院-课程中心、店商资讯、经典案例-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('college/style.css', 'college/collegecenter.css')) ?>
    </head>
    <body>
        <!--头部-->
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_Top',)) ?>
        <!--导航-->
        <div class="head main_bg_light">
            <div class="head_box conwidth1100 clearfix">
                <a class="logo_img fl" href="/">
                    <img src="<?php Qs::Sys('loadImage', 'reference/test_logo_white.png') ?>">
                    <span><em>|</em>商学院</span>
                </a>
                <ul class="fr clearfix">
                    <li><a class="mainbg_hover" href="/category/zhuchaoschool.html">首页</a></li>
                    <li><a class="mainbg_hover" href="/category/kechengzhongxin/1.html">课程中心</a></li>
                    <li><a class="mainbg_hover" href="/category/dianshangzixun/1.html">店商资讯</a></li>
                    <li><a class="mainbg_hover" href="/category/jingdiananli/1.html">经典案例</a></li>
                </ul>
            </div>
        </div>
        <!--课程中心-->
        <div class="center_main clearfix conwidth1100">
            <div class="fl main_left">
                <!--筛选-->
                <?php
                Qs::Label('文章/电商宝典', array('renderTpl'      => 'Pc_DefaultChoose', 'nodeIdentifier' => array(
                      'kechengzhongxin'
           )))
                ?>
                <!--列表-->
                <?php
                Qs::Label('文章/电商宝典', array('renderTpl' => 'Pc_DefaultList', 'nodeIdentifier' => array(), 'titleLength' => 28, 'introLength' => 20, 'outputNum' => 5, 'enablePage' => true, 'listSubNode' => true))
                ?>
            </div>
            <div class="fr main_right">
                <h3 class="right_title"><a href="/category/kechengzhongxin/1.html">最新课程</a></h3>
                <?php
                Qs::Label('文章/电商宝典', array('renderTpl' => 'Pc_NewArticle', 'nodeIdentifier' => array('kechengzhongxin'), 'titleLength' => 28, 'introLength' => 20, 'outputNum' => 3, 'enablePage' => false, 'listSubNode' => true))
                ?>
            </div>
        </div>
        <?php
        Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'college/collegeindex');
        ?>
    </body>
</html>