<!DOCTYPE html>
<?php
Qs::Ds('商城数据源/商城数据', 'sites');
Qs::Ds('栏目数据源/栏目SEO', 'category');
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>帮助中心-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('category', 'description') ?>">
        <meta name="keywords" content="<?php Qs::DsField('category', 'keyword') ?>">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">		  
        <?php Qs::Sys('loadCss', array('mall/style.css', 'mall/notice.css')); ?>
    </head>
    <body>
        <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Pc_HelpCenterTop')) ?>
        <!--导航-->
        <div class="site conwidth">
            <a href="/">首页</a>
            <span>&gt;</span>
            <a>公告</a>
        </div>
        <div class="content conwidth clearfix">
            <!--公告进度-->
            <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_NoticeList','outputNum' => 6)) ?>
            <!--公告新闻-->
            <?php Qs::Label('帮助中心/帮助中心', array('renderTpl' => 'Pc_NoticeRight','outputNum' => 6)) ?>
        </div>
        <?php Qs::Label('静态类/网站底部');
        Qs::Sys('loadRequireJs', 'mall/notice');
        ?>
    </body>
</html>