<table>
    <tr class="news_items">
        <th class="news_title">案例名称</th>
        <th class="news_time">发布时间</th>
        <th class="news_operate">操作</th>
    </tr>
    <?php
    use App\Yunzhan\Content\Constant;
$routeInfo = $this->getRouteInfo();
    $page = $routeInfo['pageId'];
    $info = $this->getCaseList(Constant::CMODEL_CASEINFO_ID, $page);
    $total = $info[1];
    $list = $info[0];
    echo '<script>var pageInfo={total:' . $total . ',currentPage:' . $page . ',pageSize:' . $this->getOutputNum() . '}</script>';

    if ($total) {
       foreach ($list as $info) {
          $node = $info->getNode();
          echo '<tr class="news_list ">
                        <td class="news_title">
                        <span class="check"><em><i></i></em></span>
                            <span class="caption"><a target="_blank" class="main_hover" href="' . $this->getSiteCaseUrl($info->getId()) . '"><em>[' . $node->getText() . ']</em>' . $info->getTitle() . '</a></span>
                        </td>
                        <td class="news_time">' . date('Y-m-d H:i:s', $info->getInputTime()) . '</td>
                        <td class="news_operate">
                            <a href="/site/casemodify/' . $info->getId() . '.html">修改</a>
                            <span>|</span>
                            <a fh-data="' . $info->getId() . '" class="delete">删除</a>
                               <span>|</span>
                            <a  target="_blank" class="main_hover" href="' . $this->getSiteCaseUrl($info->getId()) . '">预览</a>
                        </td>
                     </tr>';
       }
       echo '</table><div class="news_delete  ">
            <span class="check"><em><i></i></em>全选</span>
            <span class="btn btn_del">删除</span>
        </div>';
    } else {
       echo '<tr class="news_list no_news">
                     <td colspan=3 >暂无案例信息，赶快去添加吧~~</td>
                 </tr></table>';
    }
    ?>
    <div class="page_list"></div>