<div class="partner_link">
    <div class="conwidth">
        <dl class="partner">
            <dt class="fl">合作伙伴：</dt>
            <dd class="fr">
					 <a href="https://www.baidu.com"><img alt="百度" target="_blank" class="gray" src="<?php Qs::Sys('loadImage', 'partner/baidu.png'); ?>"></a>
					 <a href="http://www.aliyun.com"><img alt="阿里云" target="_blank" class="gray" src="<?php Qs::Sys('loadImage', 'partner/aliyun.png'); ?>"></a>
					 <a href="http://www.sheneninfo.com"><img alt="神恩信息" target="_blank" class="gray" src="<?php Qs::Sys('loadImage', 'partner/sheneninfo.png'); ?>"></a>
            </dd>
        </dl>
        <dl class="link">
            <dt class="fl">友情链接：</dt>
            <dd class="fr main_hover">
                <a alt="百度" target="_blank" href="https://www.baidu.com">百度</a><span>|</span>
                <a alt="阿里云" target="_blank" href="http://www.aliyun.com">阿里云</a><span>|</span>
                <a alt="腾讯QQ" target="_blank" href="http://www.qq.com">QQ</a><span>|</span>
                <a alt="神恩信息" target="_blank" href="http://www.sheneninfo.com">神恩信息</a>
            </dd>
        </dl>
    </div>
</div>
<!--底部导航-->
<div class="footer">
    <div class="footer_nav_box conwidth clearfix">
        <dl class="footer_nav main_hover">
            <dt>新手指南</dt>
            <dd>
                <a target="_blank" href="/category/zhuce/1.html">免费注册</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/gongyingshangfabuxinxi/1.html">发布信息</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/zhaomaijia/1.html">找买家</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/remenwenti/1.html">积分商城</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover">
            <dt>商铺目录建设</dt>
            <dd>
                <a target="_blank" href="/category/zhuceshangpu/1.html">注册商铺</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/kaitongdianpu/1.html">开通商铺</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/shangjiachanpin/1.html">上架产品</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover">
            <dt>营销推广</dt>
            <dd>
                <a target="_blank" href="/category/yingxiaoseo/1.html">SEO</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/pinpaiguanli/1.html">品牌营销</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/huodongyingxiao/1.html">活动营销</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/shehuihuayingxiao/1.html">社会化营销</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover">
            <dt>维权服务</dt>
            <dd>
                <a target="_blank" href="/category/jiaoyizhapian/1.html">交易诈骗</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/tupianqinquan/1.html">图片侵权</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/zhishichanquan/1.html">知识产权</a>
            </dd>
            <dd>
                <a target="_blank" href="/category/weiguixinxi/1.html">违规信息</a>
            </dd>
        </dl>
        <dl class="footer_nav main_hover no_mr">
            <dt>关于我们</dt>
            <dd>
                <a target="_blank" href="/about/company.html">公司简介</a>
            </dd>
            <dd>
                <a target="_blank" href="/about/culture.html">公司文化</a>
            </dd>
            <dd>
                <a target="_blank" href="/about/qualification.html">荣誉资质</a>
            </dd>
            <dd>
                <a target="_blank" href="/about/join.html">人才招聘</a>
            </dd>
            <dd>
                <a target="_blank" href="/about/legal.html">法律声明</a>
            </dd>
        </dl>
    </div>
</div>
<!--版权-->
<div class="copy_box">
    <div class="copy_box_inner conwidth">
        <div class="links">
            <a target="_blank" href="<?php echo 'http://' .\Cntysoft\RT_PROVIDER_SITE_NAME; ?>">供应商专区</a><span>|</span>
            <a target="_blank" href="<?php echo 'http://' .\Cntysoft\RT_BUYER_SITE_NAME; ?>">采购商专区</a><span>|</span>
            <a target="_blank" href="<?php echo 'http://' .\Cntysoft\RT_SYS_SITE_NAME; ?>/category/zhuchaoschool.html">筑巢商学院</a><span>|</span>
            <a target="_blank" href="<?php echo 'http://' .\Cntysoft\RT_SYS_SITE_NAME; ?>/category/laobanneican.html">老板内参</a><span>|</span>
            <a target="_blank" href="<?php echo 'http://' .\Cntysoft\RT_SYS_SITE_NAME; ?>/category/help.html">帮助中心</a>
        </div>
        <div class="links copy_list">
            增值电信业务经营许可证：豫 B2-20160047
        </div>
        <p class="links copy_list">
            Copyright 2010-2016 www.fhzc.com All Rights Reserved <a target="_blank" href="http://www.miibeian.gov.cn"> 豫ICP备14029737号</a> <?php echo round((microtime(true) - SYS_START_TIME)*1000, 2) . 'ms'; ?>
        </p>
        <div class="cert">
            <span><a target="_blank" href="http://jubao.china.cn:13225/reportform.do"><img src="<?php Qs::Sys('loadImage', 'footer/baokong.png'); ?>"/></a></span>
            <span><a target="_blank" href="http://www.miibeian.gov.cn"><img src="<?php Qs::Sys('loadImage', 'footer/zhengxin.png'); ?>"/></a></span>
            <span><img src="<?php Qs::Sys('loadImage', 'footer/wangjian.png'); ?>"/></span>
            <span><img src="<?php Qs::Sys('loadImage', 'footer/yinlian.png'); ?>"/></span>
        </div>
    </div>
</div>