<div class="l_footer">
    <div class="m_footer conwidth clearfix">
        <div class="company_link">
            <ul class="clearfix">
                <li><a href="/aboutus.html">企业介绍</a></li>
                <li><a href="/productclassify/3/1.html">产品中心</a></li>
                <li><a href="/aboutus.html">关于我们</a></li>
                <li><a href="/news/newscenter.html">新闻中心</a></li>
                <li><a href="/aboutus.html">企业文化</a></li>
                <li><a href="/recruit.html">招聘中心</a></li>
            </ul>
        </div>
        <div class="company_connect">
            <p><i class="icon-dianhua1"></i>电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话：15623480954</p>
            <p><i class="icon-iconfontzuobiao"></i>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：<?php Qs::DsField('CP', 'PCD') ?><?php Qs::DsField('CP', 'address') ?></p>
            <p><i class="icon-101"></i>工作时间：周一到周日（08:30——18:00）</p>
        </div>
        <div class="company_code">
            <div class="qrcode">
                <img src="../../Images/test/test_erweima.jpg" alt="">
            </div>
            <p>企业微信</p>
        </div>
        <div class="company_code">
            <div class="qrcode">
                <img src="../../Images/test/test_erweima.jpg" alt="">
            </div>
            <p>企业微博</p>
        </div>
    </div>
    <div class="footer_bottom">
        © 2008-2016 sheneninfo.com 版权所有
    </div>
</div>