<div class="footer">
    <div class="footer_content conwidth clearfix">
<!--        <div class="ft_pro ft_list">
            <h4>产品</h4>
            <ul>
                <li><a href="">可乐云商</a></li>
                <li><a href="">凤凰筑巢</a></li>
                <li><a href="">成功案例</a></li>
            </ul>
        </div>-->
        <div class="ft_about ft_list">
            <h4>关于我们</h4>
            <ul>
                <li><a href="http://www.fhzc.com/about/company.html" target="_blank">公司介绍</a></li>
                <li><a href="http://www.fhzc.com/about/culture.html" target="_blank">公司文化</a></li>
                <li><a href="http://www.fhzc.com/about/qualification.html" target="_blank">企业资质</a></li>
                <li><a href="http://www.fhzc.com/about/ad.html" target="_blank">公司环境</a></li>
                <li><a href="http://www.fhzc.com/about/join.html" target="_blank">招聘英才</a></li>
            </ul>
        </div>
        <div class="ft_connect ft_list">
            <h4>联系我们</h4>
            <ul>
                <li> <i class="icon-dianhua"></i>
                    电话：0371-55221883</li>
                <li> <i class="icon-weixin"></i>
                    微信：sheneninfo</li>
                <li><i class="icon-youxiang"></i>
                    邮箱：ceo@sheneninfo.com</li>
            </ul>
        </div>
        <div class="ft_weixin">
            <img src="<?php Qs::Sys('loadImage', 'kelepc/icon/icon_weixin.png') ?>">
            <div class="weixin_text">
                <p class="">神恩信息公众号</p>
                <p>微信扫码关注</p>
            </div>
        </div>
    </div>
    <div class="footer_bottom">© 2016 Kelecloud.com 可乐云商 保留所有权利<br>
        Copyright 2010-2016 www.kelecloud.com All Rights Reserved <a class="" style="color: #bbb" target="_blank" href="http://www.miibeian.gov.cn"> 豫ICP备14029737号</a> <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></div>
</div>