<div class="l_footer">
    <div class="m_footer conwidth clearfix">
        <div class="company_link">
            <ul class="clearfix">
                <li><a href="/about.html?intro">企业介绍</a></li>
                <li><a href="/productlist/1.html">产品中心</a></li>
                <li><a href="/about.html">关于我们</a></li>
                <li><a href="/newscenter.html">新闻中心</a></li>
                <li><a href="/about.html?culture">企业文化</a></li>
                <li><a href="/joinus.html">招聘中心</a></li>
            </ul>
        </div>
        <div class="company_connect">
            <p><i class="icon-dianhua1"></i>电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话：<?php Qs::DsField('CP', 'contact') ?></p>
            <p><i class="icon-iconfontzuobiao"></i>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：<?php echo implode('', Qs::DsField('CP', 'PCD', true)) ?><?php Qs::DsField('CP', 'address') ?></p>
            <p><i class="icon-101"></i>工作时间：周一到周五（08:30——18:00）</p>
        </div>
        <!--        <div class="company_code">
                    <div class="qrcode">
                        <img src="../../Images/test/test_erweima.jpg" alt="">
                    </div>
                    <p>企业微信</p>
                </div>
                <div class="company_code">
                    <div class="qrcode">
                        <img src="../../Images/test/test_erweima.jpg" alt="">
                    </div>
                    <p>企业微博</p>
                </div>-->
    </div>
    <div class="footer_bottom">
        Copyright 2010-2016 www.fhzc.com All Rights Reserved <a target="_blank" style="color: #999" href="http://www.miibeian.gov.cn"> 豫ICP备14029737号</a> <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?>
    </div>
</div>