<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>业务介绍-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/index.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg_light">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">凤凰筑巢</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Mobile_Aboutus',)) ?>
            </div>
        </div>
        <!--联系我们-->
        <div class="module_title">
            <a><i class="icon-info"></i>业务介绍</a>
        </div>
        <div class="business">
            <p>凤凰筑巢是建材及其相关行业产品信息
                发布与采购的信息平台。为建材行业提
                供供应商与采购商之间的供求对接，消除
                中间商，实现信息发布、搜索、数据统计、
                优质推荐、在线洽谈等服务，让采购商以
                更低的成本、更多的选择购买到更优质的
                建材及其相关产品和服务。<img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_service.png') ?>" alt=""></p>
            <p class="clearfix">
                <span>我们为供应商提供:
                    免费开商铺，免费发布信息、
                    多种推广渠道，提高产品点击率、
                    推荐意向客户，实现供求高效对接、
                    提供产品的多种数据统计、排名等、
                    寻找精准客户.</span>
                <span>
                    我们为采购者提供:
                    免费需求发布平台、
                    所需商品的供应商信息、
                    发布商品的供应商报价、
                    行业专家讲解推荐.
                </span>
            </p>
            <!--百度地图容器-->
        </div>

        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>

        <!--<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=BPWH0tb47EkNlH6fGGzh381M&services=&t=20160121161406"></script>-->
        <?php
        Qs::Sys('loadRequireJs', 'aboutus/aboutus');
        ?>
    </body>
</html>