<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>企业资质-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/index.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">凤凰筑巢</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Mobile_Aboutus',)) ?>
            </div>
        </div>
        <!--联系我们-->
        <!--标题-->
        <div class="module_title">
            <a ><i class="icon-zizhi"></i>企业资质</a>
        </div>
        <div class="zihi">
            <ul>
                <li>
                    <div><span>营业执照<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi1.jpg') ?>"></div>
                </li>
                <li>
                    <div><span>增值电信业务经营许可证<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi2.jpg') ?>"></div>
                </li>
                <li>
                    <div><span>神恩易站系统V1.0著作权证书<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi3.jpg') ?>"></div>
                </li>
                <li>
                    <div><span>神恩UI渲染系统V1.0著作权证书<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi5.jpg') ?>"></div>
                </li>
                <li>
                    <div><span>OpenBI大数据分析系统V1.0著作权证书<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi4.jpg') ?>"></div>
                </li>
                <li>
                    <div><span>神恩内容管理系统v1.0著作权证书<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi6.jpg') ?>"></div>
                </li>
                <li>
                    <div><span>神恩工作易应用系统V1.0著作权证书<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi7.jpg') ?>"></div>
                </li>
                <li>
                    <div><span>凤凰筑巢安卓端软件v1.0著作权证书<i class="icon-xiangxiajiantou"></i></span></div>
                    <div><img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi8.jpg') ?>"></div>
                </li>
            </ul>
        </div>
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
        <?php
        Qs::Sys('loadRequireJs', 'aboutus/index');
        ?>
    </body>
</html>