<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>企业文化-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/index.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">凤凰筑巢</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Mobile_Aboutus',)) ?>
            </div>
        </div>
        <!--联系我们-->
        <div class="module_title">
            <a ><i class="icon-qiyewenhua"></i>企业文化</a>
        </div>
        <div class="culture">
            <p>神恩视创新与服务为企业之根本，倡导专业、务实、高效、
                创新的企业精神。规范的内部机制、优良的工作环境以及广阔
                的发展空间，吸引了一批年轻、 有学识、有实干精神的人才。
                凤凰筑巢是郑州神恩信息技术有限公司开发的主要项目。
            </p>
            <ul class="clearfix">
                <li>

                    <img src="<?php Qs::Sys('loadImage', 'icon/icon_culture1.png') ?>">
                    <h2>企业核心</h2>
                    <span>创新与服务</span>
                </li>
                <li>
                    <img src="<?php Qs::Sys('loadImage', 'icon/icon_culture2.png') ?>">
                    <h2>企业精神</h2>
                    <span>
                        专业、务实<br>
                        高效、创新
                    </span>
                </li>
                <li>

                    <img src="<?php Qs::Sys('loadImage', 'icon/icon_culture3.png') ?>">
                    <h2>企业思想</h2>
                    <span>
                        用信息带动企业发展<br>
                        用技术推动时代创新</span>
                </li>
            </ul>
            <p>
                公司倡导“专业、务实、高效、创新”的企业精神，具有
                良好的内部机制、优良的工作环境以及良好的激励机制，吸引
                了一批年轻的、有学识的、具有实干精神的人才。高素质、高
                水平、高效率的人才是在当今激烈的市场竞争中立于不败之地
                的保障。 我们坚持用一颗感恩的心回馈客户，以客户为中心，
                用我们的专业水平、优质服务、合理价格为客户的成功添砖加
                瓦。自公司创办以来，得到了广大客户的充分认可，我们将一
                如既往的为客户提供最优质的服务。
            </p>
        </div>
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>

        <!--<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=BPWH0tb47EkNlH6fGGzh381M&services=&t=20160121161406"></script>-->
        <?php
        Qs::Sys('loadRequireJs', 'aboutus/aboutus');
        ?>
    </body>
</html>