<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>企业资质-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/aboutus.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">凤凰筑巢</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Mobile_Aboutus',)) ?>
            </div>
        </div>
        <!--联系我们-->
        <div class="items_box ">
            <!--标题-->
            <div class="module_title">
                <a ><i class="icon-zizhi"></i>企业资质</a>
            </div>
            <div class="items_info contact_us">
                <div class="zizhi_inner">
                    <div class="zizhi_box clearfix">
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi1.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>营业执照</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi2.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>增值电信业务经营许可证</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi3.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩易站系统V1.0著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi4.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>OpenBI大数据分析系统V1.0著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi5.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩UI渲染系统V1.0著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi6.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩内容管理系统v1.0著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi7.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>神恩工作易应用系统V1.0著作权证书</p>
                                </div>
                            </div>
                        </div>
                        <div class="zizhi_ele">
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_zizhi8.jpg') ?>" alt="">
                            <div class="zizhi_intro">
                                <div>
                                    <p>凤凰筑巢安卓端软件v1.0著作权证书</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--百度地图容器-->
        </div>

        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>

        <!--<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=BPWH0tb47EkNlH6fGGzh381M&services=&t=20160121161406"></script>-->
        <?php
        Qs::Sys('loadRequireJs', 'aboutus/aboutus');
        ?>
    </body>
</html>