<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>企业简介-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/index.css', 'swiper.min.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg_light">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">凤凰筑巢</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Mobile_Aboutus',)) ?>
            </div>
        </div>
        <!--一公司介绍页面专有-->
        <div class="module_ad3 module_ad clearfix  swiper-container">
            <div class="swiper-wrapper">
                <div class="module_ad_list swiper-slide">
                    <a href="">
                        <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_summary.jpg') ?>">
                    </a>
                </div>
            </div>
            <div class="swiper-pagination"></div>
        </div>
        <!--联系我们-->
        <div class="module_title">
            <a><i class="icon-gsjianjie"></i>公司介绍</a>
        </div>
        <div class="jianjie ">
            <p>
                凤凰筑巢是郑州神恩信息技术有限公司开发的主要项目。郑州神恩信息技术有限公司是河南省鑫山实业发展有限公司的子公司，位于郑州市凤凰城内，是一家拥有国家双软认证、以Web OS应用开发、销售为主的互联网公司。
            </p>
            <p>
                河南省鑫山实业发展有限公司创建于1995年，是以商贸家居流通为核心、以文化产业为平台、以广告业为途径、以电子商务发展为辅助、以物业、物流
                业为支撑的民营集团性企业，公司员工千余人，注册资金5亿元人民币，公司净资产近百亿元。
            </p>
            <p>
                凤凰城是鑫山实业的核心产业之一，营业面积达40余万平方米，经营数十个建材家居业种，拥有商户4000余家、停车位1800多个，占据了河南省建材
                家居半数以上的市场份额。同时，城内配有图书馆、企业收藏馆、商务办公室、设计师创客空间、智能家居样板间等，并辅以金融、保险、工商、税务、邮
                政、信息、物流等综合服务配套设施。
            </p>
            <p>
                神恩视创新与服务为企业之根本，倡导专业、务实、高效、创新的企业精神。规范的内部机制、优良的工作环境以及广阔的发展空间，吸引了一批年轻、
                有学识、有实干精神的人才。
            </p>
            <!--百度地图容器-->
        </div>

        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
        <?php
        Qs::Sys('loadRequireJs', 'aboutus/index');
        ?>
    </body>
</html>