<?php
Qs::Ds('商城数据源/商城数据', 'sites');
?>
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>公司环境-<?php Qs::DsField('sites', 'SiteTitle') ?></title>
        <meta name="description" content="<?php Qs::DsField('sites', 'SiteDescription') ?>">
        <meta name="keywords" content="<?php Qs::DsField('sites', 'SiteKeywords') ?>">
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,width=device-width">
        <link rel="icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="/Statics/Skins/Pc/Images/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">
        <?php Qs::Sys('loadCss', array('aboutus/style.css', 'aboutus/work_space.css', 'swiper.min.css')); ?>
    </head>
    <body>
        <!--logo，搜索,名称-->
        <div class="headbar w clearfix main_bg_light">
            <!--logo-->
            <div class="header_left fl">
                <a href="/">
                    <span class="icon_logo">
                        <img src="<?php Qs::Sys('loadImage', 'icon/icon_logo.png') ?>" alt="logo"/>
                    </span>
                </a>
            </div>
            <!--标题-->
            <div class="header_title">
                <h2 class="text_ellipsis tc">凤凰筑巢</h2>
            </div>
            <!--更多按钮-->
            <div class="header_right fr">
                <span class="more_icon"><i class="icon-xiala"></i></span>
            </div>
            <!--下拉列表-->
            <div class="top_nav_box hide">
                <?php Qs::Label('导航栏/网站顶部', array('renderTpl' => 'Mobile_Aboutus',)) ?>
            </div>
        </div>
        <!--联系我们-->
        <!--标题-->
        <div class="module_title">
            <a ><i class="icon-fengcai"></i>公司环境</a>
        </div>
        <div class="work_space">
            <div class="module_ad clearfix  swiper-container">
                <div class="swiper-wrapper">
                    <div class="module_ad_list swiper-slide">
                        <a>
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_env1.jpg') ?>">
                        </a>
                    </div>
                </div>
                <!--进度-->
                <div class="progress">
                    公司环境<em></em>/<span></span>
                </div>
            </div>
        </div>
        <div class="work_space">
            <div class="module_ad clearfix  swiper-container">
                <div class="swiper-wrapper">
                    <div class="module_ad_list swiper-slide">
                        <a>
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_env2.jpg') ?>">
                        </a>
                    </div>
                </div>
                <!--进度-->
                <div class="progress">
                    工作状态<em></em>/<span></span>
                </div>
            </div>
        </div>
        <div class="work_space">
            <div class="module_ad clearfix  swiper-container">
                <div class="swiper-wrapper">
                    <div class="module_ad_list swiper-slide">
                        <a>
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_env3.jpg') ?>">
                        </a>
                    </div>
                </div>
                <!--进度-->
                <div class="progress">
                    领导视察<em></em>/<span></span>
                </div>
            </div>
        </div>
        <div class="work_space">
            <div class="module_ad clearfix  swiper-container">
                <div class="swiper-wrapper">
                    <div class="module_ad_list swiper-slide">
                        <a>
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_env4.jpg') ?>">
                        </a>
                    </div>
                </div>
                <!--进度-->
                <div class="progress">
                    文艺演出<em></em>/<span></span>
                </div>
            </div>
        </div>
        <div class="work_space">
            <div class="module_ad clearfix  swiper-container">
                <div class="swiper-wrapper">
                    <div class="module_ad_list swiper-slide">
                        <a>
                            <img src="<?php Qs::Sys('loadImage', 'aboutus/icon/icon_env5.jpg') ?>">
                        </a>
                    </div>
                </div>
                <!--进度-->
                <div class="progress">
                    员工风采<em></em>/<span></span>
                </div>
            </div>
        </div>
        <div class="copy">
            <p>增值电信业务经营许可证：豫 B2-20160047<br/>
                &copy; 2010-2016 www.fhzc.com All Rights Reserved <br/>豫ICP备14029737号 <?php echo round((microtime(true) - SYS_START_TIME) * 1000, 2) . 'ms'; ?></p>
        </div>
        <?php
        Qs::Sys('loadRequireJs', 'aboutus/work_space');
        ?>
    </body>
</html>